import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { extractArticleRows } from "../api/mexal/sync-products.js";

const payload = { dati: [{ codice: " IT0001 " }, { codice_articolo: "mkt-2" }, { codice: "IMP3" }, { codice: "NO4" }] };
const rows = extractArticleRows(payload);
assert.equal(rows.length, 4, "parses the Mexal dati list wrapper");
const api = await readFile("api/mexal/sync-products.js", "utf8");
const service = await readFile("src/modules/integrations/services/mexalSyncService.js", "utf8");
assert.match(api, /normalizeCode\(value\).*trim\(\)\.toUpperCase\(\)/s);
assert.match(api, /ARTICLE_PREFIXES = \["IT", "MKT", "IMP"\]/);
assert.match(api, /async function findExistingProduct[\s\S]*\.from\("prodotti"/);
assert.match(api, /async function saveProduct[\s\S]*\.from\("prodotti"/);
assert.match(api, /async function syncCatalogImage/);
assert.match(api, /ensureImageBucket\(supabase\)/);
assert.match(api, /\.from\("ordini_prodotti_cache"\)/);
assert.match(api, /onConflict: "codice_articolo"/);
assert.match(api, /codice_articolo: code/);
assert.match(api, /mappedByCode = new Map/);
assert.match(api, /saveProduct[\s\S]*mapArticleToOrdersCache/);
assert.match(api, /assertRunStillRunning[\s\S]*upsertOrdersProductsCache/);
assert.match(api, /cache_writes: totals/);
assert.match(api, /previousInserted[\s\S]*totalProductWrites[\s\S]*totalCacheWrites/);
assert.match(api, /noRowsDiagnostic[\s\S]*"failed"[\s\S]*"completed"/);
assert.doesNotMatch(api, /completed_with_errors/);
assert.doesNotMatch(api, /\.delete\(\).*ordini_prodotti_cache/s);
assert.match(service, /syncRunId = data\.sync_run_id \|\| syncRunId/);
assert.match(service, /prodottiInserted[\s\S]*prodottiUpdated/);
assert.match(service, /total\.inserted \+ total\.updated \+ total\.prodottiInserted \+ total\.prodottiUpdated === 0/);
console.log("products and order cache writes, image preservation, cumulative counters, supported statuses and stop checks are wired");
