import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { compareMexalPayloads } from "../api/mexal/orders/diagnose-document.js";
const result = compareMexalPayloads({ data_documento: "20/07/2026", Cod_Conto: "C1", only_get: 1, nested: { value: "20260720" } }, { data_documento: [[1, "20/07/2026"]], cod_conto: "C1", only_post: true, nested: { value: "2026-07-20" } });
assert.deepEqual(result.missing_fields, [{ path: "$.only_get", get_type: "number" }]);
assert.deepEqual(result.additional_fields, [{ path: "$.only_post", post_type: "boolean" }]);
assert.deepEqual(result.type_differences, [{ path: "$.data_documento", get_type: "string", post_type: "array" }]);
assert.deepEqual(result.format_differences, [{ path: "$.nested.value", get_format: "date-yyyymmdd", post_format: "date-yyyy-mm-dd" }]);
assert.deepEqual(result.nomenclature_differences, [{ path: "$", get_field: "Cod_Conto", post_field: "cod_conto" }]);
const endpoint = await readFile("api/mexal/orders/diagnose-document.js", "utf8");
assert.match(endpoint, /getJson\(resource\)/, "the diagnostic performs the Mexal GET");
assert.doesNotMatch(endpoint, /postJson\(/, "the diagnostic never performs a Mexal POST");
assert.match(endpoint, /get_payload: getPayload, post_payload: postPayload, comparison/, "the full GET and generated POST payload are persisted");
console.log("mexal order payload diagnostic: GET snapshot and structural comparison verified");
