import assert from 'node:assert/strict';
import { invoiceCoverage, attachInvoiceLinks } from '../src/modules/orders/services/orderInvoiceReconciliation.js';
import { getOrderDisplayStatus } from '../src/modules/orders/services/orderDisplayStatus.js';
const expected=[{code:'A',unit:'1',quantity:10},{code:'B',unit:'1',quantity:2}];
const invoice=(id,a,b)=>({id,single_order:true,articles:[[1,'A'],[2,'B']],quantities:[[1,a],[2,b]],units:[[1,'1'],[2,'1']]});
assert.equal(invoiceCoverage(expected,[invoice('1',5,1)]),'partial');
assert.equal(invoiceCoverage(expected,[invoice('1',5,1),invoice('2',5,1)]),'full');
assert.equal(invoiceCoverage(expected,[invoice('1',5,1),invoice('1',5,1)]),'partial','Duplicate invoice must not double quantities');
assert.equal(invoiceCoverage([{code:'A',quantity:10}],[invoice('1',10,2)]),'linked');
assert.equal(invoiceCoverage(expected,[{...invoice('1',10,2),single_order:false}]),'linked');
assert.equal(invoiceCoverage(expected,[{...invoice('1',10,2),units:[[1,'2'],[2,'1']]}]),'linked');
const order={id:'o',modulo_ordini:'prof',stato:'confermato',stato_sincronizzazione:'completato',numero_ocm:'3'};
const [linked]=attachInvoiceLinks([order],[{ordine_id:'o',invoice:invoice('1',5,1),expected_lines:expected}]);
assert.equal(getOrderDisplayStatus(linked).label,'PARZIALMENTE FATTURATO');
assert.equal(getOrderDisplayStatus(linked).closed,getOrderDisplayStatus(order).closed,'Invoice evidence must not change operational permissions');
assert.equal(getOrderDisplayStatus({stato_sincronizzazione:'annullato'}).label,'NON PRESENTE');
assert.equal(getOrderDisplayStatus(order).label,'INVIATO');
assert.equal(getOrderDisplayStatus({...linked,modulo_ordini:'ph',stato:'aperto'}).label,'APERTO');
console.log('Invoice coverage, ambiguity, units, deduplication and operational state: PASS');
