import test from 'node:test';import assert from 'node:assert/strict';
import {privateProductionRecord as project,privateComparisons,matchesPrivateDates} from '../src/features/production-costs/private-report.js';
import {displayRecord} from '../src/features/production-costs/cost-display.js';
const base={id:1,closed:true,plannedObjective:25,quantity:100,goodQuantity:50,commercial:{octRevenue:100,invoiceRevenue:110},actualTotal:120,plannedTotal:999,baseline:{secret:true},phases:[{id:1,personnel:[{name:'hidden'}],actualHours:2,plannedHours:88}]};
test('private OC actual and invoice values exactly match standard including partial OC',()=>{
 for(const patch of [{},{goodQuantity:0},{goodQuantity:null},{goodQuantity:150},{commercial:{octRevenue:100,octPartial:true,invoiceRevenue:110}}]){const r={...base,...patch},p=project(r),s=displayRecord(r);assert.equal(p.workedOct,s.octRevenue);assert.equal(p.comparisonTotal,s.actualWithObjective);assert.equal(p.invoiceValue,r.commercial.invoiceRevenue);}
});
test('objective included once without disclosing internal data',()=>{const r=project(base);assert.equal(r.comparisonTotal,145);assert.equal(r.excess,45);assert.ok(r.detail);for(const secret of ['planned','Objective','baseline','secret','personnel','hidden'])assert.equal(JSON.stringify(r).includes(secret),false);});
test('operational detail only when actual exceeds OC',()=>{for(const patch of [{actualTotal:50},{actualTotal:75},{actualTotal:null},{commercial:{octRevenue:null}}]){const p=project({...base,...patch});assert.equal(p.detail,undefined);}});
test('available partial costs are consistent with standard',()=>{const r={...base,actualTotal:null,actualLabor:80};assert.equal(project(r).comparisonTotal,displayRecord(r).actualWithObjective);assert.equal(project(r).actualPartial,true);});
test('each comparison uses its own available pairs and counts missing values separately',()=>{
 const rows=[{invoiceValue:90,workedOct:100,comparisonTotal:120},{invoiceValue:50,workedOct:null,comparisonTotal:60},{invoiceValue:null,workedOct:30,comparisonTotal:40},{invoiceValue:0,workedOct:0,comparisonTotal:0}];
 const [fo,fc,oc]=privateComparisons(rows);assert.equal(fo.difference,-10);assert.equal(fo.items.length,2);assert.equal(fo.missingLeft,1);assert.equal(fo.missingRight,1);assert.equal(fc.difference,-40);assert.equal(fc.items.length,3);assert.equal(oc.difference,-30);assert.equal(oc.items.length,3);
});
test('no pairs stays unavailable, positive balances are retained for display suppression',()=>{assert.equal(privateComparisons([{invoiceValue:null,workedOct:null,comparisonTotal:30}])[0].difference,null);assert.equal(privateComparisons([{invoiceValue:200,workedOct:100,comparisonTotal:50}])[0].difference,100);});
test('month and inclusive date range filters use the same start or order date',()=>{const r=project({...base,date:'2026-08-01',works:[{start:'2026-09-15T08:00:00',end:'2026-09-16',state:'Terminato'}]});assert.equal(matchesPrivateDates(r,{month:'2026-09',from:'2026-09-15',to:'2026-09-15'}),true);assert.equal(matchesPrivateDates(r,{month:'2026-08'}),false);assert.equal(matchesPrivateDates({date:null},{month:'2026-09'}),false);assert.equal(matchesPrivateDates({date:null},{}),true);});
test('legacy order references conclusion and safe invoice references retained',()=>{const r=project({...base,orderNumber:'OC/2/144',customerCode:'501.00995',works:[{end:'2026-09-16',state:'Terminato'}],commercial:{octRevenue:100,octPartial:true,octReasons:['STATION secret'],invoiceRevenue:120,invoices:[{document:{sigla:'FT',serie:1,numero:42,secret:'hidden'}},{document:{sigla:'FT',serie:1,numero:42}}]}});assert.deepEqual(r.octReferences,['OC/2/144']);assert.deepEqual(r.invoiceReferences,['FT 1/42']);assert.equal(r.octPartial,true);assert.equal(r.concludedAt,'2026-09-16');assert.equal(r.isSali,true);assert.equal(JSON.stringify(r).includes('secret'),false);});
