import { agreementDisplay, AGREEMENT_FIELDS } from './hrAgreements';
import { formatDate, romeDay } from './hrTime';

const DAYS = ['Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'];
function Value({ label, children }) { return <dl><dt>{label}</dt><dd>{children}</dd></dl>; }
export default function HrEmployeeDetails({ employee, contracts, sites, onEdit }) {
  const ordered = [...contracts].sort((a, b) => b.effective_from.localeCompare(a.effective_from) || (b.created_at || '').localeCompare(a.created_at || ''));
  const current = ordered.find(c => c.effective_from <= romeDay());
  const value = key => agreementDisplay(current, key, sites);
  const days = value('weekdays').split(',').map(s => s.trim());
  const readableDays = days.every(d => /^[1-7]$/.test(d));
  return <><div className="hr-heading hr-profile-head"><div className="hr-profile-identity"><span className="hr-avatar" aria-hidden="true">{employee.name.split(' ').map(s => s[0]).slice(0, 2).join('')}</span><div><h2>{employee.name}</h2><span className="hr-muted hr-small">{employee.manager ? 'Gestore HR' : 'Dipendente'} · <span className={`hr-badge ${employee.active ? 'green' : ''}`}>{employee.active ? 'Attivo' : 'Non attivo'}</span></span></div></div><button onClick={onEdit}>Modifica scheda</button></div>
    <div className="hr-card-scroll hr-profile-content" tabIndex={0} aria-label="Dati e accordi dipendente"><section className="hr-profile-group"><h3>Anagrafica e organizzazione</h3><div className="hr-profile-grid"><Value label="Matricola">{employee.employee_code || 'Non indicata'}</Value><Value label="Sede">{value('site_id')}</Value><Value label="Reparti operativi">{employee.department || 'Non indicati'}</Value><Value label="Appartenenza aggiuntiva">Human Resources</Value></div></section>
      {current ? <><section className="hr-profile-group"><div className="hr-heading"><h3>Orario pattuito</h3><span className="hr-muted hr-small">Dal {formatDate(current.effective_from)}</span></div><div className="hr-profile-grid"><Value label="Ore settimanali">{value('weekly_hours')}</Value><Value label="Fascia oraria">{value('start_time')} – {value('end_time')}</Value><Value label="Pausa non lavorata · minuti">{value('break_minutes')}</Value><Value label="Giorni lavorativi">{readableDays ? <span className="hr-day-chips">{days.map(d => <span key={d}>{DAYS[Number(d) - 1]}</span>)}</span> : value('weekdays')}</Value></div></section><section className="hr-profile-group"><h3>Accordi economici</h3><div className="hr-profile-grid"><Value label="Compenso pattuito">{value('agreed_pay')}</Value><Value label="Periodicità">{value('pay_period')}</Value><Value label="Gestione straordinari">{value('overtime_mode')}</Value><Value label="Tariffa straordinario · €/ora">{value('overtime_rate')}</Value><Value label="Maggiorazione · %">{value('overtime_percent')}</Value></div></section></> : <p className="hr-note">Nessun accordo in vigore. Usa Modifica scheda per inserire orario e accordi.</p>}
      <details className="hr-profile-history"><summary>Storico e accordi futuri ({ordered.length})</summary>{ordered.map(c => <article className="hr-contract" key={c.id}><h3>Dal {formatDate(c.effective_from)}{c.effective_from > romeDay() ? ' · Programmato' : ''}</h3>{AGREEMENT_FIELDS.map(([key, label]) => <p key={key}>{label}: <strong>{agreementDisplay(c, key, sites)}</strong></p>)}</article>)}</details><p className="hr-muted hr-small">I campi descrittivi o incompleti non generano automaticamente turni o importi.</p></div></>;
}
