import {useState} from 'react';
import {Modal} from './common';
import CostInfo from './CostInfo';
import {money,quantity,signedMoney} from './client';
const sum=(rows,key)=>{const values=rows.map(r=>r[key]).filter(v=>v!=null);return values.length?values.reduce((a,b)=>a+b,0):null;};
export default function CostSummaryCards({rows,privateView=false}){
 const [selected,setSelected]=useState(null);
 const activate=(title,items)=>({role:"button",tabIndex:0,onClick:()=>setSelected({title,items}),onKeyDown:e=>{if(e.target===e.currentTarget&&(e.key==="Enter"||e.key===" ")){e.preventDefault();setSelected({title,items});}}});
 const matched=rows.filter(r=>r.oct!=null&&r.actual!=null&&r.objective!=null&&!r.octPartial),excluded=rows.filter(r=>!matched.includes(r));
 const oct=sum(matched,'oct'),actual=sum(matched,'actual'),objective=sum(matched,'objective');
 const difference=oct!=null&&actual!=null&&objective!=null?oct-actual-objective:null;
 const plannedRows=matched.filter(r=>r.planned!=null);
 const planDifference=plannedRows.length?plannedRows.reduce((s,r)=>s+r.oct-r.planned-r.objective,0):null;
 return <><div className="pc-cards pc-summary-cards">
 {(privateView?[["Costi consuntivi","actual"]]:[["Costi preventivi","planned"],["Costi consuntivi","actual"]]).map(([label,key])=><article className="pc-card pc-card-clickable" key={key} {...activate(label,rows)}><span>{label}<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title={label}><p>Solo produzioni chiuse nel filtro. Confrontabili: OCT completo, costi consuntivi e obiettivo STATION disponibili. Le altre produzioni sono separate e non concorrono allo scostamento. Gli importi includono soltanto le componenti di costo disponibili e non comprendono l’obiettivo STATION.</p></CostInfo></span></span><small>Con OCT confrontabile · {quantity(matched.length)} produzioni</small><strong>{money(sum(matched,key))}</strong><small>Senza confronto OCT · {quantity(excluded.length)} produzioni</small><strong>{money(sum(excluded,key))}</strong><small>Costi disponibili: possono essere parziali.</small></article>)}
 <article className="pc-card pc-card-clickable" {...activate("Valore netto OCT",rows)}><span>Valore netto OCT confrontabili<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title="Valore netto OCT"><p>Somma delle quote nette degli ordini attribuite alle sole produzioni confrontabili. IVA esclusa. Non è un utile, un incasso o un valore fatturato. Non è il totale globale di tutti gli OCT. Nella vista Private la quota è riferita alle quantità lavorate.</p></CostInfo></span></span><strong>{money(oct)}</strong><small>{quantity(matched.length)} produzioni chiuse confrontabili</small><small>OCT disponibili sulle produzioni escluse</small><strong>{money(sum(excluded,'oct'))}</strong></article>
 <article className="pc-card pc-card-clickable" {...activate("Copertura costi e obiettivo STATION",matched)}><span>Copertura costi e obiettivo STATION<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title="Come si calcola il confronto"><p>OCT meno costi meno obiettivo STATION previsto. Tutti gli importi del confronto consuntivo riguardano le stesse produzioni. Un valore negativo indica quanto manca per coprire costi e obiettivo: non è una perdita contabile, perché comprende anche il margine desiderato. Costi parziali rendono provvisorio il risultato. Il confronto preventivo esclude inoltre le produzioni senza preventivo disponibile.</p></CostInfo></span></span><small>Valore OCT: {money(oct)}</small><small>− Costi consuntivi: {money(actual)}</small><small>− Obiettivo STATION: {money(objective)}</small>{(!privateView||difference<0)&&<><small>Saldo dopo costi e obiettivo</small><strong>{signedMoney(difference)}</strong></>}{privateView&&difference>=0&&difference!=null&&<small>Nessuna eccedenza rispetto all’OCT.</small>}{!privateView&&<><small>OCT − preventivo − obiettivo · {quantity(plannedRows.length)} produzioni</small><strong>{signedMoney(planDifference)}</strong></>}<small>Confronto sui dati disponibili, non utile definitivo.</small></article>
 </div>{selected&&<Modal title={selected.title+" · produzioni chiuse"} onClose={()=>setSelected(null)}><p>Documenti e lavorazioni che compongono la card. Gli importi indicano i dati disponibili e possono essere parziali.</p><div className="pc-table-wrap"><table><thead><tr><th>RdP / lavorazione</th><th>Cliente / prodotto</th><th>OCT</th><th>Confronto</th>{!privateView&&<th>Preventivo</th>}<th>Consuntivo</th><th>Obiettivo STATION</th><th>Valore OCT</th><th>OCT − costi e obiettivo</th></tr></thead><tbody>{selected.items.map((r,i)=><tr key={r.id??i}><td>{r.order||r.id}</td><td>{r.customer}<small>{r.articleCode} · {r.description}</small></td><td>{r.references?.join(' · ')||'Riferimento non disponibile'}</td><td>{matched.includes(r)?'Confrontabile':'Esclusa'}{!matched.includes(r)&&<small>{r.reasons?.join(' ')||'OCT, costi o obiettivo non disponibili o non confrontabili.'}</small>}</td>{!privateView&&<td>{money(r.planned)}</td>}<td>{money(r.actual)}</td><td>{money(r.objective)}</td><td>{money(r.oct)}</td><td>{matched.includes(r)?signedMoney(r.oct-r.actual-r.objective):'—'}</td></tr>)}</tbody></table></div>{!selected.items.length&&<p>Nessuna produzione chiusa nel filtro.</p>}</Modal>}</>;

}
