import {useState} from 'react';
import {Modal} from './common';
import CostInfo from './CostInfo';
import {money,quantity,signedMoney} from './client';
const balanceClass=value=>value==null||value===0?"":" "+(value>0?"pc-balance-positive":"pc-balance-negative");
const sum=(rows,key)=>{const values=rows.map(r=>r[key]).filter(v=>v!=null);return values.length?values.reduce((a,b)=>a+b,0):null;};
export default function CostSummaryCards({rows,privateView=false}){
 const [selected,setSelected]=useState(null);
 const activate=(title,items)=>({role:"button",tabIndex:0,onClick:()=>setSelected({title,items}),onKeyDown:e=>{if(e.target===e.currentTarget&&(e.key==="Enter"||e.key===" ")){e.preventDefault();setSelected({title,items});}}});
 const matched=rows.filter(r=>r.oct!=null&&r.actual!=null&&!r.octPartial),excluded=rows.filter(r=>!matched.includes(r));
 const oct=sum(matched,'oct'),actual=sum(matched,'actual'),objective=sum(matched,'objective');
 const difference=oct!=null&&actual!=null&&objective!=null?oct-actual:null;
 const plannedRows=matched.filter(r=>r.planned!=null);
 const planDifference=plannedRows.length?plannedRows.reduce((s,r)=>s+r.oct-r.planned,0):null;
 return <><div className="pc-cards pc-summary-cards">
 {(privateView?[["Costi consuntivi","actual"]]:[["Costi preventivi","planned"],["Costi consuntivi","actual"]]).map(([label,key])=><article className="pc-card pc-card-clickable" key={key} {...activate(label,rows)}><span>{label}<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title={label}><p>Solo produzioni chiuse nel filtro. Confrontabili: OCT completo, costi consuntivi e obiettivo STATION disponibili. Le altre produzioni sono separate e non concorrono allo scostamento. Preventivo e consuntivo comprendono tutti i costi disponibili e l’obiettivo STATION, conteggiato una sola volta.</p></CostInfo></span></span><div className="pc-summary-line"><small>Con OCT · {quantity(matched.length)} produzioni</small><strong>{money(sum(matched,key))}</strong></div><div className="pc-summary-line"><small>Senza confronto · {quantity(excluded.length)} produzioni</small><strong>{money(sum(excluded,key))}</strong></div><small className="pc-summary-footer">Costi disponibili: possono essere parziali.</small></article>)}
 <article className="pc-card pc-card-clickable" {...activate("Valore netto OCT",rows)}><span>Valore netto OCT confrontabili<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title="Valore netto OCT"><p>Somma delle quote nette degli ordini attribuite alle sole produzioni confrontabili. IVA esclusa. Non è un utile, un incasso o un valore fatturato. Non è il totale globale di tutti gli OCT. Nella vista Private la quota è riferita alle quantità lavorate.</p></CostInfo></span></span><div className="pc-summary-line"><small>Con OCT · {quantity(matched.length)} produzioni</small><strong>{money(oct)}</strong></div><div className="pc-summary-line"><small>Senza confronto · {quantity(excluded.length)} produzioni</small><strong>{money(sum(excluded,'oct'))}</strong></div><small className="pc-summary-footer">Valore netto ordini, IVA esclusa.</small></article>
 <article className="pc-card pc-card-clickable" {...activate("Differenze rispetto al valore OCT",matched)}><span>Differenze rispetto al valore OCT<span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title="Come si calcola il confronto"><p>OCT meno il totale mostrato, già comprensivo dell’obiettivo STATION. Tutti gli importi del confronto consuntivo riguardano le stesse produzioni. Un valore negativo indica quanto manca per coprire costi e obiettivo: non è una perdita contabile, perché comprende anche il margine desiderato. Costi parziali rendono provvisorio il risultato. Il confronto preventivo esclude inoltre le produzioni senza preventivo disponibile.</p></CostInfo></span></span><div className="pc-summary-line"><small>Saldo consuntivo · {quantity(matched.length)} produzioni</small><strong className={balanceClass(difference)}>{privateView&&difference>=0&&difference!=null?'Nessuna eccedenza':signedMoney(difference)}</strong></div><div className="pc-summary-line"><small>{privateView?'Obiettivo STATION':'Saldo preventivo · '+quantity(plannedRows.length)+' produzioni'}</small><strong className={privateView?'':balanceClass(planDifference)}>{privateView?money(objective):signedMoney(planDifference)}</strong></div><small className="pc-summary-footer">OCT {money(oct)} − consuntivo {money(actual)}. Saldi provvisori, non utile definitivo.</small></article>
 </div>{selected&&<Modal title={selected.title+" · produzioni chiuse"} onClose={()=>setSelected(null)}><p>Documenti e lavorazioni che compongono la card. Gli importi indicano i dati disponibili e possono essere parziali.</p><div className="pc-table-wrap"><table><thead><tr><th>RdP / lavorazione</th><th>Cliente / prodotto</th><th>OCT</th><th>Confronto</th>{!privateView&&<th>Preventivo</th>}<th>Consuntivo</th><th>Valore OCT</th><th>OCT − preventivo</th><th>OCT − consuntivo</th></tr></thead><tbody>{selected.items.map((r,i)=><tr key={r.id??i}><td>{r.order||r.id}</td><td>{r.customer}<small>{r.articleCode} · {r.description}</small></td><td>{r.references?.join(' · ')||'Riferimento non disponibile'}</td><td>{matched.includes(r)?'Confrontabile':'Esclusa'}{!matched.includes(r)&&<small>{r.reasons?.join(' ')||'OCT, costi o obiettivo non disponibili o non confrontabili.'}</small>}</td>{!privateView&&<td>{money(r.planned)}</td>}<td>{money(r.actual)}</td><td>{money(r.oct)}</td><td className={matched.includes(r)?balanceClass(r.oct-r.planned):""}>{matched.includes(r)&&r.planned!=null?signedMoney(r.oct-r.planned):'—'}</td><td className={matched.includes(r)?balanceClass(r.oct-r.actual):""}>{matched.includes(r)?signedMoney(r.oct-r.actual):'—'}</td></tr>)}</tbody></table></div>{!selected.items.length&&<p>Nessuna produzione chiusa nel filtro.</p>}</Modal>}</>;

}
