import {InvoiceCells,InvoiceHeaders} from "./InvoiceSummary";
import {useState} from 'react';
import {Modal} from './common';
import CostInfo from './CostInfo';
import {money,quantity,signedMoney} from './client';
import {summaryGroups,total,pairedDifference} from './summary-totals';
const balanceClass=value=>value==null||value===0?"":" "+(value>0?"pc-balance-positive":"pc-balance-negative");
function Info({title,children}){return <span onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><CostInfo title={title}><p>{children}</p></CostInfo></span>;}
function Metric({label,value,signed=false}){return <div><span>{label}</span><strong className={signed?balanceClass(value):''}>{signed?signedMoney(value):money(value)}</strong></div>;}
export default function CostSummaryCards({rows}){
 const [selected,setSelected]=useState(null);
 const activate=(title,items)=>({role:"button",tabIndex:0,onClick:()=>setSelected({title,items}),onKeyDown:e=>{if(e.target===e.currentTarget&&(e.key==="Enter"||e.key===" ")){e.preventDefault();setSelected({title,items});}}});
 const {matched,excluded,invoiced,uninvoiced,invoiceOc}=summaryGroups(rows);
 return <><div className="pc-financial-overview">
 <article className="pc-panel pc-card-clickable" {...activate('Costi',rows)}><h3>Costi<Info title="Costi">Tutte le lavorazioni concluse nel filtro. Preventivi e consuntivi comprendono i costi disponibili e l’obiettivo STATION una sola volta. Differenza = preventivo meno consuntivo, calcolata solo sulle lavorazioni con entrambi i valori. Blu: risparmio; rosso: maggiore costo. I costi incompleti restano parziali.</Info></h3><div className="pc-financial-metrics"><Metric label="Preventivi" value={total(rows,'planned')}/><Metric label="Consuntivi" value={total(rows,'actual')}/><Metric label="Differenza" value={pairedDifference(rows,'planned','actual')} signed/></div><footer>{quantity(rows.length)} lavorazioni · {quantity(rows.filter(r=>r.planned==null||r.actual==null).length)} escluse dalla differenza</footer></article>
 <article className="pc-panel pc-card-clickable" {...activate('OC',matched)}><h3>OC<Info title="Confronti OC">Valore netto OC attribuito alle lavorazioni confrontabili. Differenza sul consuntivo = OC meno consuntivo; differenza sul preventivo = OC meno preventivo. Ogni confronto include solo le lavorazioni con entrambi gli importi disponibili e OC non parziale. Blu: saldo positivo; rosso: saldo negativo. Non è un utile contabile definitivo.</Info></h3><div className="pc-financial-metrics"><Metric label="Valore netto OC" value={total(matched,'oct')}/><Metric label="Differenza su consuntivi" value={pairedDifference(matched,'oct','actual')} signed/><Metric label="Differenza su preventivi" value={pairedDifference(matched,'oct','planned')} signed/></div><footer>{quantity(matched.length)} con OC · {quantity(excluded.length)} senza confronto · {quantity(matched.filter(r=>r.planned==null).length)} senza preventivo</footer></article>
 <article className="pc-panel pc-card-clickable" {...activate('Fatturato',invoiced)}><h3>Fatturato<Info title="Confronti fatturato">Somma netta delle fatture attribuite alle lavorazioni concluse. Le differenze sono fatturato meno consuntivo e fatturato meno OC. Ogni confronto usa solo coppie di importi disponibili. Il confronto OC esclude anche gli OC parziali. Le lavorazioni senza fattura sono escluse da tutti i conteggi di questa card. Blu: saldo positivo; rosso: saldo negativo.</Info></h3><div className="pc-financial-metrics"><Metric label="Fatturato netto" value={total(invoiced,'invoice')}/><Metric label="Differenza su consuntivi" value={pairedDifference(invoiced,'invoice','actual')} signed/><Metric label="Differenza su OC" value={pairedDifference(invoiceOc,'invoice','oct')} signed/></div><footer>{quantity(invoiced.length)} fatturate · {quantity(uninvoiced.length)} senza fattura<br/>Confronto OC: {quantity(invoiceOc.length)} incluse · {quantity(invoiced.length-invoiceOc.length)} fatturate escluse</footer></article>
 </div><div className="pc-financial-exclusions">
 <article className="pc-panel"><h3>Lavorazioni senza confronto OC · {quantity(excluded.length)}<Info title="Escluse dal confronto OC">OC assente, parziale o non confrontabile, oppure consuntivo non disponibile. Queste lavorazioni restano nei costi complessivi ma sono escluse dai confronti OC. Il dettaglio riporta i motivi disponibili.</Info></h3><button onClick={()=>setSelected({title:'Lavorazioni escluse dal confronto OC',items:excluded})}>Mostra lavorazioni</button></article>
 <article className="pc-panel"><h3>Lavorazioni senza fattura · {quantity(uninvoiced.length)}<Info title="Escluse dal fatturato">Nessuna fattura attribuibile nei dati importati. Queste lavorazioni non concorrono al totale fatturato né ai suoi confronti; restano visibili negli altri riepiloghi.</Info></h3><button onClick={()=>setSelected({title:'Lavorazioni escluse senza fattura',items:uninvoiced})}>Mostra lavorazioni</button></article>
 </div>{selected&&<Modal title={selected.title+" · produzioni chiuse"} onClose={()=>setSelected(null)}><p>Documenti e lavorazioni che compongono la card. Gli importi indicano i dati disponibili e possono essere parziali.</p><div className="pc-table-wrap"><table><thead><tr><th>RdP / lavorazione</th><th>Cliente / prodotto</th><th>OC</th><th>Confronto</th><th>Preventivo</th><th>Consuntivo</th><th>Valore OC</th><th>OC − preventivo</th><th>OC − consuntivo</th><InvoiceHeaders/></tr></thead><tbody>{selected.items.map((r,i)=><tr key={r.id??i}><td>{r.order||r.id}</td><td>{r.customer}<small>{r.articleCode} · {r.description}</small></td><td>{r.references?.join(' · ')||'Riferimento non disponibile'}</td><td>{matched.includes(r)?'Confrontabile':'Esclusa'}{!matched.includes(r)&&<small>{r.reasons?.join(' ')||'OC, costi o obiettivo non disponibili o non confrontabili.'}</small>}</td><td>{money(r.planned)}</td><td>{money(r.actual)}</td><td>{money(r.oct)}</td><td className={matched.includes(r)?balanceClass(r.oct-r.planned):""}>{matched.includes(r)&&r.planned!=null?signedMoney(r.oct-r.planned):'—'}</td><td className={matched.includes(r)?balanceClass(r.oct-r.actual):""}>{matched.includes(r)?signedMoney(r.oct-r.actual):'—'}</td><InvoiceCells invoice={r.invoice} oc={r.oct} actual={r.actual} references={r.invoiceReferences}/></tr>)}</tbody></table></div>{!selected.items.length&&<p>Nessuna produzione chiusa nel filtro.</p>}</Modal>}</>;

}
