import { useEffect, useMemo, useRef, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { Field, Numeric, Modal } from "./common";
import { action, money, quantity, date } from "./client";
import { sumKnown, delta, percent } from "./cost-engine";
import { matchesProductionSearch } from "./search";
import StationHistorySummary from "./StationHistorySummary";
import StationOvertime from "./StationOvertime";

function CostTable({record:r}){
 const rows=[["Materie prime",r.plannedMaterialCost,r.actualMaterialCost],["Packaging",r.plannedPackagingCost,r.actualPackagingCost],["Personale",r.plannedLabor,r.actualLabor],["Lavaggi (esclusa manodopera)",r.plannedWash,r.actualWash],["Perdite componenti SL",0,r.lossCost],["Totale costi",r.plannedTotal,r.actualTotal],["Subtotale voci disponibili (non totale definitivo)",r.plannedKnownSubtotal,r.actualKnownSubtotal],["Ricavo OCT / fatture",r.plannedRevenue,r.actualRevenue],["Margine (consuntivo sulla quantità fatturata)",r.plannedMargin,r.actualMargin],["Margine obiettivo STATION (consuntivo proporzionato al fatturato)",r.plannedObjective,r.invoicedObjective],["Margine oltre / sotto obiettivo STATION",r.plannedObjectiveVariance,r.actualObjectiveVariance]];
 return <div className="pc-table-wrap"><table><thead><tr><th>Voce</th><th>Preventivo</th><th>Consuntivo</th><th>Scostamento €</th><th>Scostamento %</th></tr></thead><tbody>{rows.map(([name,p,a])=><tr key={name}><td>{name}</td><td>{money(p)}</td><td>{money(a)}</td><td>{name.startsWith("Ricavo")||name.startsWith("Margine")?"Basi quantitative distinte":money(delta(a,p))}</td><td>{name.startsWith("Ricavo")||name.startsWith("Margine")?"—":quantity(percent(a,p))}</td></tr>)}</tbody></table></div>;
}
function Detail({record:r,token,canWrite,onClose,onChanged}){
 const [tab,setTab]=useState("Riepilogo"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reason,setReason]=useState("");
 const [washes,setWashes]=useState(()=>r.phases.filter(w=>w.id>0).map(w=>({productionId:w.id,count:w.actualWashes??"",minutes:w.actualWashMinutes??""})));
 const [invoices,setInvoices]=useState(null),[lineId,setLineId]=useState(""),[allocated,setAllocated]=useState("");
 const act=async(fn)=>{setBusy(true);setError("");try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const tabs=["Riepilogo","Tempi e personale","Materiali e SL","Economia","Tracciabilità"];
 return <Modal title={r.orderNumber+" · "+r.articleName} onClose={onClose}>
 <p className="pc-muted">{r.customerName} · {r.articleCode} · Lotto {r.lot||r.bulkLot||"non assegnato"} · Formula {r.formulaVersion||"—"} / rev. {r.formulaRevision??"—"}</p>
 <div className="pc-tabs" role="tablist">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {r.reconstructed&&<p className="pc-note"><strong>Valorizzazione storica ricostruita.</strong> Le quantità recuperate e i costi ultimi usati sono consultabili in Materiali e SL. Non sostituiscono prezzi storici non conservati nei documenti originali.</p>}
 {error&&<p className="pc-error" role="alert">{error}</p>}
 {r.stationContext&&["Riepilogo","Tempi e personale","Tracciabilità"].includes(tab)&&<StationHistorySummary history={r.stationHistory} hourly={r.stationHistoricalHourly} policyId={r.stationContext.policy?.id}/>}
 {tab==="Riepilogo"&&<><div className="pc-metrics"><div>Quantità prevista<strong>{quantity(r.quantity)} {r.unit}</strong></div><div>Quantità buona finale<strong>{quantity(r.goodQuantity)} {r.unit}</strong></div><div>Costo consuntivo / pezzo buono<strong>{money(r.unitCost)}</strong></div></div><p className="pc-note">{r.provisional?"Consuntivo provvisorio o incompleto.":"Lavorazione conclusa con costi disponibili."} Nessun valore mancante viene trattato come zero.</p>{r.warnings.map(w=><p key={w}>{w}</p>)}<CostTable record={r}/></>}
 {tab==="Tempi e personale"&&<><p>I tempi effettivi sono intervalli registrati in MES. Le presenze restano distinte dalla base economica STATION. Il tempo notturno senza turni non viene contato come lavoro ordinario.</p>{r.laborCriteria?.map(c=><p key={c}>{c}</p>)}
 {r.phases.map(w=><section className="pc-panel" key={w.id}><h3>{w.machine?.code||"Impianto "+w.machineId} · {w.phase} · {w.state}</h3><div className="pc-table-wrap"><table><thead><tr><th>Indicatore</th><th>Preventivo</th><th>Consuntivo</th></tr></thead><tbody>
 {[["Ore macchina",w.plannedHours,w.actualHours],["Turni ordinari (criterio configurato)",w.plannedTurns,w.actualTurns],["Straordinario (ore)",w.plannedOvertimeHours,w.actualOvertimeHours],["Ore/uomo per valorizzazione",w.plannedCostPersonHours,w.actualCostPersonHours],["Organico Miscelazione (STATION)",w.phase==="Semilavorato"?w.mixingOperatorsCount:null,w.phase==="Semilavorato"?w.mixingOperatorsCount:null],["Ore/uomo registrate",w.plannedPersonHours,w.actualPersonHours],["Ore/uomo entro turni (indicatore)",null,w.personHoursInShifts],["Fermi (ore)",null,w.downtimeHours],["Lavaggi",w.plannedWashes,w.actualWashes],["Lavaggi (min)",w.plannedWashMinutes,w.actualWashMinutes],["Produttività / ora",null,w.productivity],["Produttività / ora/uomo",null,w.personProductivity],["Scarti",null,w.scrapQuantity]].map(([k,p,a])=><tr key={k}><td>{k}</td><td>{quantity(p)}</td><td>{quantity(a)}</td></tr>)}</tbody></table></div>
 <h4>Operatori coinvolti</h4>{!w.personnel?.length&&<p>Presenze non disponibili.</p>}<div className="pc-table-wrap"><table><thead><tr><th>Operatore / reparto</th><th>Ruolo</th><th>Inizio</th><th>Fine</th></tr></thead><tbody>{w.personnel?.map(p=><tr key={p.id}><td>{p.name}<small>{p.department}</small></td><td>{p.role}</td><td>{p.start?.replace("T"," ")}</td><td>{p.end?.replace("T"," ")||"Presenza aperta"}</td></tr>)}</tbody></table></div></section>)}
 {canWrite&&<section className="pc-panel"><h3>Conferma lavaggi effettivamente eseguiti</h3><p>Registrazione di consuntivo con fonte obbligatoria; non cambia la lavorazione MES. Inserire zero soltanto se non ci sono stati lavaggi.</p>{washes.map((w,i)=><div className="pc-fields" key={w.productionId}><strong>Lavorazione {w.productionId}</strong><Field label="Numero lavaggi"><Numeric step="1" value={w.count} onChange={v=>setWashes(a=>a.map((x,n)=>n===i?{...x,count:v}:x))}/></Field><Field label="Minuti effettivi complessivi"><Numeric value={w.minutes} onChange={v=>setWashes(a=>a.map((x,n)=>n===i?{...x,minutes:v}:x))}/></Field></div>)}<Field label="Fonte / nota del consuntivo"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Es. registro lavaggi verificato dal responsabile"/></Field><button disabled={busy} onClick={()=>act(async()=>{await action(token,"adjust",{id:r.id,washes,reason});await onChanged();onClose();})}>Registra consuntivo lavaggi</button></section>}</>}
 {tab==="Tempi e personale"&&canWrite&&<StationOvertime record={r} token={token} onSaved={async()=>{await onChanged();onClose();}}/>}
 {tab==="Materiali e SL"&&<><p>Gli snapshot originali, se disponibili, hanno precedenza. Per lo storico si recuperano la revisione formula collegata e i prelievi scaricati: l'eventuale costo ultimo corrente è una ricostruzione, non il prezzo storico SL né una pesata manuale.</p>
 {r.historicalBaseline&&!r.baseline&&<p className="pc-note">{r.historicalBaseline.source} Revisione {r.historicalBaseline.formulaVersion} / {r.historicalBaseline.formulaRevision}; recuperata il {date(r.historicalBaseline.recoveredAt)}.</p>}
 {!!r.recoveredProducts?.length&&<section className="pc-panel"><h3>Bulk / packaging ricostruiti dagli impegni V4 consumati</h3><p>Quantità fabbisogno registrate al consumo, non quantità estratte dalla riga SL. Prezzi ultimi disponibili: stima economica.</p><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Tipo</th><th>Quantità</th><th>Costo ultimo</th><th>Consumato il</th></tr></thead><tbody>{r.recoveredProducts.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description}</small></td><td>{m.kind}</td><td>{quantity(m.quantity)} {m.unit}</td><td>{money(m.unitCost)}</td><td>{date(m.consumedAt)}</td></tr>)}</tbody></table></div></section>}
 {!!r.recoveredConsumption?.length&&<section className="pc-panel"><h3>Consumi MES recuperati · valorizzazione ricostruita</h3><div className="pc-table-wrap"><table><thead><tr><th>Materia prima / lotto</th><th>Quantità scaricata</th><th>Data scarico</th><th>Costo ultimo usato</th><th>Valore ricostruito</th></tr></thead><tbody>{r.recoveredConsumption.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description} · {m.lot}</small></td><td>{quantity(m.quantity)} {m.unit}</td><td>{date(m.withdrawnAt)}</td><td>{money(m.unitCost)}</td><td>{money(m.unitCost==null?null:m.unitCost*m.quantity)}</td></tr>)}</tbody></table></div></section>}
 <h3>Scostamenti materie prime</h3><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Q.tà formula</th><th>Q.tà SL</th><th>Prezzo preventivo</th><th>Prezzo SL</th><th>Delta consumo €</th><th>Delta prezzo €</th></tr></thead><tbody>{r.materialVariances.map(m=><tr key={m.code}><td>{m.code}</td><td>{quantity(m.plannedQuantity)}</td><td>{quantity(m.actualQuantity)}</td><td>{money(m.plannedUnitCost)}</td><td>{money(m.actualUnitCost)}</td><td>{money(m.usageVariance)}</td><td>{money(m.priceVariance)}</td></tr>)}</tbody></table></div>
 {[[r.bulkSl,"SL materie prime"],[r.productSl,"SL bulk e confezionamento"]].map(([docs,title])=><section key={title}><h3>{title}</h3>{!docs?.length&&<p>Snapshot SL non disponibile. Riferimenti storici: {r.bulkSlReference||r.productSlReference||"—"}</p>}{docs?.map((d,i)=><section className="pc-panel" key={i}><strong>{d.document} · {date(d.date)} · Magazzino {d.warehouse}</strong><p>{d.valuationSource}</p><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Lotto Mexal</th><th>Quantità</th><th>Costo unitario</th><th>Importo</th></tr></thead><tbody>{d.materials.map((m,j)=><tr key={j}><td>{m.code}</td><td>{m.lotId??"—"}</td><td>{quantity(m.quantity)}</td><td>{money(m.unitCost)}</td><td>{money(m.unitCost==null?null:m.unitCost*m.quantity)}</td></tr>)}</tbody></table></div></section>)}</section>)}
 <h3>Prelievi storici disponibili (non una valorizzazione storica)</h3><div className="pc-table-wrap"><table><thead><tr><th>Materia prima</th><th>Lotto</th><th>Quantità</th><th>Prelievo</th></tr></thead><tbody>{r.historicalMaterials?.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description}</small></td><td>{m.lot}</td><td>{quantity(m.quantity)} {m.unit}</td><td>{date(m.withdrawnAt)}</td></tr>)}</tbody></table></div></>}
 {tab==="Economia"&&<><CostTable record={r}/>{r.sourceOrder&&<p>Ordine cliente storico MES: {r.sourceOrder.reference} · {r.sourceOrder.articleCode} · {quantity(r.sourceOrder.quantity)} {r.sourceOrder.unit} · valore riga {money(r.sourceOrder.lineValue>0?r.sourceOrder.lineValue:null)}. Valore attribuito alla produzione solo se articolo, unità e quantità sono compatibili e non duplicati.</p>}<p className="pc-note">OCT e fatture sono due confronti separati, mai sommati. Il margine consuntivo usa il costo attribuito alla quantità fatturata: {quantity(r.invoicedQuantity)} {r.unit}. Le fatture non sono incassi bancari. IVA esclusa; note credito con segno negativo.</p><h3>Fatture attribuite</h3>{r.commercial.invoices?.map(x=><p key={x.id}>{x.document?.sigla} {x.document?.serie}/{x.document?.numero} · {date(x.document?.data_documento)} · {quantity(x.quantity)} · {money(x.amount)}</p>)}
 {canWrite&&<section className="pc-panel"><h3>Riconcilia fattura con la produzione</h3><p>Solo righe dello stesso cliente/articolo; la corrispondenza va confermata. La stessa quantità non può essere attribuita due volte.</p><button disabled={busy} onClick={()=>act(async()=>setInvoices((await action(token,"invoice-candidates",{id:r.id})).lines))}>Mostra righe fattura compatibili</button>
 {invoices&&<div className="pc-fields"><Field label="Riga fattura"><select value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Seleziona…</option>{invoices.map(l=><option key={l.id} value={l.id}>{l.document.sigla} {l.document.serie}/{l.document.numero} · {date(l.document.data_documento)} · {l.quantita} · {money(l.valore_netto)}</option>)}</select></Field><Field label="Quantità attribuita (valore assoluto)"><Numeric value={allocated} onChange={setAllocated}/></Field><button disabled={busy||!lineId} onClick={()=>act(async()=>{await action(token,"allocate-invoice",{id:r.id,lineId,quantity:allocated});await onChanged();onClose();})}>Conferma attribuzione</button></div>}</section>}</>}
 {tab==="Tracciabilità"&&<><h3>Fonti conservate</h3><p>Importazione MES: {r.refreshedAt?.replace("T"," ")}</p><p>Preventivo congelato: {r.baseline?.capturedAt?.replace("T"," ")||"Non disponibile per questo storico"}</p><p>Versione costi: {r.configuration?.id||"Non ancora assegnata"} · decorrenza {date(r.configuration?.effective_from)}</p><p>OCT collegati: {r.links?.map(x=>x.oct).join(", ")||"Collegamento non disponibile"}</p><h3>Registro consuntivi / rettifiche</h3>{r.audit.map(a=><p key={a.id}>{date(a.created_at)} — {a.reason}</p>)}{!r.audit.length&&<p>Nessuna integrazione manuale.</p>}</>}
 </Modal>;
}
export default function ProductionCostReports(){
 const {session}=useAuth(),token=session?.access_token;
 const [records,setRecords]=useState([]),[canWrite,setCanWrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState("");
 const [query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[state,setState]=useState(""),[machine,setMachine]=useState(""),[selected,setSelected]=useState(null);
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function load(){const r=await action(token,"list");if(mounted.current){setRecords(r.records);setCanWrite(r.canWrite);}}
 useEffect(()=>{if(!token)return;let alive=true;action(token,"list").then(r=>{if(alive){setRecords(r.records);setCanWrite(r.canWrite);}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false;};},[token]);
 async function sync(){setBusy(true);setError("");try{let page=1,result;do{result=await action(token,"sync",{page});if(!mounted.current)return;setProgress(`Importati ${Math.min(page*100,result.total)} / ${result.total} ordini MES`);page++;}while(result.hasMore);await load();}catch(e){setError(e.message);await load().catch(()=>{});}finally{if(mounted.current)setBusy(false);}}
 const machines=useMemo(()=>[...new Map(records.flatMap(r=>r.phases.map(p=>[p.machineId,p.machine?.code||"Impianto "+p.machineId]))).entries()], [records]);
 const filtered=useMemo(()=>records.filter(r=>{
  const d=String(r.works?.[0]?.start||r.date||"").slice(0,10);
  return (!from||d>=from)&&(!to||d<=to)&&(!state||(state==="closed"?r.closed:state==="incomplete"?r.provisional:!r.closed))&&(!machine||r.phases.some(p=>String(p.machineId)===machine))&&matchesProductionSearch(r,query);
 }),[records,from,to,state,machine,query]);
 const aggregate=key=>sumKnown(filtered.map(r=>r[key]));
 const knownActual=filtered.filter(r=>r.actualKnownSubtotal!==null);
 return <main className="pc-page" data-column-controls="off">
 <section className="pc-panel"><div className="pc-toolbar"><p>Nessun aggiornamento automatico durante la consultazione.</p><button className="pc-primary" disabled={busy} onClick={sync}><RefreshCw size={17}/>{busy?"Caricamento…":"Importa / aggiorna storico MES"}</button></div>{progress&&<p role="status">{progress}</p>}
 <div className="pc-filters"><Field label="Ricerca totale"><input aria-label="Ricerca totale" placeholder="Cliente, OCT/RdP, prodotto, lotto, operatore, reparto…" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Dal (avvio / data ordine)"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Al"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="Stato"><select value={state} onChange={e=>setState(e.target.value)}><option value="">Tutti</option><option value="closed">Concluse</option><option value="open">Aperte</option><option value="incomplete">Provvisorie / incomplete</option></select></Field><Field label="Impianto"><select value={machine} onChange={e=>setMachine(e.target.value)}><option value="">Tutti</option>{machines.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></div></section>
 {error&&<p className="pc-error" role="alert">{error}</p>}
 <div className="pc-cards">{[["Costo preventivo",aggregate("plannedTotal")],["Costo consuntivo",aggregate("directActualTotal")],["Ricavo da OCT / stima",aggregate("plannedRevenue")],["Fatturato attribuito",aggregate("actualRevenue")]].map(([label,value])=><article className="pc-card" key={label}><span>{label}</span><strong>{money(value)}</strong><small>{value===null?"Totale incompleto: aprire le singole produzioni.":filtered.length+" produzioni nel filtro"}</small></article>)}</div>
 {!!knownActual.length&&<p className="pc-note">Costi diretti disponibili nel filtro: <strong>{money(sumKnown(knownActual.map(r=>r.actualKnownSubtotal)))}</strong> su {knownActual.length} produzioni. Subtotale parziale, non costo definitivo; {filtered.filter(r=>r.reconstructed).length} produzioni includono valori ricostruiti. I trasferimenti del bulk non vengono sommati due volte.</p>}
 <p className="pc-note">I totali completi sono disponibili solo quando tutte le voci necessarie sono note. KG e pezzi non vengono sommati. Il guadagno stimato per turno non è incluso nei ricavi. Le produzioni condivise richiedono l'attribuzione del costo bulk.</p>
 <section className="pc-panel"><div className="pc-toolbar"><h2>Produzioni · {filtered.length}</h2><span className="pc-muted">Storico importato: {records.length}</span></div><div className="pc-table-wrap"><table><thead><tr><th>Ordine / cliente</th><th>Prodotto / lotto</th><th>Avvio / stato</th><th>Lavorazioni</th><th>Preventivo</th><th>Consuntivo</th><th>Scostamento</th><th>€/pezzo buono</th><th>Dettaglio</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.orderNumber}</strong><small>{r.customerName}</small><small>{r.links?.map(x=>x.oct).join(", ")}</small></td><td>{r.articleName}<small>{r.articleCode} · {r.lot||r.bulkLot||"—"}</small></td><td>{date(r.works?.[0]?.start||r.date)}<small>{r.state}</small><span className="pc-badge">{r.provisional?"Provvisorio / incompleto":"Completo"}</span></td><td>{r.phases.map(p=><small key={p.id}>{p.machine?.code||p.machineId} · {p.phase} · {p.state}</small>)}</td><td>{money(r.plannedTotal)}</td><td>{money(r.actualTotal)}</td><td>{money(r.totalVariance)}</td><td>{money(r.unitCost)}</td><td><button onClick={()=>setSelected(r)}><Search size={14}/>Apri</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p>{records.length?"Nessun risultato per i filtri impostati.":"Importa lo storico MES per consultare anche le produzioni pregresse. Non vengono generati nuovi ordini o lotti."}</p>}</section>
 {selected&&<Detail record={selected} token={token} canWrite={canWrite} onClose={()=>setSelected(null)} onChanged={load}/>}
 </main>;
}
