import {conclusionDate,splitSaliDiIschia} from "./summary-totals";
import {InvoiceCells,InvoiceHeaders,InvoiceBalance,invoiceDifference} from "./InvoiceSummary";
import CostSummaryCards from "./CostSummaryCards";
import { useEffect, useMemo, useRef, useState } from "react";
import { PackagingPlan } from "./PackagingPlan";
import { RefreshCw, Search } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { Field, Numeric, Modal } from "./common";
import { action, money, quantity, date,unitMoney,signedMoney,signedPercent } from "./client";
import { costVariance, costVariancePercent } from "./cost-engine";
import { matchesProductionSearch } from "./search";
import { matchesWorkflow, workflowLabel } from "./workflow-status";
import CostInfo, { RecordNotes } from "./CostInfo";
import { costRows,displayRecord } from "./cost-display";
import { sumAvailable } from "./available-costs";
import StationOvertime from "./StationOvertime";

function Amount({value,partial,signed=false}){
 return <><span className={signed&&value!=null?(value>0?"pc-balance-positive":value<0?"pc-balance-negative":""):undefined}>{(signed?signedMoney:money)(value)}</span>{partial&&value!=null&&<small className="pc-partial">Parziale</small>}</>;
}
function OctNotes({record:r}){
 return <><p>Valore netto OC attribuito a questa produzione, non il totale dell’intero documento. IVA esclusa; OC e fatture non si sommano.</p>
 {r.commercial?.octSource&&<p>Fonte: {r.commercial.octSource}.</p>}
 {r.commercial?.octReasons?.map((reason,i)=><p key={i}>{reason}</p>)}
 {r.octRevenue==null&&!r.commercial?.octReasons?.length&&<p>Nessuna riga OC valorizzata e attribuibile nei dati acquisiti. Verificare in Economia il riferimento ordine MES, articolo, unità e quantità.</p>}
 {r.octRevenue==null&&r.plannedRevenue!=null&&<p>Prezzo stimato configurato: {money(r.plannedRevenue)}. Non viene presentato come ricavo OC.</p>}
 {r.recoveredOctLines?.map(l=><p key={l.targetKey}>OC originale: {l.reference} · anno {l.year} · riga {l.position} · {l.articleCode} · {quantity(l.quantity)} {l.unit} · netto riga {money(l.lineValue)} · verificato il {date(l.recoveredAt)}.</p>)}
 {r.sourceOrder&&<p>Riga storica MES: {r.sourceOrder.reference} · articolo {r.sourceOrder.articleCode} · {quantity(r.sourceOrder.quantity)} {r.sourceOrder.unit} · valore {money(r.sourceOrder.lineValue)}.</p>}</>;
}
function OctComparisonNotes(){
 return <p>Valore netto OC attribuito alla produzione meno il consuntivo mostrato, già comprensivo di tutti i costi e dell’obiettivo STATION. L’obiettivo non viene sottratto una seconda volta. Positivo = ricavo superiore ai costi. Non è il margine sulla sola quantità fatturata. Se mancano costi o quote OC, il confronto è parziale; per produzioni aperte è provvisorio.</p>;
}
function CostTable({record}){
 const r=displayRecord(record.completeCosts||record),rows=[...costRows(r),{name:"Totale complessivo",p:r.plannedWithObjective,a:r.actualWithObjective,pp:r.costPartial.plannedWithObjective,ap:r.costPartial.actualWithObjective,total:true,comparison:true,info:"Lo stesso margine obiettivo STATION previsto viene sommato a entrambi i totali."}];
 return <div className="pc-table-wrap"><table className="pc-economics-table"><thead><tr>
 <th>Voce</th><th>Preventivo</th><th>Consuntivo</th>
 <th>Scostamento €<CostInfo title="Scostamenti"><p>Preventivo meno consuntivo: risparmio positivo, maggior costo negativo. Percentuale rispetto al preventivo. Un confronto tra somme parziali resta parziale; margini su quantità fatturate diverse restano separati.</p></CostInfo></th>
 <th>Scost. %</th><th>Valore OC<CostInfo title="Valore OC"><OctNotes record={r}/></CostInfo></th>
 <th>Fatture attribuite<CostInfo title="Fatture attribuite"><p>Valore netto delle sole righe fattura riconciliate con la produzione. Non è sommato all’OC e può riferirsi a una quantità inferiore.</p></CostInfo></th>
 <th>OC − consuntivo<CostInfo title="OC meno consuntivo"><OctComparisonNotes/></CostInfo></th>
 <th>Fatturato − OC</th><th>Fatturato − consuntivo</th></tr></thead><tbody>{rows.map(({name,p,a,pp,ap,separate,info,total,comparison})=><tr key={name} className={total?"pc-total-row":undefined}>
 <td>{name}<CostInfo title={name}><p>{info}</p></CostInfo></td>
 <td><Amount value={p} partial={pp}/></td><td><Amount value={a} partial={ap}/></td>
 <td>{separate?"Basi quantitative distinte":<Amount value={costVariance(a,p)} partial={pp||ap} signed/>}</td>
 <td>{separate?"—":signedPercent(costVariancePercent(a,p))}</td>
 <td>{comparison?<Amount value={r.octRevenue} partial={r.costPartial.octRevenue}/>:"—"}</td>
 <td>{comparison?<>{money(r.actualRevenue)}{r.commercial?.invoices?.map(x=><small key={x.id}>{x.document?.sigla} {x.document?.serie}/{x.document?.numero}</small>)}</>:"—"}</td>
 <td>{comparison?<><small className="pc-comparison-label">OC − preventivo</small><Amount value={r.octPlannedMargin} partial={r.costPartial.plannedWithObjective} signed/><small className="pc-comparison-label">OC − consuntivo</small><Amount value={r.octActualMargin} partial={r.costPartial.octActualMargin} signed/></>:"—"}</td>
 <td>{comparison&&<InvoiceBalance value={invoiceDifference(r.commercial?.invoiceRevenue,r.octRevenue)}/>}</td><td>{comparison&&<InvoiceBalance value={invoiceDifference(r.commercial?.invoiceRevenue,r.actualWithObjective)}/>}</td></tr>)}</tbody></table></div>;
}
function Detail({record,token,canWrite,onClose,onChanged}){
 const r=displayRecord(record);
 const [tab,setTab]=useState("Riepilogo"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reason,setReason]=useState("");
 const [washes,setWashes]=useState(()=>r.phases.filter(w=>w.id>0).map(w=>({productionId:w.id,count:w.actualWashes??"",minutes:w.actualWashMinutes??""})));
 const [invoices,setInvoices]=useState(null),[lineId,setLineId]=useState(""),[allocated,setAllocated]=useState("");
 const act=async(fn)=>{setBusy(true);setError("");try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const tabs=["Riepilogo","Tempi e personale","Materiali e SL","Economia","Tracciabilità"];
 return <Modal title={r.orderNumber+" · "+r.articleName} onClose={onClose}>
 <p className="pc-muted">{r.customerName} · {r.articleCode} · Lotto {r.lot||r.bulkLot||"non assegnato"} · Formula {r.formulaVersion||"—"} / rev. {r.formulaRevision??"—"}</p>
 <div className="pc-tabs" role="tablist">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <div className="pc-detail-info">Informazioni sul dettaglio costi<CostInfo title={tab+" · criteri e fonti"}><RecordNotes record={r}/></CostInfo></div>
 {error&&<p className="pc-error" role="alert">{error}</p>}
 {r.fillingContext&&tab==="Tempi e personale"&&<section className="pc-panel"><h3>Manodopera a pezzi · lavorazione selezionata<CostInfo title="Manodopera a pezzi"><p>Costo unitario FILLING: {unitMoney(r.fillingUnitLabor)}. I pezzi FILLING e astucciatura non vengono sommati.</p><p>La quantità preventiva viene ripartita una sola volta tra le lavorazioni FILLING, proporzionalmente ai pezzi rilevati o in parti uguali quando non disponibili.</p></CostInfo></h3><div className="pc-table-wrap"><table><thead><tr><th>Fase / lavorazione</th><th>Pezzi previsti attribuiti</th><th>Pezzi buoni chiusi</th><th>Manodopera preventiva</th><th>Manodopera consuntiva</th></tr></thead><tbody>{r.phases.filter(p=>["Confezionamento","Astucciatura"].includes(p.phase)).map(p=><tr key={p.id}><td>{p.phase} · {p.id}</td><td>{p.phase==="Confezionamento"?quantity(p.plannedLaborPieces):"Separati"}</td><td>{p.state==="Terminato"?quantity(p.goodQuantity):"Non conclusa"}</td><td>{p.laborIncludedInFilling?"Compresa nel reparto":money(p.plannedLabor)}</td><td>{p.laborIncludedInFilling?"Compresa nel reparto":money(p.actualLabor)}</td></tr>)}</tbody></table></div></section>}
 {tab==="Riepilogo"&&<><div className="pc-metrics pc-quantity-metrics"><div>Quantità prevista<CostInfo title="Quantità prevista"><p>Quantità dell’ordine di produzione nell’unità indicata. KG e pezzi non vengono sommati.</p></CostInfo><strong>{quantity(r.quantity)} {r.unit}</strong></div><div>Quantità buona finale<CostInfo title="Quantità buona finale"><p>Quantità buona della fase finale: l’astucciatura, se presente, non si somma al riempimento.</p></CostInfo><strong>{quantity(r.goodQuantity)} {r.unit}</strong></div></div><CostTable record={r}/><p>Guadagno consuntivo per turno STATION (base OC): <Amount value={r.realGainPerShift} partial={r.costPartial.realGainPerShift} signed/><CostInfo title="Guadagno per turno"><p>(Valore OC attribuito − costi consuntivi disponibili) ÷ turni effettivi STATION. Solo lavorazioni chiuse con una STATION identificabile. Non è il margine obiettivo né un incasso. Se i costi sono parziali, anche il guadagno è provvisorio.</p></CostInfo></p></>}
 {tab==="Tempi e personale"&&<><h3>Tempi e personale<CostInfo title="Tempi e personale"><p>I tempi effettivi sono intervalli registrati in MES. Le presenze restano distinte dalla base economica STATION. Il tempo notturno senza turni non viene contato come lavoro ordinario.</p>{r.laborCriteria?.map(c=><p key={c}>{c}</p>)}</CostInfo></h3>
 {r.phases.map(w=><section className="pc-panel" key={w.id}><h3>{w.machine?.code||"Impianto "+w.machineId} · {w.phase} · {w.state}</h3><div className="pc-table-wrap"><table><thead><tr><th>Indicatore</th><th>Preventivo</th><th>Consuntivo</th></tr></thead><tbody>
 {[["Ore macchina",w.plannedHours,w.actualHours],["Turni ordinari (criterio configurato)",w.plannedTurns,w.actualTurns],["Straordinario (ore)",w.plannedOvertimeHours,w.actualOvertimeHours],["Ore/uomo per valorizzazione",w.plannedCostPersonHours,w.actualCostPersonHours],["Organico Miscelazione (STATION)",w.phase==="Semilavorato"?w.mixingOperatorsCount:null,w.phase==="Semilavorato"?w.mixingOperatorsCount:null],["Ore/uomo registrate",w.plannedPersonHours,w.actualPersonHours],["Ore/uomo entro turni (indicatore)",null,w.personHoursInShifts],["Fermi (ore)",null,w.downtimeHours],["Lavaggi",w.plannedWashes,w.actualWashes],["Lavaggi (min)",w.plannedWashMinutes,w.actualWashMinutes],["Produttività / ora",null,w.productivity],["Produttività / ora/uomo",null,w.personProductivity],["Scarti",null,w.scrapQuantity]].map(([k,p,a])=><tr key={k}><td>{k}</td><td>{quantity(p)}</td><td>{quantity(a)}</td></tr>)}</tbody></table></div>
 <h4>Operatori coinvolti<CostInfo title="Operatori coinvolti"><p>Presenze registrate in MES, con reparto, ruolo e orari. Non coincidono necessariamente con l’organico usato dal criterio economico.</p></CostInfo></h4>{!w.personnel?.length&&<p>Presenze non disponibili.</p>}<div className="pc-table-wrap"><table><thead><tr><th>Operatore / reparto</th><th>Ruolo</th><th>Inizio</th><th>Fine</th></tr></thead><tbody>{w.personnel?.map(p=><tr key={p.id}><td>{p.name}<small>{p.department}</small></td><td>{p.role}</td><td>{p.start?.replace("T"," ")}</td><td>{p.end?.replace("T"," ")||"Presenza aperta"}</td></tr>)}</tbody></table></div></section>)}
 {canWrite&&<section className="pc-panel"><h3>Conferma lavaggi effettivamente eseguiti<CostInfo title="Registrazione lavaggi"><p>Registrazione con fonte obbligatoria; non cambia la lavorazione MES. Inserire zero solo se non ci sono stati lavaggi.</p></CostInfo></h3>{washes.map((w,i)=><div className="pc-fields" key={w.productionId}><strong>Lavorazione {w.productionId}</strong><Field label="Numero lavaggi"><Numeric step="1" value={w.count} onChange={v=>setWashes(a=>a.map((x,n)=>n===i?{...x,count:v}:x))}/></Field><Field label="Minuti effettivi complessivi"><Numeric value={w.minutes} onChange={v=>setWashes(a=>a.map((x,n)=>n===i?{...x,minutes:v}:x))}/></Field></div>)}<Field label="Fonte / nota del consuntivo"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Es. registro lavaggi verificato dal responsabile"/></Field><button disabled={busy} onClick={()=>act(async()=>{await action(token,"adjust",{id:r.id,washes,reason});await onChanged();onClose();})}>Registra consuntivo lavaggi</button></section>}</>}
 {tab==="Tempi e personale"&&canWrite&&<StationOvertime record={r} token={token} onSaved={async()=>{await onChanged();onClose();}}/>}
 {tab==="Materiali e SL"&&<><h3>Materiali e SL<CostInfo title="Origine dei materiali"><p>Gli snapshot originali hanno precedenza. Quantità formula dalla revisione collegata; consumi dallo SL oppure dai prelievi scaricati. I costi ultimi sono una ricostruzione, non prezzi storici SL.</p>{r.historicalBaseline&&<p>{r.historicalBaseline.source} Revisione {r.historicalBaseline.formulaVersion} / {r.historicalBaseline.formulaRevision}; recuperata il {date(r.historicalBaseline.recoveredAt)}.</p>}</CostInfo></h3>
 <PackagingPlan record={r}/>
 {r.productSlReference&&<button disabled={busy} onClick={()=>act(async()=>{await action(token,"sync-product-sl",{id:r.id});await onChanged();onClose();})}>Recupera SL storico di confezionamento</button>}
 {!!r.recoveredProducts?.length&&<section className="pc-panel"><h3>Bulk / packaging recuperati<CostInfo title="Bulk e packaging recuperati"><p>Quantità fabbisogno degli impegni V4 registrate al consumo, non quantità estratte dalla riga SL. Prezzi ultimi disponibili: stima economica.</p></CostInfo></h3><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Tipo</th><th>Quantità</th><th>Costo ultimo</th><th>Consumato il</th></tr></thead><tbody>{r.recoveredProducts.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description}</small></td><td>{m.kind}</td><td>{quantity(m.quantity)} {m.unit}</td><td>{money(m.unitCost)}</td><td>{date(m.consumedAt)}</td></tr>)}</tbody></table></div></section>}
 {!!r.recoveredConsumption?.length&&<section className="pc-panel"><h3>Consumi MES recuperati<CostInfo title="Consumi MES recuperati"><p>Prelievi scaricati in MES, valorizzati con i costi ultimi disponibili. I componenti senza prezzo restano visibili e non partecipano alla somma valorizzata.</p></CostInfo></h3><div className="pc-table-wrap"><table><thead><tr><th>Materia prima / lotto</th><th>Quantità scaricata</th><th>Data scarico</th><th>Costo ultimo usato</th><th>Valore ricostruito</th></tr></thead><tbody>{r.recoveredConsumption.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description} · {m.lot}</small></td><td>{quantity(m.quantity)} {m.unit}</td><td>{date(m.withdrawnAt)}</td><td>{money(m.unitCost)}</td><td>{money(m.unitCost==null?null:m.unitCost*m.quantity)}</td></tr>)}</tbody></table></div></section>}
 <h3>Scostamenti materie prime<CostInfo title="Scostamenti materie prime"><p>Quantità formula prevista confrontata con SL o prelievi storici. Delta consumo = (quantità preventiva − consuntiva) × prezzo preventivo; delta prezzo = quantità consuntiva × (prezzo preventivo − consuntivo). Positivo significa risparmio. Senza le basi necessarie il delta resta non disponibile.</p></CostInfo></h3><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Q.tà formula</th><th>Q.tà SL</th><th>Prezzo preventivo</th><th>Prezzo SL</th><th>Delta consumo €</th><th>Delta prezzo €</th></tr></thead><tbody>{r.materialVariances.map(m=><tr key={m.code}><td>{m.code}</td><td>{m.plannedQuantity==null?"Non disponibile":quantity(m.plannedQuantity)}</td><td>{m.actualQuantity==null?"Non disponibile":quantity(m.actualQuantity)}</td><td>{money(m.plannedUnitCost)}</td><td>{money(m.actualUnitCost)}</td><td>{signedMoney(m.usageVariance)}</td><td>{signedMoney(m.priceVariance)}</td></tr>)}</tbody></table></div>
 {[[r.bulkSl,"SL materie prime",r.bulkSlReference],[r.productSl,"SL bulk e confezionamento",r.productSlReference]].map(([docs,title,reference])=><section key={title}><h3>{title}<CostInfo title={title}><p>Documenti originali conservati e SL storici recuperati da Mexal. La fonte è indicata per ogni documento.</p>{!docs?.length&&<p>Snapshot SL non disponibile. Riferimenti storici: {reference||"—"}</p>}</CostInfo></h3>{!docs?.length&&<p>Nessuna copia dettagliata conservata.</p>}{docs?.map((d,i)=><section className="pc-panel" key={i}><strong>{d.document} · {date(d.date)} · Magazzino {d.warehouse}</strong><CostInfo title={"Valorizzazione "+d.document}><p>{d.valuationSource||"Fonte riportata nel documento SL conservato."}</p></CostInfo><div className="pc-table-wrap"><table><thead><tr><th>Articolo</th><th>Lotto Mexal</th><th>Quantità</th><th>Costo unitario</th><th>Importo</th></tr></thead><tbody>{d.materials.map((m,j)=><tr key={j}><td>{m.code}<small>{m.description}</small></td><td>{m.lotId??"—"}</td><td>{quantity(m.quantity)}</td><td>{money(m.unitCost)}</td><td>{money(m.unitCost==null?null:m.unitCost*m.quantity)}</td></tr>)}</tbody></table></div></section>)}</section>)}
 <h3>Prelievi storici disponibili<CostInfo title="Prelievi storici"><p>Materiali, lotti, quantità e date dei prelievi registrati in MES. Non costituiscono la formula preventiva né la copia dello SL originale.</p></CostInfo></h3><div className="pc-table-wrap"><table><thead><tr><th>Materia prima</th><th>Lotto</th><th>Quantità</th><th>Prelievo</th></tr></thead><tbody>{r.historicalMaterials?.map((m,i)=><tr key={i}><td>{m.code}<small>{m.description}</small></td><td>{m.lot}</td><td>{quantity(m.quantity)} {m.unit}</td><td>{date(m.withdrawnAt)}</td></tr>)}</tbody></table></div></>}
 {tab==="Economia"&&<><button disabled={busy} onClick={()=>act(async()=>{await action(token,"sync-oct",{id:r.id});await onChanged();onClose();})}>Recupera valore OC originale</button><CostTable record={r}/>{r.sourceOrder&&<p>Ordine cliente storico MES<CostInfo title="Ordine cliente storico MES"><p> {r.sourceOrder.reference} · {r.sourceOrder.articleCode} · {quantity(r.sourceOrder.quantity)} {r.sourceOrder.unit} · valore riga {money(r.sourceOrder.lineValue>0?r.sourceOrder.lineValue:null)}. Valore attribuito alla produzione solo se articolo, unità e quantità sono compatibili e non duplicati.</p></CostInfo></p>}<h3>Fatture attribuite<CostInfo title="Fatture attribuite"><p>OC e fatture sono confronti separati. Il margine consuntivo usa la somma dei costi disponibili attribuita alla quantità fatturata: {quantity(r.invoicedQuantity)} {r.unit}. Fatture diverse dagli incassi bancari; IVA esclusa e note credito negative.</p></CostInfo></h3>{r.commercial.invoices?.map(x=><p key={x.id}>{x.document?.sigla} {x.document?.serie}/{x.document?.numero} · {date(x.document?.data_documento)} · {quantity(x.quantity)} · {money(x.amount)}</p>)}
 {canWrite&&<section className="pc-panel"><h3>Riconcilia fattura con la produzione<CostInfo title="Riconciliazione fatture"><p>Solo righe dello stesso cliente/articolo; corrispondenza da confermare. La stessa quantità non può essere attribuita due volte.</p></CostInfo></h3><button disabled={busy} onClick={()=>act(async()=>setInvoices((await action(token,"invoice-candidates",{id:r.id})).lines))}>Mostra righe fattura compatibili</button>
 {invoices&&<div className="pc-fields"><Field label="Riga fattura"><select value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Seleziona…</option>{invoices.map(l=><option key={l.id} value={l.id}>{l.document.sigla} {l.document.serie}/{l.document.numero} · {date(l.document.data_documento)} · {l.quantita} · {money(l.valore_netto)}</option>)}</select></Field><Field label="Quantità attribuita (valore assoluto)"><Numeric value={allocated} onChange={setAllocated}/></Field><button disabled={busy||!lineId} onClick={()=>act(async()=>{await action(token,"allocate-invoice",{id:r.id,lineId,quantity:allocated});await onChanged();onClose();})}>Conferma attribuzione</button></div>}</section>}</>}
 {tab==="Tracciabilità"&&<><h3>Fonti conservate<CostInfo title="Tracciabilità delle fonti"><p>Data dell’ultima importazione dei dati di produzione, preventivo conservato e versione costi. Le medie storiche hanno una propria data di acquisizione, consultabile nelle informazioni generali.</p></CostInfo></h3><p>Importazione MES: {r.refreshedAt?.replace("T"," ")}</p><p>Preventivo congelato: {r.baseline?.capturedAt?.replace("T"," ")||"Non disponibile per questo storico"}</p><p>Versione costi: {r.configuration?.id||"Non ancora assegnata"} · decorrenza {date(r.configuration?.effective_from)}</p><p>OC collegati: {r.links?.map(x=>x.oct).join(", ")||"Collegamento non disponibile"}</p><h3>Registro consuntivi / rettifiche<CostInfo title="Registro rettifiche"><p>Integrazioni manuali del consuntivo con fonte e data; non modificano la lavorazione MES.</p></CostInfo></h3>{r.audit.map(a=><p key={a.id}>{date(a.created_at)} — {a.reason}</p>)}{!r.audit.length&&<p>Nessuna integrazione manuale.</p>}</>}
 </Modal>;
}
export default function ProductionCostReports(){
 const {session}=useAuth(),token=session?.access_token;
 const [records,setRecords]=useState([]),[canWrite,setCanWrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState("");
 const [query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[invoiceState,setInvoiceState]=useState(""),[machine,setMachine]=useState(""),[selected,setSelected]=useState(null);
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function load(){const r=await action(token,"list");if(mounted.current){setRecords(r.records);setCanWrite(r.canWrite);}}
 useEffect(()=>{if(!token)return;let alive=true;action(token,"list").then(r=>{if(alive){setRecords(r.records);setCanWrite(r.canWrite);}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false;};},[token]);
 async function sync(){setBusy(true);setError("");try{let page=1,result,unresolved=0,recovered=0;do{
  result=await action(token,"sync",{page});if(!mounted.current)return;
  for(const [index,id] of (result.octRecoveryIds||[]).entries()){
   setProgress(`Recupero OC originali - pagina ${page}, produzione ${index+1}/${result.octRecoveryIds.length}`);
   const oct=await action(token,"sync-oct",{id});if(!mounted.current)return;
   unresolved+=oct.warnings?.length||0;
  }
  for(const [index,id] of (result.recoveryIds||[]).entries()){
   setProgress(`Recupero SL confezionamento - pagina ${page}, produzione ${index+1}/${result.recoveryIds.length}`);
   const sl=await action(token,"sync-product-sl",{id});if(!mounted.current)return;
   recovered+=sl.recovered;unresolved+=sl.warnings?.length||0;
  }
  setProgress(`Importati ${Math.min(page*100,result.total)} / ${result.total} ordini MES`);page++;
 }while(result.hasMore);await load();setProgress(`Importazione completata. ${recovered} SL storici disponibili.${unresolved?" "+unresolved+" segnalazioni nelle informazioni delle produzioni.":""}`);
 }catch(e){setError(e.message);await load().catch(()=>{});}finally{if(mounted.current)setBusy(false);}}
 async function recoverAllOct(){
  setBusy(true);setError("");let warnings=0,recovered=0;
  try{for(const [index,r] of records.entries()){
   if(!mounted.current)return;
   setProgress(`Recupero OC originali: ${index+1} / ${records.length}`);
   const result=await action(token,"sync-oct",{id:r.id});
   recovered+=result.recovered;warnings+=result.warnings?.length||0;
  }
  await load();setProgress(`Recupero OC completato: ${recovered} collegamenti disponibili.${warnings?" "+warnings+" segnalazioni consultabili nel dettaglio Economia.":""}`);
  }catch(e){setError(e.message);await load().catch(()=>{});}finally{if(mounted.current)setBusy(false);}
 }
 const machines=useMemo(()=>[...new Map(records.flatMap(r=>r.phases.map(p=>[p.machineId,p.machine?.code||"Impianto "+p.machineId]))).entries()], [records]);
 const filtered=useMemo(()=>records.filter(r=>{
  const d=String(r.works?.[0]?.start||r.date||"").slice(0,10);
  return (!from||d>=from)&&(!to||d<=to)&&matchesWorkflow(r,"closed")&&(!invoiceState||(invoiceState==="available"?r.commercial?.invoiceRevenue!=null:r.commercial?.invoiceRevenue==null))&&(!machine||r.phases.some(p=>String(p.machineId)===machine))&&matchesProductionSearch(r,query);
 }),[records,from,to,machine,query,invoiceState]);
 const allDisplayed=useMemo(()=>filtered.map(displayRecord).sort((a,b)=>{
  const start=r=>Date.parse(r.works?.[0]?.start||r.date||"")||0;
  return start(b)-start(a);
 }),[filtered]);
 const {ordinary:displayed,sali:saliRows}=splitSaliDiIschia(allDisplayed);
 const summaryRow=r=>({id:r.id,order:r.orderNumber,concludedAt:conclusionDate(r.works),customer:r.customerName,articleCode:r.articleCode,description:r.articleName,references:r.links?.map(l=>l.oct),reasons:r.commercial?.octReasons,oct:r.octRevenue,octPartial:r.costPartial.octRevenue,actual:r.actualWithObjective,planned:r.plannedWithObjective,objective:r.plannedObjective,invoice:r.commercial?.invoiceRevenue,invoiceReferences:r.commercial?.invoices?.map(x=>`${x.document?.sigla} ${x.document?.serie}/${x.document?.numero}`)});
 const closedRows=displayed.filter(r=>r.closed);
 const comparable=key=>closedRows.filter(r=>r.actualWithObjective!=null&&r[key]!=null&&(key!=="octRevenue"||!r.costPartial.octRevenue));
 const excluded=closedRows.filter(r=>!comparable("octRevenue").includes(r));

 return <main className="pc-page" data-column-controls="off">
 <section className="pc-panel"><div className="pc-toolbar"><p>Nessun aggiornamento automatico durante la consultazione.</p><button disabled={busy||!records.length} onClick={recoverAllOct}>Recupera OC originali · tutte le produzioni</button><button className="pc-primary" disabled={busy} onClick={sync}><RefreshCw size={17}/>{busy?"Caricamento…":"Importa / aggiorna storico MES"}</button></div>{progress&&<p role="status">{progress}</p>}
 <div className="pc-filters"><Field label="Ricerca totale"><input aria-label="Ricerca totale" placeholder="Cliente, OC/RdP, prodotto, lotto, operatore, reparto…" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Dal (avvio / data ordine)"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Al"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="Stato fatture"><select value={invoiceState} onChange={e=>setInvoiceState(e.target.value)}><option value="">Tutte</option><option value="available">Disponibili</option><option value="missing">Non disponibili</option></select></Field><Field label="Impianto"><select value={machine} onChange={e=>setMachine(e.target.value)}><option value="">Tutti</option>{machines.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></div></section>
 {error&&<p className="pc-error" role="alert">{error}</p>}
 <CostSummaryCards rows={closedRows.map(summaryRow)} saliRows={saliRows.map(summaryRow)}/>

 <section className="pc-panel"><div className="pc-toolbar"><h2>Produzioni concluse · {displayed.length}</h2><span className="pc-muted">Storico importato: {records.length}</span></div><div className="pc-table-wrap"><table className="pc-production-list"><thead><tr><th>Ordine / cliente</th><th>Prodotto / lotto</th><th>Avvio</th><th>Preventivo</th><th>Consuntivo</th><th>Scostamento<CostInfo title="Scostamento costi"><p>Preventivo meno consuntivo: risparmio positivo, maggior costo negativo.</p></CostInfo></th><th>Valore OC<CostInfo title="Valore OC nell’elenco"><p>Quota netta OC attribuita alla produzione. Aprire il dettaglio e l’icona i per fonte e motivi degli importi mancanti. Non include prezzi stimati.</p></CostInfo></th><th>OC − consuntivo<CostInfo title="Confronto OC e costi"><OctComparisonNotes/></CostInfo></th><InvoiceHeaders/><th>Dettaglio</th></tr></thead><tbody>{displayed.map(r=><tr key={r.id}><td><strong>{r.orderNumber}</strong><small>{r.customerName}</small><small>{r.links?.map(x=>x.oct).join(", ")}</small></td><td>{r.articleName}<small>{r.articleCode} · {r.lot||r.bulkLot||"—"}</small></td><td>{date(r.works?.[0]?.start||r.date)}<CostInfo title="Completezza dei dati economici"><p>{r.provisional?"Dati economici provvisori, ricostruiti o incompleti.":"Dati economici completi."} Questa indicazione non determina lo stato di lavorazione e non viene usata dal filtro.</p></CostInfo></td><td>{money(r.plannedWithObjective)}{r.costPartial.plannedWithObjective&&<small className="pc-partial">Parziale</small>}</td><td>{money(r.actualWithObjective)}{r.costPartial.actualWithObjective&&<small className="pc-partial">Parziale</small>}</td><td>{signedMoney(costVariance(r.actualWithObjective,r.plannedWithObjective))}{(r.costPartial.actualWithObjective||r.costPartial.plannedWithObjective)&&<small className="pc-partial">Parziale</small>}</td><td><Amount value={r.octRevenue} partial={r.costPartial.octRevenue}/></td><td><Amount value={r.octActualMargin} partial={r.costPartial.octActualMargin} signed/></td><InvoiceCells invoice={r.commercial?.invoiceRevenue} oc={r.octRevenue} actual={r.actualWithObjective} references={r.commercial?.invoices?.map(x=>`${x.document?.sigla} ${x.document?.serie}/${x.document?.numero}`)}/><td><button onClick={()=>setSelected(r.completeCosts)}><Search size={14}/>Apri</button></td></tr>)}</tbody></table></div>{!displayed.length&&<p>{records.length?"Nessun risultato per i filtri impostati.":"Importa lo storico MES per consultare anche le produzioni pregresse. Non vengono generati nuovi ordini o lotti."}</p>}</section>
 {selected&&<Detail record={selected} token={token} canWrite={canWrite} onClose={()=>setSelected(null)} onChanged={load}/>}
 </main>;
}
