import { useEffect, useState } from "react";
import { Plus, Save, RefreshCw, Trash2 } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { defaultSettings, validateSettings } from "./cost-engine";
import { Field, Numeric } from "./common";
import { action, money, date } from "./client";

const days=["Dom","Lun","Mar","Mer","Gio","Ven","Sab"];
export default function ProductionCostConfiguration(){
 const {session}=useAuth(),token=session?.access_token;
 const [settings,setSettings]=useState(defaultSettings),[versions,setVersions]=useState([]),[canWrite,setCanWrite]=useState(false);
 const [effective,setEffective]=useState(new Date().toISOString().slice(0,10)),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{if(!token)return;let alive=true;action(token,"configuration").then(r=>{if(alive){setVersions(r.configurations);setCanWrite(r.canWrite);if(r.configurations[0])setSettings(r.configurations[0].settings);}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[token]);
 const update=(key,value)=>setSettings(s=>({...s,[key]:value}));
 const edit=(key,i,values)=>setSettings(s=>({...s,[key]:s[key].map((x,n)=>n===i?{...x,...values}:x)}));
 const remove=(key,i)=>update(key,settings[key].filter((_,n)=>n!==i));
 async function machines(){setBusy(true);setError("");try{const r=await action(token,"machines");setSettings(s=>({...s,machines:r.machines.map(m=>({...m,washCost:"",gainPerShift:"",...s.machines.find(x=>x.id===m.id)}))}));setMessage("Impianti importati. Nessun piano MES è stato modificato.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setError("");setMessage("");setBusy(true);try{validateSettings(settings);await action(token,"save-configuration",{settings,effectiveFrom:effective,note});const r=await action(token,"configuration");setVersions(r.configurations);setMessage("Nuova versione salvata. Le produzioni già associate conservano la loro configurazione.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="pc-page" data-column-controls="off">
 {error&&<p className="pc-error" role="alert">{error}</p>}{message&&<p className="pc-success" role="status">{message}</p>}
 <form onSubmit={save}><fieldset disabled={!canWrite||busy}>
 <section className="pc-panel"><h2>Costo del personale</h2><p>Un unico costo ora/uomo per tutti gli operatori. I tempi effettivi restano quelli rilevati in MES.</p><div className="pc-fields"><Field label="Costo ora/uomo (€)"><Numeric required value={settings.laborHourly} onChange={v=>update("laborHourly",v)}/></Field><Field label="Decorrenza della nuova versione"><input required type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></Field><Field label="Nota della versione"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Es. tariffe approvate settembre"/></Field></div></section>
 <section className="pc-panel"><h2>Turni e calendario di rendicontazione</h2><p>Il primo turno è il riferimento per il guadagno STATION. Pause ripartite proporzionalmente negli intervalli. Queste impostazioni non rigenerano né spostano il piano APS.</p>
 {settings.shifts.map((s,i)=><div className="pc-shift" key={i}><Field label="Nome turno"><input value={s.name} onChange={e=>edit("shifts",i,{name:e.target.value})}/></Field><Field label="Inizio"><input type="time" value={s.start} onChange={e=>edit("shifts",i,{start:e.target.value})}/></Field><Field label="Fine"><input type="time" value={s.end} onChange={e=>edit("shifts",i,{end:e.target.value})}/></Field><Field label="Pausa (min)"><Numeric value={s.breakMinutes} onChange={v=>edit("shifts",i,{breakMinutes:v})}/></Field><div className="pc-days">{days.map((d,n)=><label key={d}><input type="checkbox" checked={s.days.includes(n)} onChange={e=>edit("shifts",i,{days:e.target.checked?[...s.days,n]:s.days.filter(x=>x!==n)})}/>{d}</label>)}</div><button type="button" onClick={()=>remove("shifts",i)} aria-label="Elimina turno"><Trash2 size={16}/></button></div>)}
 <button type="button" onClick={()=>update("shifts",[...settings.shifts,{name:"Nuovo turno",start:"16:00",end:"23:00",breakMinutes:0,days:[1,2,3,4,5]}])}><Plus size={17}/>Aggiungi turno</button>
 <Field label="Chiusure / festività (una data AAAA-MM-GG per riga)"><textarea value={settings.holidays.join("\n")} onChange={e=>update("holidays",e.target.value.split(/\s+/).filter(Boolean))}/></Field></section>
 <section className="pc-panel"><div className="pc-toolbar"><h2>STATION e filling</h2><button type="button" onClick={machines}><RefreshCw size={17}/>Carica impianti da MES</button></div><p>Il costo lavaggio è un costo diretto <strong>esclusa la manodopera</strong>, già valorizzata nelle presenze. Non è previsto un costo orario della macchina.</p>
 <div className="pc-table-wrap"><table data-no-column-controls="true"><thead><tr><th>Impianto</th><th>Reparto</th><th>Lavaggio standard (min)</th><th>Costo lavaggio (€)</th><th>GUADAGNO STIMATO PER TURNO (€)</th></tr></thead><tbody>{settings.machines.map((m,i)=><tr key={m.id}><td><strong>{m.code}</strong><small>{m.name}</small></td><td>{m.department}</td><td><Numeric value={m.washMinutes} onChange={v=>edit("machines",i,{washMinutes:v})}/></td><td><Numeric value={m.washCost} onChange={v=>edit("machines",i,{washCost:v})}/></td><td>{["TurboEmulsore","Miscelatore"].includes(m.type)?<Numeric value={m.gainPerShift} onChange={v=>edit("machines",i,{gainPerShift:v})}/>:"Non applicabile (filling/altro)"}</td></tr>)}</tbody></table></div>
 {!settings.machines.length&&<p>Caricare gli impianti per configurare lavaggi e obiettivi.</p>}</section>
 <section className="pc-panel"><h2>Prezzi stimati di vendita</h2><p>Usati solo in assenza del prezzo netto OCT. Non modificano l'ordine commerciale né le fatture.</p>
 {settings.prices.map((p,i)=><div className="pc-fields" key={i}>{[["articleCode","Codice articolo"],["customerCode","Codice cliente (facoltativo)"],["orderNumber","OdP (facoltativo)"],["unit","Unità (KG / PZ)"]].map(([key,label])=><Field key={key} label={label}><input value={p[key]||""} onChange={e=>edit("prices",i,{[key]:e.target.value})}/></Field>)}<Field label="Prezzo netto unitario (€)"><Numeric value={p.price} onChange={v=>edit("prices",i,{price:v})}/></Field><button type="button" aria-label="Elimina prezzo" onClick={()=>remove("prices",i)}><Trash2 size={16}/></button></div>)}
 <button type="button" onClick={()=>update("prices",[...settings.prices,{articleCode:"",customerCode:"",orderNumber:"",unit:"PZ",price:""}])}><Plus size={17}/>Aggiungi prezzo stimato</button></section>
 <div className="pc-save"><button className="pc-primary" type="submit"><Save size={18}/>{busy?"Salvataggio…":"Salva nuova versione"}</button></div></fieldset></form>
 {!canWrite&&<p className="pc-note">Accesso in sola lettura.</p>}
 <section className="pc-panel"><h2>Versioni conservate</h2>{versions.map(v=><article className="pc-version" key={v.id}><div><strong>Dal {date(v.effective_from)}</strong><span>{money(v.settings.laborHourly)} / ora/uomo · creata il {date(v.created_at)}</span><small>{v.note}</small></div><button onClick={()=>{setSettings(v.settings);setMessage("Versione caricata nel modulo. Il salvataggio crea una nuova versione, senza alterare lo storico.");}}>Consulta / usa come base</button></article>)}{!versions.length&&<p>Nessuna tariffa inserita: i dati storici saranno consultabili senza costi inventati.</p>}</section>
 </main>;
}
