import { useEffect, useState } from "react";
import { Plus, Save, RefreshCw, Trash2 } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { defaultSettings, validateSettings } from "./cost-engine";
import { Field, Numeric } from "./common";
import { action, money, date } from "./client";
import CostAIAssistant from "./CostAIAssistant";
import LaborCriteriaFields from "./LaborCriteriaFields";
import { sameSettings } from "./labor-rules";

const days=["Dom","Lun","Mar","Mer","Gio","Ven","Sab"];
export default function ProductionCostConfiguration(){
 const {session,hasModuleAccess}=useAuth(),token=session?.access_token;
 const [appliedProposal,setAppliedProposal]=useState(null);
 const [settings,setSettings]=useState(defaultSettings),[versions,setVersions]=useState([]),[canWrite,setCanWrite]=useState(false);
 const [applyToHistory,setApplyToHistory]=useState(false);
 const [effective,setEffective]=useState(new Date().toISOString().slice(0,10)),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{if(!token)return;let alive=true;action(token,"configuration").then(r=>{if(alive){setVersions(r.configurations);setCanWrite(r.canWrite);if(r.configurations[0])setSettings({...defaultSettings(),...r.configurations[0].settings});}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[token]);
 const update=(key,value)=>setSettings(s=>({...s,[key]:value}));
 const edit=(key,i,values)=>setSettings(s=>({...s,[key]:s[key].map((x,n)=>n===i?{...x,...values}:x)}));
 const remove=(key,i)=>update(key,settings[key].filter((_,n)=>n!==i));
 async function machines(){setBusy(true);setError("");try{const r=await action(token,"machines");setSettings(s=>({...s,mixingOperatorsCount:r.machines[0]?.mixingOperatorsCount??null,machines:r.machines.map(m=>({...m,washCost:"",gainPerShift:"",...s.machines.find(x=>x.id===m.id)}))}));setMessage("Impianti e numero operatori Miscelazione importati. Nessun piano MES è stato modificato.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setError("");setMessage("");setBusy(true);try{validateSettings(settings);const approved=appliedProposal&&sameSettings(settings,appliedProposal.candidate);await action(token,"save-configuration",{settings,effectiveFrom:effective,note,applyToHistory,...(approved?{proposalId:appliedProposal.id,confirmProposal:true}:{})});const r=await action(token,"configuration");setVersions(r.configurations);setAppliedProposal(null);setMessage(applyToHistory?"Nuova versione applicata allo storico ricostruito dalla decorrenza scelta. Operazione tracciata; preventivi originali invariati.":"Nuova versione salvata. Le produzioni prive di versione vengono associate; quelle già associate conservano la configurazione.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="pc-page" data-column-controls="off">
 {error&&<p className="pc-error" role="alert">{error}</p>}{message&&<p className="pc-success" role="status">{message}</p>}
 <CostAIAssistant token={token} settings={settings} disabled={!canWrite||!hasModuleAccess?.("assistente_ai")||busy} onApply={p=>{setSettings(p.candidate);setAppliedProposal(p);setMessage("Proposta IA confermata e trasferita nel modulo. Verifica la decorrenza e salva la nuova versione per attivarla.");}}/>
 {appliedProposal&&<p className="pc-note">{sameSettings(settings,appliedProposal.candidate)?"Proposta IA confermata, non ancora salvata.":"Hai modificato manualmente i valori della proposta: il prossimo salvataggio sarà una versione manuale."}</p>}
 <form onSubmit={save}><fieldset disabled={!canWrite||busy}>
 <section className="pc-panel"><h2>Costo del personale</h2><p>Un unico costo ora/uomo per tutti gli operatori. I tempi effettivi restano quelli rilevati in MES.</p><div className="pc-fields"><Field label="Costo ora/uomo (€)"><Numeric required value={settings.laborHourly} onChange={v=>update("laborHourly",v)}/></Field><Field label="Decorrenza della nuova versione"><input required type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></Field><Field label="Nota della versione"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Es. tariffe approvate settembre"/></Field></div></section>
 <LaborCriteriaFields settings={settings} onChange={v=>update("laborRules",v)}/>
 <section className="pc-panel"><h2>Turni e calendario di rendicontazione</h2><p>Inserisci soltanto i turni previsti. Arrotondamenti e straordinari seguono i criteri selezionati sopra. Queste impostazioni non rigenerano né spostano il piano APS.</p>
 <div className="pc-fields"><Field label="Ore economiche per turno (base costo, normalmente 8)"><Numeric required min="0.01" max="24" value={settings.referenceShiftHours??8} onChange={v=>update("referenceShiftHours",v)}/></Field><Field label="Operatori Miscelazione attivi (da MES)"><input readOnly value={settings.mixingOperatorsCount??"Da importare da MES"} /></Field></div>
 <p>Con la regola iniziale (mezzo turno superiore), orario 09:00–16:00: fine alle 17:00 = 1 turno + 1 ora straordinaria; fine alle 11:00 del giorno successivo = 1,5 turni. I criteri FILLING sono indipendenti.</p>
 {settings.shifts.map((s,i)=><div className="pc-shift" key={i}><Field label="Nome turno"><input value={s.name} onChange={e=>edit("shifts",i,{name:e.target.value})}/></Field><Field label="Inizio"><input type="time" value={s.start} onChange={e=>edit("shifts",i,{start:e.target.value})}/></Field><Field label="Fine"><input type="time" value={s.end} onChange={e=>edit("shifts",i,{end:e.target.value})}/></Field><Field label="Pausa (min)"><Numeric value={s.breakMinutes} onChange={v=>edit("shifts",i,{breakMinutes:v})}/></Field><div className="pc-days">{days.map((d,n)=><label key={d}><input type="checkbox" checked={s.days.includes(n)} onChange={e=>edit("shifts",i,{days:e.target.checked?[...s.days,n]:s.days.filter(x=>x!==n)})}/>{d}</label>)}</div><button type="button" onClick={()=>remove("shifts",i)} aria-label="Elimina turno"><Trash2 size={16}/></button></div>)}
 <button type="button" onClick={()=>update("shifts",[...settings.shifts,{name:"Nuovo turno",start:"16:00",end:"23:00",breakMinutes:0,days:[1,2,3,4,5]}])}><Plus size={17}/>Aggiungi turno</button>
 <Field label="Chiusure / festività (una data AAAA-MM-GG per riga)"><textarea value={settings.holidays.join("\n")} onChange={e=>update("holidays",e.target.value.split(/\s+/).filter(Boolean))}/></Field></section>
 <section className="pc-panel"><div className="pc-toolbar"><h2>Lavaggi e margine obiettivo per STATION</h2><button type="button" onClick={machines}><RefreshCw size={17}/>Carica impianti e organico da MES</button></div><p>Il costo lavaggio è un costo diretto <strong>esclusa la manodopera</strong>. Il guadagno desiderato è il <strong>margine dopo tutti i costi di produzione conteggiati</strong>, diverso per ogni STATION: non viene aggiunto ai costi o ai ricavi. Non è previsto un costo orario macchina.</p>
 <div className="pc-table-wrap"><table data-no-column-controls="true"><thead><tr><th>Impianto</th><th>Reparto</th><th>Lavaggio standard (min)</th><th>Costo lavaggio (€)</th><th>GUADAGNO STIMATO PER TURNO (€)</th></tr></thead><tbody>{settings.machines.map((m,i)=><tr key={m.id}><td><strong>{m.code}</strong><small>{m.name}</small></td><td>{m.department}</td><td><Numeric value={m.washMinutes} onChange={v=>edit("machines",i,{washMinutes:v})}/></td><td><Numeric value={m.washCost} onChange={v=>edit("machines",i,{washCost:v})}/></td><td>{["TurboEmulsore","Miscelatore"].includes(m.type)?<Numeric value={m.gainPerShift} onChange={v=>edit("machines",i,{gainPerShift:v})}/>:"Non applicabile (filling/altro)"}</td></tr>)}</tbody></table></div>
 {!settings.machines.length&&<p>Caricare gli impianti per configurare lavaggi e obiettivi.</p>}</section>
 <section className="pc-panel"><h2>Prezzi stimati di vendita</h2><p>Usati solo in assenza del prezzo netto OCT. Non modificano l'ordine commerciale né le fatture.</p>
 {settings.prices.map((p,i)=><div className="pc-fields" key={i}>{[["articleCode","Codice articolo"],["customerCode","Codice cliente (facoltativo)"],["orderNumber","OdP (facoltativo)"],["unit","Unità (KG / PZ)"]].map(([key,label])=><Field key={key} label={label}><input value={p[key]||""} onChange={e=>edit("prices",i,{[key]:e.target.value})}/></Field>)}<Field label="Prezzo netto unitario (€)"><Numeric value={p.price} onChange={v=>edit("prices",i,{price:v})}/></Field><button type="button" aria-label="Elimina prezzo" onClick={()=>remove("prices",i)}><Trash2 size={16}/></button></div>)}
 <button type="button" onClick={()=>update("prices",[...settings.prices,{articleCode:"",customerCode:"",orderNumber:"",unit:"PZ",price:""}])}><Plus size={17}/>Aggiungi prezzo stimato</button></section>
 <p className="pc-note"><label><input type="checkbox" checked={applyToHistory} onChange={e=>setApplyToHistory(e.target.checked)}/> Applica questa versione anche alle produzioni storiche prive di preventivo congelato, dalla decorrenza scelta.</label> La scelta resta nel registro; non modifica i dati MES né i preventivi originali.</p>
 <div className="pc-save"><button className="pc-primary" type="submit"><Save size={18}/>{busy?"Salvataggio…":"Salva nuova versione"}</button></div></fieldset></form>
 {!canWrite&&<p className="pc-note">Accesso in sola lettura.</p>}
 <section className="pc-panel"><h2>Versioni conservate</h2>{versions.map(v=><article className="pc-version" key={v.id}><div><strong>Dal {date(v.effective_from)}</strong><span>{money(v.settings.laborHourly)} / ora/uomo · creata il {date(v.created_at)}</span><small>{v.note}</small>{v.settings.aiDefinition&&<small>Definita con IA · proposta {v.settings.aiDefinition.proposalId} · confermata il {date(v.settings.aiDefinition.confirmedAt)}</small>}</div><button onClick={()=>{setSettings({...defaultSettings(),...v.settings});setAppliedProposal(null);setMessage("Versione caricata nel modulo. Il salvataggio crea una nuova versione, senza alterare lo storico.");}}>Consulta / usa come base</button></article>)}{!versions.length&&<p>Nessuna tariffa inserita: i dati storici saranno consultabili senza costi inventati.</p>}</section>
 </main>;
}
