import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Plus, Search, Pencil, Trash2, X, Save, Folder, CalendarDays, UserCircle, CheckCircle2, AlertCircle, History } from "lucide-react";
import { supabase } from "../../lib/supabaseClient";

const emptyForm = { nome:"", descrizione:"", stato:"In corso", responsabile_id:"", data_inizio:"", deadline:"", data_chiusura:"" };
const statiProgetto = ["In valutazione","Pianificato","In corso","In attesa","Completato","Annullato"];

function Projects(){
  const navigate = useNavigate();
  const [progetti,setProgetti]=useState([]); const [utenti,setUtenti]=useState([]); const [tasks,setTasks]=useState([]);
  const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("tutti");
  const [modalOpen,setModalOpen]=useState(false); const [editingProject,setEditingProject]=useState(null); const [form,setForm]=useState(emptyForm); const [saving,setSaving]=useState(false);
  useEffect(()=>{loadData();},[]);
  async function loadData(){ setLoading(true); const [projectsRes,usersRes,tasksRes]=await Promise.all([supabase.from("progetti").select("id,nome,descrizione,stato,responsabile_id,data_inizio,deadline,data_chiusura,created_at,updated_at,responsabile:utenti!progetti_responsabile_id_fkey(nome,email)").order("created_at",{ascending:false}),supabase.from("utenti").select("id,nome,email,attivo").eq("attivo",true).order("nome"),supabase.from("tasks").select("id,progetto_id,deadline,stati_task(nome,chiusa)")]); if(projectsRes.error){console.error(projectsRes.error);setProgetti([])} else setProgetti(projectsRes.data||[]); if(usersRes.error){console.error(usersRes.error);setUtenti([])} else setUtenti(usersRes.data||[]); if(tasksRes.error){console.error(tasksRes.error);setTasks([])} else setTasks(tasksRes.data||[]); setLoading(false); }
  function openCreate(){ setEditingProject(null); setForm(emptyForm); setModalOpen(true); }
  function openEdit(p){ setEditingProject(p); setForm({nome:p.nome||"",descrizione:p.descrizione||"",stato:p.stato||"In corso",responsabile_id:p.responsabile_id||"",data_inizio:p.data_inizio||"",deadline:p.deadline||"",data_chiusura:p.data_chiusura||""}); setModalOpen(true); }
  function closeModal(){ setModalOpen(false); setEditingProject(null); setForm(emptyForm); }
  function update(field,value){ setForm(c=>({...c,[field]:value})); }
  function openHistory(p){ navigate(`/tasks?project=${p.id}`); }
  async function handleSave(e){ e.preventDefault(); if(!form.nome.trim()) return alert("Inserisci il nome del progetto."); setSaving(true); const payload={nome:form.nome.trim(),descrizione:form.descrizione.trim()||null,stato:form.stato||"In corso",responsabile_id:form.responsabile_id||null,data_inizio:form.data_inizio||null,deadline:form.deadline||null,data_chiusura:form.data_chiusura||null}; const req=editingProject?supabase.from("progetti").update(payload).eq("id",editingProject.id):supabase.from("progetti").insert(payload); const {error}=await req; setSaving(false); if(error){console.error(error);return alert("Errore salvataggio progetto.");} await loadData(); closeModal(); }
  async function deleteProject(p){ const count=tasks.filter(t=>t.progetto_id===p.id).length; if(count>0) return alert(`Non puoi eliminare questo progetto perché ha ${count} task collegate.`); if(!confirm(`Eliminare il progetto "${p.nome}"?`)) return; const {error}=await supabase.from("progetti").delete().eq("id",p.id); if(error){console.error(error);return alert("Errore eliminazione progetto.");} await loadData(); }
  function stats(id){ const arr=tasks.filter(t=>t.progetto_id===id); const completed=arr.filter(t=>t.stati_task?.chiusa).length; const open=arr.length-completed; const today=new Date(); today.setHours(0,0,0,0); const overdue=arr.filter(t=>{ if(!t.deadline||t.stati_task?.chiusa) return false; const d=new Date(`${t.deadline}T00:00:00`); d.setHours(0,0,0,0); return d<today; }).length; return {total:arr.length,completed,open,overdue,progress:arr.length?Math.round((completed/arr.length)*100):0}; }
  function formatDate(date){ if(!date) return "-"; return new Date(`${date}T00:00:00`).toLocaleDateString("it-IT",{day:"2-digit",month:"short",year:"numeric"}); }
  function overdueProject(p){ if(!p.deadline||["Completato","Annullato"].includes(p.stato)) return false; const today=new Date(); today.setHours(0,0,0,0); const d=new Date(`${p.deadline}T00:00:00`); d.setHours(0,0,0,0); return d<today; }
  function statusClass(s){ if(s==="Completato")return"completed"; if(s==="Annullato")return"cancelled"; if(s==="In corso")return"active"; if(s==="In attesa")return"waiting"; return"planned"; }
  const filtered=useMemo(()=>{ const q=search.trim().toLowerCase(); return progetti.filter(p=>{ const text=`${p.nome||""} ${p.descrizione||""} ${p.stato||""} ${p.responsabile?.nome||""}`.toLowerCase(); return (!q||text.includes(q)) && (statusFilter==="tutti"||p.stato===statusFilter);});},[progetti,search,statusFilter]);
  const counters={totale:progetti.length,inCorso:progetti.filter(p=>p.stato==="In corso").length,completati:progetti.filter(p=>p.stato==="Completato").length,inRitardo:progetti.filter(overdueProject).length};
  return <div className="projects-page"><div className="page-title-row"><div><h1>Progetti</h1><p>Clicca su un progetto per vedere lo storico task collegato.</p></div><button className="primary-action" onClick={openCreate}><Plus size={18}/>Nuovo progetto</button></div>
    <div className="projects-kpi-grid"><div className="project-kpi"><Folder size={22}/><div><strong>{counters.totale}</strong><span>Progetti totali</span></div></div><div className="project-kpi"><CalendarDays size={22}/><div><strong>{counters.inCorso}</strong><span>In corso</span></div></div><div className="project-kpi"><CheckCircle2 size={22}/><div><strong>{counters.completati}</strong><span>Completati</span></div></div><div className="project-kpi danger"><AlertCircle size={22}/><div><strong>{counters.inRitardo}</strong><span>In ritardo</span></div></div></div>
    <div className="projects-toolbar"><div className="projects-search"><Search size={18}/><input placeholder="Cerca progetto, responsabile o stato..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="projects-status-filter" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="tutti">Tutti gli stati</option>{statiProgetto.map(s=><option key={s} value={s}>{s}</option>)}</select></div>
    {loading?<div className="panel"><p className="table-message">Caricamento progetti...</p></div>:filtered.length===0?<div className="panel"><p className="table-message">Nessun progetto trovato.</p></div>:<div className="projects-grid">{filtered.map(p=>{ const st=stats(p.id); const over=overdueProject(p); return <div className={`project-card clickable-card ${over?"overdue":""}`} key={p.id} onClick={()=>openHistory(p)}><div className="project-card-header"><div><span className={`project-status ${statusClass(p.stato)}`}>{p.stato||"In corso"}</span><h3>{p.nome}</h3></div><div className="project-actions" onClick={e=>e.stopPropagation()}><button title="Storico task" onClick={()=>openHistory(p)}><History size={16}/></button><button title="Modifica" onClick={()=>openEdit(p)}><Pencil size={16}/></button><button title="Elimina" className="danger" onClick={()=>deleteProject(p)}><Trash2 size={16}/></button></div></div><p className="project-description">{p.descrizione||"Nessuna descrizione inserita."}</p><div className="project-meta-grid"><div><UserCircle size={17}/><span>{p.responsabile?.nome||"Responsabile non assegnato"}</span></div><div className={over?"danger":""}><CalendarDays size={17}/><span>Scadenza: {formatDate(p.deadline)}</span></div></div><div className="project-progress-block"><div className="progress-row"><span>Avanzamento</span><strong>{st.progress}%</strong></div><div className="progress-bar"><div style={{width:`${st.progress}%`}}/></div></div><div className="project-task-stats"><div><strong>{st.total}</strong><span>Task</span></div><div><strong>{st.open}</strong><span>Aperte</span></div><div><strong>{st.completed}</strong><span>Chiuse</span></div><div className={st.overdue?"danger":""}><strong>{st.overdue}</strong><span>Scadute</span></div></div><button className="secondary-action linked-history-btn" type="button" onClick={(e)=>{e.stopPropagation();openHistory(p)}}><History size={17}/> Storico task collegate</button></div>})}</div>}
    {modalOpen&&<div className="modal-backdrop"><div className="project-modal"><div className="modal-header"><div><h2>{editingProject?"Modifica progetto":"Nuovo progetto"}</h2><p>Definisci nome, stato, responsabile e scadenze.</p></div><button className="modal-close" onClick={closeModal} type="button"><X size={22}/></button></div><form className="project-form" onSubmit={handleSave}><div className="form-group full"><label>Nome progetto *</label><input value={form.nome} onChange={e=>update("nome",e.target.value)} autoFocus/></div><div className="form-group full"><label>Descrizione</label><textarea value={form.descrizione} onChange={e=>update("descrizione",e.target.value)}/></div><div className="form-group"><label>Stato</label><select value={form.stato} onChange={e=>update("stato",e.target.value)}>{statiProgetto.map(s=><option key={s} value={s}>{s}</option>)}</select></div><div className="form-group"><label>Responsabile</label><select value={form.responsabile_id} onChange={e=>update("responsabile_id",e.target.value)}><option value="">Non assegnato</option>{utenti.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select></div><div className="form-group"><label>Data inizio</label><input type="date" value={form.data_inizio} onChange={e=>update("data_inizio",e.target.value)}/></div><div className="form-group"><label>Deadline</label><input type="date" value={form.deadline} onChange={e=>update("deadline",e.target.value)}/></div><div className="form-group"><label>Data chiusura</label><input type="date" value={form.data_chiusura} onChange={e=>update("data_chiusura",e.target.value)}/></div><div className="modal-actions"><button type="button" className="secondary-action" onClick={closeModal}>Annulla</button><button type="submit" className="primary-action" disabled={saving}><Save size={18}/>{saving?"Salvataggio...":"Salva progetto"}</button></div></form></div></div>}
  </div>;
}
export default Projects;
