-- Schedulazione amministrabile delle sincronizzazioni Mexal.  Le run esistenti
-- non vengono mai riscritte e l'identità bigint di mexal_sync_runs è preservata.
alter table public.mexal_sync_runs drop constraint if exists mexal_sync_runs_sync_type_check;
alter table public.mexal_sync_runs add constraint mexal_sync_runs_sync_type_check
  check (sync_type in ('products','clients','stocks','orders','commercial_conditions','document_series','agents','payments'));

create table if not exists public.mexal_sync_schedules (
  id bigint generated by default as identity primary key,
  sync_type text not null unique check (sync_type in ('products','clients','stocks','orders','commercial_conditions','document_series','agents','payments')),
  enabled boolean not null default false,
  schedule_mode text not null default 'manual' check (schedule_mode in ('manual','interval','daily','weekly')),
  frequency_minutes integer check (frequency_minutes is null or frequency_minutes between 1 and 10080),
  hour smallint check (hour is null or hour between 0 and 23), minute smallint check (minute is null or minute between 0 and 59),
  days_of_week smallint[] not null default '{}'::smallint[] check (days_of_week <@ array[0,1,2,3,4,5,6]::smallint[]),
  batch_size integer not null default 12 check (batch_size between 1 and 500),
  last_run_at timestamptz, next_run_at timestamptz, last_status text, last_error text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists mexal_sync_schedules_due_idx on public.mexal_sync_schedules (enabled, next_run_at);

insert into public.mexal_sync_schedules (sync_type,enabled,schedule_mode,hour,minute,batch_size)
values ('clients',true,'daily',0,0,12),('products',true,'daily',0,5,12),('commercial_conditions',true,'daily',0,10,12),('document_series',true,'daily',0,15,12),('stocks',true,'daily',0,20,12),('orders',true,'daily',0,25,12)
on conflict (sync_type) do nothing;

alter table public.mexal_sync_schedules enable row level security;
drop policy if exists "admins read mexal sync schedules" on public.mexal_sync_schedules;
create policy "admins read mexal sync schedules" on public.mexal_sync_schedules for select to authenticated using (exists (select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))));
drop policy if exists "admins write mexal sync schedules" on public.mexal_sync_schedules;
create policy "admins write mexal sync schedules" on public.mexal_sync_schedules for all to authenticated using (exists (select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione')))) with check (exists (select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))));
