create table if not exists public.workspace_article_supplier_associations (
  id bigint generated by default as identity primary key,
  article_id bigint not null check (article_id > 0),
  article_code text not null check (btrim(article_code) <> ''),
  supplier_id bigint not null check (supplier_id > 0),
  supplier_code text,
  supplier_name text not null check (btrim(supplier_name) <> ''),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workspace_article_supplier_associations_article_supplier_key unique (article_id, supplier_id)
);

create index if not exists workspace_article_supplier_associations_article_idx
  on public.workspace_article_supplier_associations (article_id);

alter table public.workspace_article_supplier_associations enable row level security;
revoke all on table public.workspace_article_supplier_associations from anon, authenticated;
grant all on table public.workspace_article_supplier_associations to service_role;
grant usage, select on sequence public.workspace_article_supplier_associations_id_seq to service_role;

comment on table public.workspace_article_supplier_associations is
  'Associazioni Workspace tra articoli ProgreMES e fornitori ProgreMES usate per generare proposte PF per ogni fornitore associato.';
