-- Harden Mexal run tracking and add database-configured application event automations.
alter table public.mexal_sync_runs drop constraint if exists mexal_sync_runs_sync_type_check;
alter table public.mexal_sync_runs add constraint mexal_sync_runs_sync_type_check check (sync_type in ('clients','agents','products','commercial_conditions','document_series','stocks','orders','payments'));
alter table public.mexal_sync_runs drop constraint if exists mexal_sync_runs_status_check;
alter table public.mexal_sync_runs add constraint mexal_sync_runs_status_check check (status in ('running','completed','completed_with_errors','completed_with_warnings','failed','timeout','skipped'));
alter table public.mexal_sync_runs add column if not exists duration_ms bigint, add column if not exists source text not null default 'manual', add column if not exists context jsonb not null default '{}'::jsonb;
create index if not exists mexal_sync_runs_sync_type_idx on public.mexal_sync_runs(sync_type);
create index if not exists mexal_sync_runs_status_idx on public.mexal_sync_runs(status);
create index if not exists mexal_sync_runs_started_at_idx on public.mexal_sync_runs(started_at desc);
create index if not exists mexal_sync_runs_running_type_idx on public.mexal_sync_runs(sync_type, started_at) where status = 'running';

create table if not exists public.mexal_event_automations (
 id bigint generated by default as identity primary key, event_key text not null, sync_type text not null, enabled boolean not null default true,
 execution_order integer not null default 1, blocking boolean not null default true, run_if_previous_failed boolean not null default false,
 allow_continue_on_error boolean not null default false, scope text not null default 'global', configuration jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid, updated_by uuid,
 constraint mexal_event_automations_event_key_check check (event_key in ('orders_module_open','before_new_order','customer_selected','before_order_save','after_order_save','before_order_send','after_order_send','product_selected','manual')),
 constraint mexal_event_automations_sync_type_check check (sync_type in ('clients','agents','products','commercial_conditions','document_series','stocks','orders','payments')),
 constraint mexal_event_automations_scope_check check (scope in ('global','selected_customer','selected_product','current_order','current_user','current_warehouse')),
 constraint mexal_event_automations_unique unique(event_key, sync_type, scope)
);
create index if not exists mexal_event_automations_enabled_order_idx on public.mexal_event_automations(event_key, execution_order) where enabled;
alter table public.mexal_event_automations enable row level security;
drop policy if exists "mexal event automations read authorized" on public.mexal_event_automations;
create policy "mexal event automations read authorized" on public.mexal_event_automations for select to authenticated using (exists (select 1 from public.utenti u where u.auth_user_id = auth.uid() and u.attivo is not false));
drop policy if exists "mexal event automations admin manage" on public.mexal_event_automations;
create policy "mexal event automations admin manage" on public.mexal_event_automations for all to authenticated using (exists (select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione')))) with check (exists (select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))));
create or replace function public.set_mexal_event_automations_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists mexal_event_automations_updated_at on public.mexal_event_automations;
create trigger mexal_event_automations_updated_at before update on public.mexal_event_automations for each row execute function public.set_mexal_event_automations_updated_at();
insert into public.mexal_event_automations(event_key,sync_type,execution_order,blocking,scope) values ('before_new_order','stocks',1,true,'global'),('before_new_order','document_series',2,true,'global') on conflict (event_key,sync_type,scope) do nothing;
