-- Stores the unmodified GET payload as the official reference for a later POST schema decision.
create table if not exists public.mexal_order_payload_diagnostics (
  id bigint generated by default as identity primary key,
  ordine_id uuid not null references public.ordini_testate(id) on delete cascade,
  tipo_documento text not null check (tipo_documento in ('OCM', 'OCX', 'OCI')),
  sigla text not null, serie text not null, numero text not null,
  get_payload jsonb not null, post_payload jsonb not null, comparison jsonb not null,
  creato_il timestamptz not null default now()
);
create index if not exists idx_mexal_order_payload_diagnostics_order on public.mexal_order_payload_diagnostics(ordine_id, creato_il desc);
alter table public.mexal_order_payload_diagnostics enable row level security;
drop policy if exists "mexal_order_payload_diagnostics_select_authenticated" on public.mexal_order_payload_diagnostics;
create policy "mexal_order_payload_diagnostics_select_authenticated" on public.mexal_order_payload_diagnostics for select to authenticated using (true);
comment on table public.mexal_order_payload_diagnostics is 'Snapshot integrale GET Mexal, payload POST locale e confronto diagnostico; nessun POST Mexal viene eseguito.';
