-- WorkspaceMES V3. Schema additivo, disabilitato per default e senza backfill storico.
-- V1/V2 restano invariati; tutte le mutazioni V3 passano da RPC service-role fail-closed.

create table if not exists public.workspace_finished_bom_revisions (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  finished_article_code text not null,
  revision integer not null check (revision > 0),
  source text not null default 'MEXAL',
  source_hash text not null,
  base_quantity numeric(18,6) not null default 1 check (base_quantity > 0),
  unit_of_measure text not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  is_current boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (finished_article_code, revision),
  check (effective_to is null or effective_to >= effective_from)
);

create unique index if not exists workspace_finished_bom_current_uniq
  on public.workspace_finished_bom_revisions (finished_article_code) where is_current;

create table if not exists public.workspace_finished_bom_lines (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  revision_id bigint not null references public.workspace_finished_bom_revisions(id) on delete restrict,
  line_number integer not null check (line_number > 0),
  article_code text not null,
  description text,
  quantity numeric(18,6) not null check (quantity > 0),
  unit_of_measure text not null,
  component_kind text not null check (component_kind in ('DIRECT_COMPONENT','FORMULA_COMPONENT')),
  classification_source text not null,
  formula_external_ref text,
  metadata jsonb not null default '{}'::jsonb,
  unique (revision_id, line_number)
);

create table if not exists public.workspace_v3_previews (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  production_request_id uuid references public.workspace_production_requests(id) on delete restrict,
  contract_version integer not null default 3 check (contract_version = 3),
  preview_hash text not null unique,
  idempotency_key text not null unique,
  payload_hash text not null,
  status text not null check (status in ('BUILDING','READY','BLOCKED','STALE','CONFIRMING','CONFIRMED','RECOVERY_REQUIRED','CANCELLED')),
  oct_revision integer not null check (oct_revision > 0),
  oct_hash text not null,
  bom_revision_id bigint not null references public.workspace_finished_bom_revisions(id) on delete restrict,
  bom_hash text not null,
  availability_version text not null,
  snapshot jsonb not null,
  correlation_id uuid not null,
  causation_id uuid,
  requested_by uuid,
  row_version bigint not null default 1,
  captured_at timestamptz not null default now(),
  invalidated_at timestamptz,
  confirmed_at timestamptz
);

create table if not exists public.workspace_v3_preview_components (
  id bigint generated by default as identity primary key,
  preview_id bigint not null references public.workspace_v3_previews(id) on delete restrict,
  bom_line_id bigint not null references public.workspace_finished_bom_lines(id) on delete restrict,
  component_kind text not null check (component_kind in ('DIRECT_COMPONENT','FORMULA_COMPONENT','FORMULA_MATERIAL')),
  parent_component_id bigint references public.workspace_v3_preview_components(id) on delete restrict,
  article_code text not null,
  unit_of_measure text not null,
  required_quantity numeric(18,6) not null check (required_quantity >= 0),
  on_hand_quantity numeric(18,6) not null default 0,
  committed_quantity numeric(18,6) not null default 0,
  incoming_quantity numeric(18,6) not null default 0,
  uncovered_quantity numeric(18,6) not null default 0,
  expected_available_at timestamptz,
  calculation_owner text not null check (calculation_owner in ('WORKSPACE','PROGREMES')),
  formula_code text,
  formula_revision integer,
  formula_snapshot_hash text,
  batch text,
  station text,
  filling text,
  blocker_code text,
  certified_payload jsonb not null default '{}'::jsonb,
  unique (preview_id, component_kind, article_code, bom_line_id, parent_component_id)
);

create table if not exists public.workspace_v3_confirmation_sagas (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique,
  preview_id bigint not null references public.workspace_v3_previews(id) on delete restrict,
  idempotency_key text not null unique,
  payload_hash text not null,
  status text not null check (status in ('PENDING_MES','MES_CONFIRMED','MATERIALIZING_WORKSPACE','COMPLETED','RECOVERY_REQUIRED','COMPENSATION_REQUIRED','CANCELLED')),
  mes_confirmation_id uuid,
  mes_production_order_id integer,
  mes_production_order_number text,
  last_error_code text,
  correlation_id uuid not null,
  causation_id uuid,
  row_version bigint not null default 1,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.workspace_v3_material_commitments (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  saga_id bigint not null references public.workspace_v3_confirmation_sagas(id) on delete restrict,
  preview_component_id bigint not null references public.workspace_v3_preview_components(id) on delete restrict,
  owner text not null check (owner in ('WORKSPACE_DIRECT','PROGREMES_MP_CERTIFIED')),
  article_code text not null,
  unit_of_measure text not null,
  quantity numeric(18,6) not null check (quantity > 0),
  source_commitment_id text,
  status text not null check (status in ('ACTIVE','RELEASED','COMPENSATION_REQUIRED')),
  committed_at timestamptz not null default now(),
  released_at timestamptz,
  unique (saga_id, preview_component_id, owner)
);

create table if not exists public.workspace_v3_purchase_requirements (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  saga_id bigint not null references public.workspace_v3_confirmation_sagas(id) on delete restrict,
  commitment_id bigint not null references public.workspace_v3_material_commitments(id) on delete restrict,
  article_code text not null,
  unit_of_measure text not null,
  required_quantity numeric(18,6) not null check (required_quantity > 0),
  required_at timestamptz,
  status text not null check (status in ('OPEN','IN_PROPOSAL','IN_RFQ','QUOTED','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
  lineage jsonb not null,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (saga_id, commitment_id)
);

create table if not exists public.workspace_v3_purchase_documents (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  document_type text not null check (document_type in ('PROPOSAL','RFQ','QUOTE','SUPPLIER_ORDER')),
  parent_document_id bigint references public.workspace_v3_purchase_documents(id) on delete restrict,
  supplier_external_ref text,
  status text not null,
  document_number text,
  currency text,
  valid_until date,
  mexal_external_ref text,
  payload_hash text not null,
  idempotency_key text not null unique,
  correlation_id uuid not null,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_v3_purchase_document_lines (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.workspace_v3_purchase_documents(id) on delete restrict,
  requirement_id bigint not null references public.workspace_v3_purchase_requirements(id) on delete restrict,
  quantity numeric(18,6) not null check (quantity > 0),
  unit_price numeric(18,6),
  expected_at timestamptz,
  received_quantity numeric(18,6) not null default 0 check (received_quantity >= 0),
  unique (document_id, requirement_id)
);

create table if not exists public.workspace_v3_outbox (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique default gen_random_uuid(),
  aggregate_type text not null,
  aggregate_id text not null,
  destination text not null check (destination in ('PROGREMES','MEXAL','WORKSPACE')),
  event_type text not null,
  sequence bigint not null,
  payload jsonb not null,
  payload_hash text not null,
  correlation_id uuid not null,
  causation_id uuid,
  attempt_count integer not null default 0,
  next_attempt_at timestamptz,
  lease_token uuid,
  lease_expires_at timestamptz,
  delivered_at timestamptz,
  dead_lettered_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  unique (aggregate_type, aggregate_id, destination, sequence)
);

create table if not exists public.workspace_v3_audit (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique default gen_random_uuid(),
  aggregate_type text not null,
  aggregate_id text not null,
  action text not null,
  actor_id text not null,
  before_hash text,
  after_hash text,
  payload jsonb not null default '{}'::jsonb,
  correlation_id uuid not null,
  causation_id uuid,
  occurred_at timestamptz not null default now()
);

create table if not exists public.workspace_v3_feature_flags (
  key text primary key,
  enabled boolean not null default false,
  description text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

insert into public.workspace_v3_feature_flags(key, enabled, description) values
  ('workspacemes.v3.preview', false, 'Abilita preview V3 senza effetti produttivi.'),
  ('workspacemes.v3.confirm', false, 'Abilita saga di conferma V3 e materializzazione impegni/fabbisogni.'),
  ('legacy.sync.oct', true, 'Sincronizzazione legacy OCT Mexal verso MES.'),
  ('legacy.sync.articles', true, 'Sincronizzazione legacy articoli Mexal verso MES.'),
  ('legacy.sync.customers', true, 'Sincronizzazione legacy clienti Mexal verso MES.'),
  ('legacy.sync.suppliers', true, 'Sincronizzazione legacy fornitori Mexal verso MES.'),
  ('legacy.sync.stocks', true, 'Sincronizzazione legacy giacenze Mexal verso MES.'),
  ('legacy.sync.supplier_orders', true, 'Sincronizzazione legacy ordini fornitori Mexal verso MES.'),
  ('legacy.sync.finished_bom', true, 'Sincronizzazione legacy distinta prodotto finito Mexal verso MES.'),
  ('legacy.sync.fp_formulas', true, 'Sincronizzazione legacy formule FP Mexal verso MES.')
on conflict (key) do nothing;

create index if not exists workspace_v3_outbox_pending_idx on public.workspace_v3_outbox(next_attempt_at, id)
  where delivered_at is null and dead_lettered_at is null;
create index if not exists workspace_v3_requirements_status_idx on public.workspace_v3_purchase_requirements(status, required_at);
create index if not exists workspace_v3_components_article_idx on public.workspace_v3_preview_components(article_code, component_kind);

alter table public.workspace_finished_bom_revisions enable row level security;
alter table public.workspace_finished_bom_lines enable row level security;
alter table public.workspace_v3_previews enable row level security;
alter table public.workspace_v3_preview_components enable row level security;
alter table public.workspace_v3_confirmation_sagas enable row level security;
alter table public.workspace_v3_material_commitments enable row level security;
alter table public.workspace_v3_purchase_requirements enable row level security;
alter table public.workspace_v3_purchase_documents enable row level security;
alter table public.workspace_v3_purchase_document_lines enable row level security;
alter table public.workspace_v3_outbox enable row level security;
alter table public.workspace_v3_audit enable row level security;
alter table public.workspace_v3_feature_flags enable row level security;

revoke all on public.workspace_finished_bom_revisions, public.workspace_finished_bom_lines,
  public.workspace_v3_previews, public.workspace_v3_preview_components,
  public.workspace_v3_confirmation_sagas, public.workspace_v3_material_commitments,
  public.workspace_v3_purchase_requirements, public.workspace_v3_purchase_documents,
  public.workspace_v3_purchase_document_lines, public.workspace_v3_outbox,
  public.workspace_v3_audit, public.workspace_v3_feature_flags from anon, authenticated;
grant select, insert, update on public.workspace_finished_bom_revisions, public.workspace_finished_bom_lines,
  public.workspace_v3_previews, public.workspace_v3_preview_components,
  public.workspace_v3_confirmation_sagas, public.workspace_v3_material_commitments,
  public.workspace_v3_purchase_requirements, public.workspace_v3_purchase_documents,
  public.workspace_v3_purchase_document_lines, public.workspace_v3_outbox,
  public.workspace_v3_audit, public.workspace_v3_feature_flags to service_role;

create or replace function public.confirm_workspace_v3_after_mes(
  p_preview_id bigint,
  p_external_id uuid,
  p_idempotency_key text,
  p_payload_hash text,
  p_expected_row_version bigint,
  p_mes_confirmation_id uuid,
  p_mes_production_order_id integer,
  p_mes_production_order_number text,
  p_actor text,
  p_correlation_id uuid,
  p_causation_id uuid default null
) returns table(saga_id bigint, status text, requirements_created integer)
language plpgsql security definer set search_path = public as $$
declare
  v_preview public.workspace_v3_previews%rowtype;
  v_saga public.workspace_v3_confirmation_sagas%rowtype;
  v_component public.workspace_v3_preview_components%rowtype;
  v_commitment_id bigint;
  v_requirements integer := 0;
begin
  if not coalesce((select enabled from public.workspace_v3_feature_flags where key='workspacemes.v3.confirm'), false) then
    raise exception 'WORKSPACEMES_V3_CONFIRM_DISABLED';
  end if;
  select * into v_preview from public.workspace_v3_previews where id=p_preview_id for update;
  if not found then raise exception 'V3_PREVIEW_NOT_FOUND'; end if;
  if v_preview.row_version <> p_expected_row_version then raise exception 'V3_CONCURRENT_MODIFICATION'; end if;
  if v_preview.status <> 'READY' then raise exception 'V3_PREVIEW_NOT_READY'; end if;
  select * into v_saga from public.workspace_v3_confirmation_sagas where idempotency_key=p_idempotency_key for update;
  if found then
    if v_saga.payload_hash <> p_payload_hash then raise exception 'V3_IDEMPOTENCY_CONFLICT'; end if;
    return query select v_saga.id, v_saga.status, 0;
    return;
  end if;
  insert into public.workspace_v3_confirmation_sagas(external_id,preview_id,idempotency_key,payload_hash,status,
    mes_confirmation_id,mes_production_order_id,mes_production_order_number,correlation_id,causation_id)
  values(p_external_id,p_preview_id,p_idempotency_key,p_payload_hash,'MATERIALIZING_WORKSPACE',
    p_mes_confirmation_id,p_mes_production_order_id,p_mes_production_order_number,p_correlation_id,p_causation_id)
  returning * into v_saga;
  for v_component in select * from public.workspace_v3_preview_components where preview_id=p_preview_id loop
    if v_component.required_quantity <= 0 then continue; end if;
    insert into public.workspace_v3_material_commitments(saga_id,preview_component_id,owner,article_code,unit_of_measure,quantity,source_commitment_id,status)
    values(v_saga.id,v_component.id,case when v_component.component_kind='DIRECT_COMPONENT' then 'WORKSPACE_DIRECT' else 'PROGREMES_MP_CERTIFIED' end,
      v_component.article_code,v_component.unit_of_measure,v_component.required_quantity,
      case when v_component.component_kind='FORMULA_MATERIAL' then p_mes_confirmation_id::text else null end,'ACTIVE')
    returning id into v_commitment_id;
    if v_component.uncovered_quantity > 0 then
      insert into public.workspace_v3_purchase_requirements(saga_id,commitment_id,article_code,unit_of_measure,required_quantity,expected_at,status,lineage)
      values(v_saga.id,v_commitment_id,v_component.article_code,v_component.unit_of_measure,v_component.uncovered_quantity,
        v_component.expected_available_at,'OPEN',jsonb_build_object('previewId',p_preview_id,'componentId',v_component.id,
        'productionOrderId',p_mes_production_order_id,'productionOrderNumber',p_mes_production_order_number));
      v_requirements := v_requirements + 1;
    end if;
  end loop;
  update public.workspace_v3_confirmation_sagas set status='COMPLETED',completed_at=now(),updated_at=now(),row_version=row_version+1 where id=v_saga.id;
  update public.workspace_v3_previews set status='CONFIRMED',confirmed_at=now(),row_version=row_version+1 where id=p_preview_id;
  insert into public.workspace_v3_outbox(aggregate_type,aggregate_id,destination,event_type,sequence,payload,payload_hash,correlation_id,causation_id)
  values('V3_CONFIRMATION_SAGA',v_saga.id::text,'WORKSPACE','WorkspaceV3Confirmed',1,
    jsonb_build_object('sagaId',v_saga.id,'previewId',p_preview_id,'productionOrderId',p_mes_production_order_id,'requirementsCreated',v_requirements),
    p_payload_hash,p_correlation_id,p_causation_id);
  insert into public.workspace_v3_audit(aggregate_type,aggregate_id,action,actor_id,after_hash,payload,correlation_id,causation_id)
  values('V3_CONFIRMATION_SAGA',v_saga.id::text,'CONFIRMED',p_actor,p_payload_hash,
    jsonb_build_object('previewId',p_preview_id,'requirementsCreated',v_requirements),p_correlation_id,p_causation_id);
  return query select v_saga.id, 'COMPLETED'::text, v_requirements;
end $$;

revoke all on function public.confirm_workspace_v3_after_mes(bigint,uuid,text,text,bigint,uuid,integer,text,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.confirm_workspace_v3_after_mes(bigint,uuid,text,text,bigint,uuid,integer,text,text,uuid,uuid) to service_role;

comment on table public.workspace_v3_previews is 'Snapshot V3 append-only: preview senza impegni, fabbisogni o prenotazioni.';
comment on table public.workspace_v3_purchase_requirements is 'Fabbisogno acquisti Workspace aggregato da DIRECT e copia certificata MP MES.';
comment on table public.workspace_v3_feature_flags is 'Gate V3 e sincronizzazioni legacy separabili; V3 resta fail-closed fino al collaudo.';
