-- Fase 1: RdP multi-OCT, UDM e snapshot auditabile della domanda.
-- Workspace non nettifica la disponibilità: quantità, impegni, arrivi e decisioni restano master ProgreMES.
-- Questa migration prepara soltanto il repository e non abilita alcun flusso mutante.

alter table if exists public.ordini_righe
  add column if not exists unita_misura_oct text,
  add column if not exists tipo_unita_misura_mexal text;

alter table if exists public.workspace_production_requests
  add column if not exists idempotency_key text,
  add column if not exists demand_hash text,
  add column if not exists contract_version integer not null default 1,
  add column if not exists request_kind text not null default 'SINGLE_OCT_LINE_LEGACY',
  add column if not exists requested_by uuid,
  add column if not exists demand_snapshot_id bigint,
  add column if not exists sent_demand_snapshot_id bigint,
  add column if not exists last_response jsonb;

update public.workspace_production_requests
set idempotency_key = 'legacy:' || id::text
where idempotency_key is null;

alter table public.workspace_production_requests
  alter column idempotency_key set not null;

create unique index if not exists workspace_production_requests_idempotency_uniq
  on public.workspace_production_requests (idempotency_key);

create table if not exists public.workspace_production_request_items (
  id uuid primary key default gen_random_uuid(),
  external_id uuid not null unique default gen_random_uuid(),
  production_request_id uuid not null references public.workspace_production_requests(id) on delete cascade,
  ordine_id uuid not null references public.ordini_testate(id) on delete restrict,
  ordine_riga_id uuid not null references public.ordini_righe(id) on delete restrict,
  item_index integer not null check (item_index > 0),
  item_external_key text not null,
  mexal_order_key text not null,
  mexal_line_position integer,
  codice_articolo_commerciale text not null,
  codice_articolo_produttivo text,
  mapping_status text not null default 'TO_RESOLVE_IN_MES',
  quantita_oct numeric(18,6) not null check (quantita_oct > 0),
  unita_misura_oct text not null,
  quantita_unita_produzione numeric(18,6) not null check (quantita_unita_produzione > 0),
  unita_misura_produzione text not null,
  conversione jsonb,
  data_consegna_richiesta date,
  mes_status text,
  mes_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (production_request_id, ordine_riga_id),
  unique (production_request_id, item_external_key),
  unique (production_request_id, item_index)
);

create table if not exists public.workspace_production_demand_snapshots (
  id bigint generated by default as identity primary key,
  production_request_id uuid references public.workspace_production_requests(id) on delete cascade,
  snapshot_hash text not null,
  demand_hash text not null,
  contract_version integer not null,
  order_count integer not null check (order_count > 0),
  item_count integer not null check (item_count > 0),
  requested_by uuid,
  snapshot jsonb not null,
  captured_at timestamptz not null default now(),
  last_validated_at timestamptz not null default now()
);

create unique index if not exists workspace_production_demand_snapshots_identity_uniq
  on public.workspace_production_demand_snapshots (
    coalesce(production_request_id, '00000000-0000-0000-0000-000000000000'::uuid), snapshot_hash
  );

alter table public.workspace_production_requests
  add constraint workspace_production_requests_demand_snapshot_fk
  foreign key (demand_snapshot_id) references public.workspace_production_demand_snapshots(id);

alter table public.workspace_production_requests
  add constraint workspace_production_requests_sent_demand_snapshot_fk
  foreign key (sent_demand_snapshot_id) references public.workspace_production_demand_snapshots(id);

alter table if exists public.workspace_production_proposals
  add column if not exists production_request_item_id uuid references public.workspace_production_request_items(id),
  add column if not exists item_external_key text;

alter table public.workspace_production_request_items enable row level security;
alter table public.workspace_production_demand_snapshots enable row level security;
revoke all on public.workspace_production_request_items from anon, authenticated;
revoke all on public.workspace_production_demand_snapshots from anon, authenticated;

create index if not exists workspace_production_request_items_oct_idx
  on public.workspace_production_request_items (ordine_id, ordine_riga_id);
create index if not exists workspace_production_request_items_mes_status_idx
  on public.workspace_production_request_items (mes_status) where mes_status is not null;

create or replace function public.record_workspace_production_demand(
  p_create_request boolean,
  p_idempotency_key text,
  p_demand_hash text,
  p_snapshot_hash text,
  p_snapshot jsonb,
  p_requested_by uuid default null
) returns table(
  request_id uuid,
  external_id uuid,
  snapshot_id bigint,
  snapshot_hash text,
  snapshot_captured_at timestamptz,
  reused boolean,
  attempt_count integer
)
language plpgsql security definer set search_path = public as $$
declare
  v_request public.workspace_production_requests%rowtype;
  v_snapshot public.workspace_production_demand_snapshots%rowtype;
  v_item jsonb;
  v_reused boolean := false;
begin
  if nullif(btrim(p_idempotency_key), '') is null or nullif(btrim(p_demand_hash), '') is null or
     nullif(btrim(p_snapshot_hash), '') is null then
    raise exception 'INVALID_DEMAND_IDENTITY';
  end if;
  if coalesce((p_snapshot->>'version')::integer, 0) <> 2 or
     p_snapshot->>'kind' <> 'MULTI_OCT_PRODUCTION_DEMAND' or
     jsonb_typeof(p_snapshot->'items') <> 'array' or
     jsonb_array_length(p_snapshot->'items') = 0 then
    raise exception 'INVALID_MULTI_OCT_DEMAND';
  end if;

  if p_create_request then
    select * into v_request from public.workspace_production_requests
      where idempotency_key = p_idempotency_key for update;
    if found then
      if v_request.demand_hash is distinct from p_demand_hash then
        raise exception 'IDEMPOTENCY_CONFLICT';
      end if;
      v_reused := true;
    else
      insert into public.workspace_production_requests (
        ordine_id, ordine_riga_id, idempotency_key, demand_hash,
        contract_version, request_kind, requested_by, stato, workspace_status
      ) values (
        ((p_snapshot->'items'->0)->>'orderId')::uuid,
        ((p_snapshot->'items'->0)->>'lineId')::uuid,
        p_idempotency_key, p_demand_hash,
        2, 'MULTI_OCT_PRODUCTION_DEMAND', p_requested_by, 'PRONTA', 'PRONTA'
      ) returning * into v_request;
    end if;
  end if;

  select * into v_snapshot from public.workspace_production_demand_snapshots
    where production_request_id is not distinct from v_request.id
      and snapshot_hash = p_snapshot_hash;
  if found then
    v_reused := true;
    update public.workspace_production_demand_snapshots
      set last_validated_at = now()
      where id = v_snapshot.id
      returning * into v_snapshot;
  else
    insert into public.workspace_production_demand_snapshots (
      production_request_id, snapshot_hash, demand_hash, contract_version,
      order_count, item_count, requested_by, snapshot
    ) values (
      v_request.id, p_snapshot_hash, p_demand_hash, 2,
      (p_snapshot->>'orderCount')::integer,
      (p_snapshot->>'itemCount')::integer,
      p_requested_by, p_snapshot
    ) returning * into v_snapshot;
  end if;

  if p_create_request then
    for v_item in select value from jsonb_array_elements(p_snapshot->'items') loop
      insert into public.workspace_production_request_items (
        production_request_id, ordine_id, ordine_riga_id, item_index,
        item_external_key, mexal_order_key, mexal_line_position,
        codice_articolo_commerciale, codice_articolo_produttivo, mapping_status,
        quantita_oct, unita_misura_oct, quantita_unita_produzione,
        unita_misura_produzione, conversione, data_consegna_richiesta
      ) values (
        v_request.id,
        (v_item->>'orderId')::uuid,
        (v_item->>'lineId')::uuid,
        (v_item->>'itemIndex')::integer,
        v_item->>'itemExternalKey',
        v_item->>'mexalOrderKey',
        nullif(v_item->>'mexalLinePosition', '')::integer,
        v_item->>'commercialArticleCode',
        nullif(v_item->>'productionArticleCode', ''),
        coalesce(nullif(v_item->>'mappingStatus', ''), 'TO_RESOLVE_IN_MES'),
        (v_item->>'requestedQuantity')::numeric,
        v_item->>'requestedUnitOfMeasure',
        (v_item->>'productionQuantity')::numeric,
        v_item->>'productionUnitOfMeasure',
        v_item->'conversion',
        nullif(v_item->>'requestedDeliveryDate', '')::date
      ) on conflict (production_request_id, ordine_riga_id) do nothing;
    end loop;

    update public.workspace_production_requests set
      demand_snapshot_id = v_snapshot.id,
      updated_at = now()
    where id = v_request.id
    returning * into v_request;
  end if;

  return query select v_request.id, v_request.external_id, v_snapshot.id,
    v_snapshot.snapshot_hash, v_snapshot.captured_at, v_reused,
    coalesce(v_request.attempt_count, 0);
end $$;

revoke all on function public.record_workspace_production_demand(boolean,text,text,text,jsonb,uuid)
  from public, anon, authenticated;
grant execute on function public.record_workspace_production_demand(boolean,text,text,text,jsonb,uuid)
  to service_role;

create or replace function public.process_workspace_production_event(
  p_event_id uuid,
  p_external_id uuid,
  p_sequence bigint,
  p_event_type text,
  p_payload_hash text,
  p_payload jsonb
) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_request public.workspace_production_requests%rowtype;
  v_existing_hash text;
  v_proposal jsonb;
  v_request_item_id uuid;
begin
  select payload_hash into v_existing_hash from public.workspace_production_event_inbox where event_id = p_event_id;
  if found then
    if v_existing_hash <> p_payload_hash then
      raise exception 'EventId già usato con payload differente.' using errcode = 'P0001';
    end if;
    return 'duplicate';
  end if;

  select * into v_request from public.workspace_production_requests
  where external_id = p_external_id for update;
  if not found then raise exception 'RdP Workspace non trovata.' using errcode = 'P0001'; end if;

  insert into public.workspace_production_event_inbox(event_id, external_id, sequence, event_type, payload_hash, payload)
  values (p_event_id, p_external_id, p_sequence, p_event_type, p_payload_hash, p_payload);

  if p_sequence <= v_request.last_event_sequence then
    update public.workspace_production_event_inbox set processed_at = now() where event_id = p_event_id;
    return 'stale';
  end if;

  update public.workspace_production_requests set
    stato = coalesce(p_payload->>'status', stato),
    workspace_status = coalesce(p_payload->>'workspaceStatus', workspace_status),
    last_event_sequence = p_sequence,
    updated_at = now()
  where id = v_request.id;

  for v_proposal in select value from jsonb_array_elements(coalesce(p_payload->'proposals', '[]'::jsonb)) loop
    select id into v_request_item_id from public.workspace_production_request_items
      where production_request_id = v_request.id
        and item_external_key = v_proposal->>'itemExternalKey';
    if coalesce((p_payload->>'schemaVersion')::integer, 1) >= 2 and v_request_item_id is null then
      raise exception 'UNKNOWN_PRODUCTION_REQUEST_ITEM';
    end if;
    insert into public.workspace_production_proposals(
      production_request_id, production_request_item_id, item_external_key,
      mes_proposal_id, production_index, quantita, stato, material_status,
      expected_material_availability, mes_production_order_id, mes_production_order_number, updated_at)
    values (
      v_request.id, v_request_item_id, nullif(v_proposal->>'itemExternalKey', ''),
      (v_proposal->>'id')::integer, (v_proposal->>'productionIndex')::integer,
      (v_proposal->>'quantity')::numeric, v_proposal->>'status', v_proposal->>'materialStatus',
      nullif(v_proposal->>'expectedMaterialAvailability','')::date,
      nullif(v_proposal->>'productionOrderId','')::integer,
      nullif(v_proposal->>'productionOrderNumber',''), now())
    on conflict (mes_proposal_id) do update set
      production_request_item_id = excluded.production_request_item_id,
      item_external_key = excluded.item_external_key,
      stato = excluded.stato, material_status = excluded.material_status,
      expected_material_availability = excluded.expected_material_availability,
      mes_production_order_id = excluded.mes_production_order_id,
      mes_production_order_number = excluded.mes_production_order_number, updated_at = now();
  end loop;

  update public.workspace_production_event_inbox set processed_at = now() where event_id = p_event_id;
  return 'processed';
end $$;

revoke all on function public.process_workspace_production_event(uuid,uuid,bigint,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.process_workspace_production_event(uuid,uuid,bigint,text,text,jsonb)
  to service_role;

comment on table public.workspace_production_request_items is
  'Righe OCT conservate separatamente dentro una RdP multi-OCT; ProgreMES può aggregare tecnicamente senza perdere la provenienza.';
comment on table public.workspace_production_demand_snapshots is
  'Snapshot append-only della domanda commerciale inviata; non contiene nettificazione o prenotazioni autorevoli.';
comment on column public.workspace_production_requests.demand_hash is
  'Hash stabile della domanda completa usato per idempotenza e conflitti controllati.';
