-- WorkspaceMES Fase 1: revisioni OCT monotone e callback compatibili con il contratto RdP v2.
-- La migration è additiva e non modifica cicli/job Mexal né righe OCT storiche.

create table if not exists public.workspace_oct_contract_revisions (
  id bigint generated by default as identity primary key,
  ordine_id uuid not null references public.ordini_testate(id) on delete restrict,
  commercial_revision integer not null check (commercial_revision > 0),
  version_hash text not null check (version_hash ~ '^[0-9a-f]{64}$'),
  source_timestamp timestamptz not null,
  created_at timestamptz not null default now(),
  unique (ordine_id, commercial_revision)
);

create index if not exists workspace_oct_contract_revisions_current_idx
  on public.workspace_oct_contract_revisions (ordine_id, commercial_revision desc);

alter table public.workspace_oct_contract_revisions enable row level security;
revoke all on public.workspace_oct_contract_revisions from anon, authenticated;

create or replace function public.reserve_workspace_oct_contract_revisions(
  p_octs jsonb,
  p_commit boolean default false
) returns table(
  order_id uuid,
  commercial_revision integer,
  version_hash text,
  source_timestamp timestamptz
)
language plpgsql security definer set search_path = public as $$
declare
  v_oct jsonb;
  v_order_id uuid;
  v_hash text;
  v_source_timestamp timestamptz;
  v_current public.workspace_oct_contract_revisions%rowtype;
  v_revision integer;
begin
  if jsonb_typeof(p_octs) is distinct from 'array' or jsonb_array_length(p_octs) = 0 then
    raise exception 'INVALID_OCT_REVISIONS';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_octs) item
    group by item->>'orderId'
    having count(*) > 1
  ) then
    raise exception 'DUPLICATE_OCT_REVISION';
  end if;

  for v_oct in select value from jsonb_array_elements(p_octs) loop
    v_order_id := nullif(v_oct->>'orderId', '')::uuid;
    v_hash := lower(btrim(v_oct->>'versionHash'));
    v_source_timestamp := nullif(v_oct->>'sourceTimestamp', '')::timestamptz;
    if v_order_id is null or v_hash !~ '^[0-9a-f]{64}$' or v_source_timestamp is null then
      raise exception 'INVALID_OCT_REVISION';
    end if;
    if not exists (select 1 from public.ordini_testate o where o.id = v_order_id and o.origine = 'mexal_oct') then
      raise exception 'INVALID_OCT_ORDER';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(v_order_id::text, 0));
    select r.* into v_current
      from public.workspace_oct_contract_revisions r
      where r.ordine_id = v_order_id
      order by r.commercial_revision desc
      limit 1;

    if found and v_current.version_hash = v_hash then
      v_revision := v_current.commercial_revision;
      v_source_timestamp := v_current.source_timestamp;
    else
      v_revision := coalesce(v_current.commercial_revision, 0) + 1;
      if p_commit then
        insert into public.workspace_oct_contract_revisions(
          ordine_id, commercial_revision, version_hash, source_timestamp
        ) values (v_order_id, v_revision, v_hash, v_source_timestamp);
      end if;
    end if;

    order_id := v_order_id;
    commercial_revision := v_revision;
    version_hash := v_hash;
    source_timestamp := v_source_timestamp;
    return next;
  end loop;
end $$;

revoke all on function public.reserve_workspace_oct_contract_revisions(jsonb,boolean)
  from public, anon, authenticated;
grant execute on function public.reserve_workspace_oct_contract_revisions(jsonb,boolean)
  to service_role;

create or replace function public.record_workspace_production_v2_response(
  p_request_id uuid,
  p_payload_hash text,
  p_snapshot_id bigint,
  p_response jsonb
) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_request public.workspace_production_requests%rowtype;
  v_analysis jsonb;
  v_line_id uuid;
  v_item_count integer;
  v_analysis_count integer;
  v_updated integer;
begin
  select * into v_request
  from public.workspace_production_requests
  where id = p_request_id
  for update;
  if not found then raise exception 'PRODUCTION_REQUEST_NOT_FOUND'; end if;
  if nullif(btrim(p_payload_hash), '') is null or nullif(p_response->>'status', '') is null or
     nullif(p_response->>'workspaceExternalId', '')::uuid is distinct from v_request.external_id or
     p_response->'productionMutationsEnabled' is distinct from 'false'::jsonb or
     jsonb_typeof(p_response->'analyses') is distinct from 'array' then
    raise exception 'INVALID_MES_RESPONSE';
  end if;
  if not exists (
    select 1 from public.workspace_production_demand_snapshots snapshot
    where snapshot.id = p_snapshot_id and snapshot.production_request_id = p_request_id
  ) then
    raise exception 'INVALID_DEMAND_SNAPSHOT';
  end if;

  select count(*)::integer into v_item_count
  from public.workspace_production_request_items
  where production_request_id = p_request_id;
  select jsonb_array_length(p_response->'analyses') into v_analysis_count;
  if v_item_count = 0 or v_analysis_count <> v_item_count then
    raise exception 'INCOMPLETE_MES_ANALYSIS';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_response->'analyses') analysis
    group by analysis->>'workspaceLineId'
    having count(*) > 1
  ) then
    raise exception 'DUPLICATE_MES_ANALYSIS';
  end if;

  for v_analysis in select value from jsonb_array_elements(p_response->'analyses') loop
    v_line_id := nullif(v_analysis->>'workspaceLineId', '')::uuid;
    if v_line_id is null or nullif(v_analysis->>'snapshotHash', '') is null or
       jsonb_typeof(v_analysis->'blockCode') is distinct from 'string' then
      raise exception 'INVALID_MES_ANALYSIS';
    end if;
    update public.workspace_production_request_items set
      mes_status = case when nullif(v_analysis->>'blockCode', '') is null
        then 'ANALYZED' else 'BLOCKED:' || (v_analysis->>'blockCode') end,
      mes_payload = v_analysis,
      updated_at = now()
    where production_request_id = p_request_id and ordine_riga_id = v_line_id;
    get diagnostics v_updated = row_count;
    if v_updated <> 1 then raise exception 'UNKNOWN_MES_ANALYSIS_LINE'; end if;
  end loop;

  update public.workspace_production_requests set
    payload_hash = p_payload_hash,
    stato = p_response->>'status',
    workspace_status = coalesce(p_response->>'workspaceStatus', p_response->>'status'),
    attempt_count = attempt_count + 1,
    sent_demand_snapshot_id = p_snapshot_id,
    last_response = p_response,
    last_error_code = null,
    updated_at = now()
  where id = p_request_id;
end $$;

revoke all on function public.record_workspace_production_v2_response(uuid,text,bigint,jsonb)
  from public, anon, authenticated;
grant execute on function public.record_workspace_production_v2_response(uuid,text,bigint,jsonb)
  to service_role;

create or replace function public.process_workspace_production_event(
  p_event_id uuid,
  p_external_id uuid,
  p_sequence bigint,
  p_event_type text,
  p_payload_hash text,
  p_payload jsonb
) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_request public.workspace_production_requests%rowtype;
  v_existing_hash text;
  v_proposal jsonb;
  v_request_item_id uuid;
begin
  select payload_hash into v_existing_hash from public.workspace_production_event_inbox where event_id = p_event_id;
  if found then
    if v_existing_hash <> p_payload_hash then
      raise exception 'EventId già usato con payload differente.' using errcode = 'P0001';
    end if;
    return 'duplicate';
  end if;

  select * into v_request from public.workspace_production_requests
  where external_id = p_external_id for update;
  if not found then raise exception 'RdP Workspace non trovata.' using errcode = 'P0001'; end if;

  insert into public.workspace_production_event_inbox(event_id, external_id, sequence, event_type, payload_hash, payload)
  values (p_event_id, p_external_id, p_sequence, p_event_type, p_payload_hash, p_payload);

  if p_sequence <= v_request.last_event_sequence then
    update public.workspace_production_event_inbox set processed_at = now() where event_id = p_event_id;
    return 'stale';
  end if;

  update public.workspace_production_requests set
    stato = coalesce(p_payload->>'status', stato),
    workspace_status = coalesce(p_payload->>'workspaceStatus', p_payload->>'status', workspace_status),
    last_event_sequence = p_sequence,
    last_response = p_payload,
    updated_at = now()
  where id = v_request.id;

  for v_proposal in select value from jsonb_array_elements(coalesce(p_payload->'proposals', '[]'::jsonb)) loop
    select id into v_request_item_id from public.workspace_production_request_items
      where production_request_id = v_request.id
        and item_external_key = v_proposal->>'itemExternalKey';
    if coalesce((p_payload->>'schemaVersion')::integer, 1) >= 2 and v_request_item_id is null then
      raise exception 'UNKNOWN_PRODUCTION_REQUEST_ITEM';
    end if;
    insert into public.workspace_production_proposals(
      production_request_id, production_request_item_id, item_external_key,
      mes_proposal_id, production_index, quantita, stato, material_status,
      expected_material_availability, mes_production_order_id, mes_production_order_number, updated_at)
    values (
      v_request.id, v_request_item_id, nullif(v_proposal->>'itemExternalKey', ''),
      (v_proposal->>'id')::integer, (v_proposal->>'productionIndex')::integer,
      (v_proposal->>'quantity')::numeric, v_proposal->>'status', v_proposal->>'materialStatus',
      nullif(v_proposal->>'expectedMaterialAvailability','')::date,
      nullif(v_proposal->>'productionOrderId','')::integer,
      nullif(v_proposal->>'productionOrderNumber',''), now())
    on conflict (mes_proposal_id) do update set
      production_request_item_id = excluded.production_request_item_id,
      item_external_key = excluded.item_external_key,
      stato = excluded.stato, material_status = excluded.material_status,
      expected_material_availability = excluded.expected_material_availability,
      mes_production_order_id = excluded.mes_production_order_id,
      mes_production_order_number = excluded.mes_production_order_number, updated_at = now();
  end loop;

  update public.workspace_production_event_inbox set processed_at = now() where event_id = p_event_id;
  return 'processed';
end $$;

revoke all on function public.process_workspace_production_event(uuid,uuid,bigint,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.process_workspace_production_event(uuid,uuid,bigint,text,text,jsonb)
  to service_role;

comment on table public.workspace_oct_contract_revisions is
  'Registro append-only delle revisioni commerciali OCT inviate nel contratto WorkspaceMES RdP v2.';
