begin;

create table if not exists public.mexal_fatture_vendita (
  id uuid primary key default gen_random_uuid(),
  sigla text not null default 'FT' check (sigla = 'FT'),
  cod_modulo text not null default 'E' check (cod_modulo = 'E'),
  serie integer not null,
  numero bigint not null,
  data_documento date not null,
  codice_cliente text not null,
  ragione_sociale_cliente text,
  codice_agente_mexal text,
  agente_nome text,
  id_pagamento integer,
  nota text,
  totale_imponibile numeric(16,4) not null default 0,
  totale_iva numeric(16,4) not null default 0,
  totale_documento numeric(16,4) not null default 0,
  dati_mexal jsonb not null default '{}'::jsonb,
  sincronizzato_il timestamptz not null default now(),
  creato_il timestamptz not null default now(),
  aggiornato_il timestamptz not null default now(),
  unique (sigla, serie, numero, codice_cliente)
);

create table if not exists public.mexal_fatture_vendita_righe (
  id bigint generated by default as identity primary key,
  fattura_id uuid not null references public.mexal_fatture_vendita(id) on delete cascade,
  posizione integer not null,
  tipo_riga text,
  codice_articolo text,
  descrizione text,
  quantita numeric(16,4) not null default 0,
  prezzo_unitario numeric(16,6) not null default 0,
  sconto text,
  aliquota_iva numeric(8,4),
  codice_agente_mexal text,
  dati_mexal jsonb not null default '{}'::jsonb,
  unique (fattura_id, posizione)
);

create table if not exists public.mexal_fatture_sync_stato (
  id integer primary key default 1 check (id = 1),
  next_cursor text,
  ciclo_iniziato_il timestamptz,
  aggiornato_il timestamptz not null default now()
);
insert into public.mexal_fatture_sync_stato(id) values (1) on conflict (id) do nothing;

alter table if exists public.mexal_sync_schedules
  drop constraint if exists mexal_sync_schedules_sync_type_check;
alter table if exists public.mexal_sync_schedules
  add constraint mexal_sync_schedules_sync_type_check
  check (sync_type in ('clients','agents','products','commercial_conditions','document_series','stocks','orders','payments','list_price_commissions','sales_invoices'));

alter table if exists public.mexal_sync_runs
  drop constraint if exists mexal_sync_runs_sync_type_check;
alter table if exists public.mexal_sync_runs
  add constraint mexal_sync_runs_sync_type_check
  check (sync_type in ('products','clients','stocks','orders','commercial_conditions','document_series','agents','payments','list_price_commissions','sales_invoices'));

insert into public.mexal_sync_schedules(sync_type, enabled, schedule_mode, batch_size, execution_order)
values ('sales_invoices', true, 'daily_vercel_hobby', 500, 7)
on conflict (sync_type) do update
set enabled = excluded.enabled,
    schedule_mode = excluded.schedule_mode,
    batch_size = excluded.batch_size,
    execution_order = excluded.execution_order,
    updated_at = now();

create index if not exists mexal_fatture_vendita_data_idx
  on public.mexal_fatture_vendita(data_documento desc, serie, numero desc);
create index if not exists mexal_fatture_vendita_cliente_idx
  on public.mexal_fatture_vendita(codice_cliente);
create index if not exists mexal_fatture_vendita_agente_idx
  on public.mexal_fatture_vendita(codice_agente_mexal);
create index if not exists mexal_fatture_vendita_righe_fattura_idx
  on public.mexal_fatture_vendita_righe(fattura_id, posizione);

alter table public.mexal_fatture_vendita enable row level security;
alter table public.mexal_fatture_vendita_righe enable row level security;

create or replace function public.can_view_mexal_sales_invoice(p_agent_code text)
returns boolean
language sql stable security definer set search_path = public
as $$
  with me as (
    select u.id, coalesce(r.livello, 0) livello, lower(coalesce(r.nome, '')) ruolo
    from public.utenti u
    left join public.ruoli r on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid() and u.attivo is not false
  )
  select exists (
    select 1 from me
    where livello >= 80
       or ruolo in ('admin','administrator','amministratore','super admin','direzione')
  )
  or exists (
    select 1
    from public.integrazioni_utenti iu
    join me on me.id = iu.utente_id
    where iu.enabled is true
      and iu.modulo in ('gestione_ordini_pr', 'gestione_ordini_ph')
      and iu.ruolo_ordini = 'backoffice'
  )
  or nullif(btrim(coalesce(p_agent_code, '')), '') in (
    select public.visible_mexal_agent_codes()
  );
$$;

drop policy if exists "fatture vendita visibili per organizzazione" on public.mexal_fatture_vendita;
create policy "fatture vendita visibili per organizzazione"
on public.mexal_fatture_vendita for select to authenticated
using (public.can_view_mexal_sales_invoice(codice_agente_mexal));

drop policy if exists "righe fatture vendita visibili per organizzazione" on public.mexal_fatture_vendita_righe;
create policy "righe fatture vendita visibili per organizzazione"
on public.mexal_fatture_vendita_righe for select to authenticated
using (
  exists (
    select 1 from public.mexal_fatture_vendita f
    where f.id = fattura_id
      and public.can_view_mexal_sales_invoice(f.codice_agente_mexal)
  )
);

revoke all on table public.mexal_fatture_vendita from public, anon, authenticated;
revoke all on table public.mexal_fatture_vendita_righe from public, anon, authenticated;
grant select on table public.mexal_fatture_vendita to authenticated;
grant select on table public.mexal_fatture_vendita_righe to authenticated;
grant all on table public.mexal_fatture_vendita to service_role;
grant all on table public.mexal_fatture_vendita_righe to service_role;
grant all on table public.mexal_fatture_sync_stato to service_role;
grant usage, select on sequence public.mexal_fatture_vendita_righe_id_seq to service_role;
revoke all on function public.can_view_mexal_sales_invoice(text) from public, anon;
grant execute on function public.can_view_mexal_sales_invoice(text) to authenticated, service_role;

commit;
