begin;

alter table public.ai_action_audit drop constraint if exists ai_action_audit_status_check;
alter table public.ai_action_audit add constraint ai_action_audit_status_check
  check (status in ('proposed','confirmed','executed','failed','rejected','rolled_back'));
alter table public.ai_action_audit add column if not exists before_snapshot jsonb;
alter table public.ai_action_audit add column if not exists rolled_back_at timestamptz;
alter table public.ai_action_audit add column if not exists rolled_back_by uuid references public.utenti(id);

create table if not exists public.workspace_builder_scoped_layouts (
  id uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('screen','module','menu')),
  target_code text not null,
  scope_type text not null check (scope_type in ('global','role','department','user')),
  scope_id uuid,
  layout jsonb not null,
  current_version integer not null default 1,
  active boolean not null default true,
  updated_by uuid references public.utenti(id) on delete set null,
  updated_at timestamptz not null default now(),
  check ((scope_type='global' and scope_id is null) or (scope_type<>'global' and scope_id is not null))
);
create unique index if not exists workspace_builder_scoped_layout_identity_uq
  on public.workspace_builder_scoped_layouts(target_type,target_code,scope_type,coalesce(scope_id,'00000000-0000-0000-0000-000000000000'::uuid));

create table if not exists public.workspace_builder_scoped_versions (
  id bigint generated by default as identity primary key,
  layout_id uuid not null references public.workspace_builder_scoped_layouts(id) on delete restrict,
  version integer not null,
  layout jsonb not null,
  created_by uuid references public.utenti(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(layout_id,version)
);

create table if not exists public.workspace_ai_monitor_rules (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.utenti(id) on delete cascade,
  name text not null,
  dataset text not null check(dataset in ('orders','rdp','op','lots','documents','materials','synchronizations')),
  condition jsonb not null,
  frequency_minutes integer not null check(frequency_minutes between 5 and 10080),
  notification_mode text not null default 'on_change' check(notification_mode in ('on_change','on_match','daily_summary')),
  active boolean not null default true,
  last_evaluated_at timestamptz,
  last_result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.workspace_builder_scoped_layouts enable row level security;
alter table public.workspace_builder_scoped_versions enable row level security;
alter table public.workspace_ai_monitor_rules enable row level security;
create policy "admins inspect scoped layouts" on public.workspace_builder_scoped_layouts for select to authenticated using(public.workspace_user_is_admin());
create policy "admins inspect scoped versions" on public.workspace_builder_scoped_versions for select to authenticated using(public.workspace_user_is_admin());
create policy "owners manage ai monitors" on public.workspace_ai_monitor_rules for select to authenticated
  using(user_id=public.workspace_current_profile_id() or public.workspace_user_is_admin());
grant select on public.workspace_builder_scoped_layouts,public.workspace_builder_scoped_versions,public.workspace_ai_monitor_rules to authenticated;

create or replace function public.workspace_validate_builder_layout(target_layout jsonb)
returns void language plpgsql immutable set search_path=public as $$
declare target_blocks jsonb;
begin
  if jsonb_typeof(target_layout)<>'object' then raise exception 'Layout non valido.'; end if;
  target_blocks:=target_layout->'blocks';
  if jsonb_typeof(target_blocks)<>'array' or jsonb_array_length(target_blocks)>40 then raise exception 'Elenco blocchi non valido.'; end if;
  if exists(select 1 from jsonb_array_elements(target_blocks) b where coalesce(b->>'type','') not in ('system-content','text','panel','notice','button','links','divider','kpi','data-table')) then raise exception 'Tipo di blocco non consentito.'; end if;
  if exists(select b->>'id' from jsonb_array_elements(target_blocks)b group by b->>'id' having b->>'id' is null or count(*)>1) then raise exception 'Identificatori blocco non validi.'; end if;
  if exists(select 1 from jsonb_array_elements(target_blocks)b where b->>'type' in ('kpi','data-table') and coalesce(b->>'dataset','') not in ('products','documents','orders','projects','tasks')) then raise exception 'Dataset non consentito.'; end if;
  if exists(select 1 from jsonb_array_elements(target_blocks)b where b->>'type'='button' and coalesce(b->>'href','')!~'^(\/|https:\/\/)') then raise exception 'Destinazione pulsante non consentita.'; end if;
end $$;

create or replace function public.workspace_resolve_builder_layout(p_target_type text,p_target_code text)
returns jsonb language sql stable security definer set search_path=public as $$
  with me as (
    select u.id,u.ruolo_id,u.reparto_id from public.utenti u where u.auth_user_id=auth.uid() and u.attivo is not false limit 1
  ), candidates as (
    select l.layout,case l.scope_type when 'user' then 40 when 'role' then 30 when 'department' then 20 else 10 end priority,l.updated_at
    from public.workspace_builder_scoped_layouts l cross join me
    where l.active and l.target_type=p_target_type and l.target_code=p_target_code and (
      l.scope_type='global' or (l.scope_type='user' and l.scope_id=me.id) or
      (l.scope_type='role' and l.scope_id=me.ruolo_id) or
      (l.scope_type='department' and (l.scope_id=me.reparto_id or exists(select 1 from public.utenti_reparti ur where ur.utente_id=me.id and ur.reparto_id=l.scope_id)))
    )
    union all select legacy.layout,0,legacy.updated_at from public.workspace_builder_layouts legacy where legacy.target_type=p_target_type and legacy.target_code=p_target_code
  ) select layout from candidates order by priority desc,updated_at desc limit 1
$$;

create or replace function public.workspace_ai_can_propose()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce((select r.amministratore_workspace or r.livello_ai in ('bozza','conferma')
    from public.utenti u join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false limit 1),false)
$$;
create or replace function public.workspace_ai_can_confirm()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce((select r.amministratore_workspace or r.livello_ai='conferma'
    from public.utenti u join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false limit 1),false)
$$;

create or replace function public.propose_workspace_ai_action(p_tool text,p_payload jsonb,p_request_id uuid,p_correlation_id uuid,p_idempotency_key text)
returns public.ai_action_audit language plpgsql security definer set search_path=public as $$
declare v_user uuid:=public.workspace_current_profile_id(); v_registry public.ai_action_registry; v_row public.ai_action_audit; v_scope uuid;
begin
  if v_user is null or not public.workspace_ai_can_propose() then raise exception 'FORBIDDEN'; end if;
  select * into v_registry from public.ai_action_registry where code=p_tool and active;
  if v_registry.code is null then raise exception 'TOOL_NOT_ALLOWED'; end if;
  if p_tool='ACCESS_ROLE_UPDATE' and not public.workspace_user_is_admin() then raise exception 'FORBIDDEN'; end if;
  if p_tool='ARTICLE_UPDATE' and not public.workspace_user_is_admin() and coalesce(public.workspace_access_context()->'module_levels'->>'prodotti','nessuno') not in ('scrittura','amministrazione') then raise exception 'FORBIDDEN'; end if;
  if p_tool='DOCUMENT_METADATA_UPDATE' and not public.workspace_user_is_admin() and coalesce(public.workspace_access_context()->'module_levels'->>'documenti','nessuno') not in ('scrittura','amministrazione') then raise exception 'FORBIDDEN'; end if;
  if p_tool='UI_CONFIGURE_VIEW' and p_payload->>'scopeType'='user' then
    v_scope:=nullif(p_payload->>'scopeId','')::uuid;
    if v_scope is distinct from v_user and not public.workspace_user_is_admin() then raise exception 'FORBIDDEN'; end if;
  elsif p_tool='UI_CONFIGURE_VIEW' and p_payload->>'scopeType'<>'user' and not public.workspace_user_is_admin() then raise exception 'FORBIDDEN';
  end if;
  if v_registry.system='mes' and not public.company_mes_ai_can_write() then raise exception 'FORBIDDEN'; end if;
  insert into public.ai_action_audit(user_id,system,tool,action,target,payload_summary,status,request_id,correlation_id,idempotency_key)
  values(v_user,v_registry.system,p_tool,lower(p_tool),coalesce(p_payload->>'targetId',p_payload->>'targetCode',p_payload->>'roleId',p_payload->>'name'),p_payload,'proposed',p_request_id,p_correlation_id,p_idempotency_key)
  on conflict(user_id,tool,idempotency_key) where idempotency_key is not null do update set occurred_at=public.ai_action_audit.occurred_at
  returning * into v_row; return v_row;
end $$;

create or replace function public.decide_workspace_ai_action(p_proposal_id uuid,p_confirm boolean)
returns public.ai_action_audit language plpgsql security definer set search_path=public as $$
declare v_user uuid:=public.workspace_current_profile_id(); v_action public.ai_action_audit; v_layout_id uuid; v_version integer; v_changes jsonb; v_target uuid;
begin
  if v_user is null or not public.workspace_ai_can_confirm() then raise exception 'FORBIDDEN'; end if;
  select * into v_action from public.ai_action_audit where id=p_proposal_id and user_id=v_user for update;
  if v_action.id is null then raise exception 'NOT_FOUND'; end if;
  if v_action.status in ('executed','failed','rejected','rolled_back') then return v_action; end if;
  if v_action.status<>'proposed' then raise exception 'INVALID_STATE'; end if;
  if not p_confirm then update public.ai_action_audit set status='rejected',result='{"changed":false}'::jsonb where id=v_action.id returning * into v_action; return v_action; end if;
  update public.ai_action_audit set status='confirmed',confirmed_at=now() where id=v_action.id;
  if v_action.system='mes' then select * into v_action from public.ai_action_audit where id=v_action.id; return v_action; end if;

  if v_action.tool='UI_CONFIGURE_VIEW' then
    perform public.workspace_validate_builder_layout(v_action.payload_summary->'layout');
    update public.ai_action_audit set before_snapshot=(select to_jsonb(l) from public.workspace_builder_scoped_layouts l where l.target_type=v_action.payload_summary->>'targetType' and l.target_code=v_action.payload_summary->>'targetCode' and l.scope_type=v_action.payload_summary->>'scopeType' and l.scope_id is not distinct from nullif(v_action.payload_summary->>'scopeId','')::uuid) where id=v_action.id;
    select id,current_version into v_layout_id,v_version from public.workspace_builder_scoped_layouts where target_type=v_action.payload_summary->>'targetType' and target_code=v_action.payload_summary->>'targetCode' and scope_type=v_action.payload_summary->>'scopeType' and scope_id is not distinct from nullif(v_action.payload_summary->>'scopeId','')::uuid for update;
    if v_layout_id is null then
      insert into public.workspace_builder_scoped_layouts(target_type,target_code,scope_type,scope_id,layout,updated_by)
      values(v_action.payload_summary->>'targetType',v_action.payload_summary->>'targetCode',v_action.payload_summary->>'scopeType',nullif(v_action.payload_summary->>'scopeId','')::uuid,v_action.payload_summary->'layout',v_user)
      returning id,current_version into v_layout_id,v_version;
    else
      update public.workspace_builder_scoped_layouts set layout=v_action.payload_summary->'layout',current_version=current_version+1,updated_by=v_user,updated_at=now() where id=v_layout_id returning current_version into v_version;
    end if;
    insert into public.workspace_builder_scoped_versions(layout_id,version,layout,created_by) values(v_layout_id,v_version,v_action.payload_summary->'layout',v_user);
  elsif v_action.tool='MONITOR_RULE_CREATE' then
    insert into public.workspace_ai_monitor_rules(user_id,name,dataset,condition,frequency_minutes,notification_mode,active)
    values(v_user,v_action.payload_summary->>'name',v_action.payload_summary->>'dataset',v_action.payload_summary->'condition',(v_action.payload_summary->>'frequencyMinutes')::integer,coalesce(v_action.payload_summary->>'notificationMode','on_change'),coalesce((v_action.payload_summary->>'active')::boolean,true));
  elsif v_action.tool='ACCESS_ROLE_UPDATE' then
    if not public.workspace_user_is_admin() then raise exception 'FORBIDDEN'; end if; v_target:=(v_action.payload_summary->>'roleId')::uuid;
    if exists(select 1 from public.ruoli where id=v_target and amministratore_workspace) then raise exception 'ADMIN_ROLE_PROTECTED'; end if;
    update public.ai_action_audit set before_snapshot=(select to_jsonb(r) from public.ruoli r where id=v_target) where id=v_action.id;
    update public.ruoli set ambito_dati=coalesce(v_action.payload_summary->>'dataScope',ambito_dati),livello_accesso=coalesce(v_action.payload_summary->>'accessLevel',livello_accesso),livello_ai=coalesce(v_action.payload_summary->>'aiLevel',livello_ai) where id=v_target;
    insert into public.ruoli_moduli(ruolo_id,modulo,livello_accesso) select v_target,x->>'module',x->>'level' from jsonb_array_elements(coalesce(v_action.payload_summary->'moduleLevels','[]'::jsonb))x on conflict(ruolo_id,modulo) do update set livello_accesso=excluded.livello_accesso;
  elsif v_action.tool='ARTICLE_UPDATE' then
    v_target:=(v_action.payload_summary->>'targetId')::uuid; v_changes:=v_action.payload_summary->'changes';
    if exists(select 1 from jsonb_object_keys(v_changes) as allowed_key(key) where allowed_key.key not in ('nome','descrizione','mostra_in_app')) then raise exception 'FIELD_NOT_ALLOWED'; end if;
    update public.ai_action_audit set before_snapshot=(select jsonb_build_object('id',id,'nome',nome,'descrizione',descrizione,'mostra_in_app',mostra_in_app) from public.prodotti where id=v_target) where id=v_action.id;
    update public.prodotti set nome=case when v_changes?'nome' then v_changes->>'nome' else nome end,descrizione=case when v_changes?'descrizione' then v_changes->>'descrizione' else descrizione end,mostra_in_app=case when v_changes?'mostra_in_app' then (v_changes->>'mostra_in_app')::boolean else mostra_in_app end where id=v_target;
  elsif v_action.tool='DOCUMENT_METADATA_UPDATE' then
    v_target:=(v_action.payload_summary->>'targetId')::uuid; v_changes:=v_action.payload_summary->'changes';
    if exists(select 1 from jsonb_object_keys(v_changes) as allowed_key(key) where allowed_key.key not in ('titolo','categoria','marca','gamma','prodotto','parole_chiave','attivo')) then raise exception 'FIELD_NOT_ALLOWED'; end if;
    update public.ai_action_audit set before_snapshot=(select to_jsonb(d) from public.documenti_workspace d where id=v_target) where id=v_action.id;
    update public.documenti_workspace set titolo=case when v_changes?'titolo' then v_changes->>'titolo' else titolo end,categoria=case when v_changes?'categoria' then v_changes->>'categoria' else categoria end,marca=case when v_changes?'marca' then v_changes->>'marca' else marca end,gamma=case when v_changes?'gamma' then v_changes->>'gamma' else gamma end,prodotto=case when v_changes?'prodotto' then v_changes->>'prodotto' else prodotto end,parole_chiave=case when v_changes?'parole_chiave' then array(select jsonb_array_elements_text(v_changes->'parole_chiave')) else parole_chiave end,attivo=case when v_changes?'attivo' then (v_changes->>'attivo')::boolean else attivo end,aggiornato_il=now() where id=v_target;
  else raise exception 'WORKSPACE_TOOL_NOT_IMPLEMENTED'; end if;
  update public.ai_action_audit set status='executed',executed_at=now(),result=jsonb_build_object('changed',true,'tool',tool) where id=v_action.id returning * into v_action; return v_action;
exception when others then
  update public.ai_action_audit set status='failed',error=left(sqlerrm,1000) where id=p_proposal_id returning * into v_action; return v_action;
end $$;

create or replace function public.complete_workspace_external_ai_action(p_proposal_id uuid,p_succeeded boolean,p_result jsonb,p_error text)
returns public.ai_action_audit language plpgsql security definer set search_path=public as $$
declare v_action public.ai_action_audit;
begin
  if auth.role()<>'service_role' then raise exception 'FORBIDDEN'; end if;
  update public.ai_action_audit set status=case when p_succeeded then 'executed' else 'failed' end,executed_at=case when p_succeeded then now() else null end,result=coalesce(p_result,'{}'::jsonb),error=case when p_succeeded then null else left(p_error,1000) end where id=p_proposal_id and system='mes' and status='confirmed' returning * into v_action;
  if v_action.id is null then raise exception 'INVALID_STATE'; end if; return v_action;
end $$;

insert into public.ai_action_registry(code,system,risk_level,input_schema,required_permission,active) values
('UI_CONFIGURE_VIEW','workspace','write','{"type":"object"}'::jsonb,'settings.manage',true),
('ACCESS_ROLE_UPDATE','workspace','write','{"type":"object"}'::jsonb,'settings.manage',true),
('MONITOR_RULE_CREATE','workspace','write','{"type":"object"}'::jsonb,null,true),
('ARTICLE_UPDATE','workspace','write','{"type":"object"}'::jsonb,'products.write',true),
('DOCUMENT_METADATA_UPDATE','workspace','write','{"type":"object"}'::jsonb,'documentation.write',true),
('FORMULA_CREATE_REVISION','mes','write','{"type":"object"}'::jsonb,'progremes.write',true),
('PLANNING_CRITERIA_UPDATE','mes','write','{"type":"object"}'::jsonb,'progremes.write',true),
('RDP_UPDATE','mes','write','{"type":"object"}'::jsonb,'progremes.write',true),
('OP_UPDATE','mes','write','{"type":"object"}'::jsonb,'progremes.write',true),
('LOT_OVERRIDE','mes','destructive','{"type":"object"}'::jsonb,'progremes.write',true),
('LOT_DOCUMENT_LINK','mes','write','{"type":"object"}'::jsonb,'progremes.write',true),
('PURCHASE_PROPOSAL_CREATE','mes','write','{"type":"object"}'::jsonb,'progremes.write',true)
on conflict(code) do update set system=excluded.system,risk_level=excluded.risk_level,required_permission=excluded.required_permission,active=true,updated_at=now();

revoke all on function public.workspace_resolve_builder_layout(text,text),public.workspace_ai_can_propose(),public.workspace_ai_can_confirm(),public.propose_workspace_ai_action(text,jsonb,uuid,uuid,text),public.decide_workspace_ai_action(uuid,boolean),public.complete_workspace_external_ai_action(uuid,boolean,jsonb,text) from public,anon;
grant execute on function public.workspace_resolve_builder_layout(text,text),public.workspace_ai_can_propose(),public.workspace_ai_can_confirm(),public.propose_workspace_ai_action(text,jsonb,uuid,uuid,text),public.decide_workspace_ai_action(uuid,boolean) to authenticated;
grant execute on function public.complete_workspace_external_ai_action(uuid,boolean,jsonb,text) to service_role;

commit;
