-- TEMPORARY diagnostics for the Mexal payment-discount synchronization.
-- Remove this table after the actual discount field has been verified.
create table if not exists public.mexal_sync_debug (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sync_run_id text,
  endpoint text not null,
  payload jsonb,
  error text
);

create index if not exists mexal_sync_debug_created_at_idx
  on public.mexal_sync_debug (created_at desc);

alter table public.mexal_sync_debug enable row level security;

comment on table public.mexal_sync_debug is
  'TEMPORARY: raw Mexal payment-sync WebAPI responses captured for discount-field diagnostics.';
