begin;

create table if not exists public.progremes_moduli (
  codice text primary key,
  nome text not null,
  descrizione text,
  percorso text not null default '/',
  attivo boolean not null default true,
  ordine integer not null default 0,
  prima_sincronizzazione timestamptz not null default now(),
  ultima_sincronizzazione timestamptz not null default now()
);

create table if not exists public.progremes_reparti_moduli (
  reparto_id uuid not null references public.reparti(id) on delete cascade,
  modulo_codice text not null references public.progremes_moduli(codice) on delete cascade,
  creato_il timestamptz not null default now(),
  primary key (reparto_id, modulo_codice)
);

create table if not exists public.progremes_sync_config (
  id smallint primary key default 1 check (id = 1),
  sincronizzazione_automatica boolean not null default true,
  intervallo_ore integer not null default 24 check (intervallo_ore between 1 and 168),
  ultima_esecuzione timestamptz,
  prossima_esecuzione timestamptz,
  aggiornato_il timestamptz not null default now()
);
insert into public.progremes_sync_config(id, prossima_esecuzione)
values (1, now()) on conflict (id) do nothing;

create table if not exists public.progremes_sync_runs (
  id bigint generated by default as identity primary key,
  origine text not null default 'manuale' check (origine in ('manuale','automatica')),
  stato text not null default 'in_coda' check (stato in ('in_coda','in_esecuzione','completata','arrestata','errore')),
  iniziata_il timestamptz not null default now(),
  completata_il timestamptz,
  moduli_letti integer not null default 0,
  inseriti integer not null default 0,
  aggiornati integer not null default 0,
  disattivati integer not null default 0,
  arresto_richiesto boolean not null default false,
  errore text,
  dettagli jsonb not null default '{}'::jsonb
);

alter table public.progremes_moduli enable row level security;
alter table public.progremes_reparti_moduli enable row level security;
alter table public.progremes_sync_config enable row level security;
alter table public.progremes_sync_runs enable row level security;

create policy "authenticated read progremes modules" on public.progremes_moduli for select to authenticated using (true);
create policy "authenticated read progremes department modules" on public.progremes_reparti_moduli for select to authenticated using (true);
create policy "admins manage progremes modules" on public.progremes_moduli for all to authenticated using (public.workspace_user_is_admin()) with check (public.workspace_user_is_admin());
create policy "admins manage progremes department modules" on public.progremes_reparti_moduli for all to authenticated using (public.workspace_user_is_admin()) with check (public.workspace_user_is_admin());
create policy "admins read progremes sync config" on public.progremes_sync_config for select to authenticated using (public.workspace_user_is_admin());
create policy "admins manage progremes sync config" on public.progremes_sync_config for all to authenticated using (public.workspace_user_is_admin()) with check (public.workspace_user_is_admin());
create policy "admins read progremes sync runs" on public.progremes_sync_runs for select to authenticated using (public.workspace_user_is_admin());

grant select on public.progremes_moduli, public.progremes_reparti_moduli to authenticated;
grant select, insert, update, delete on public.progremes_sync_config to authenticated;
grant select on public.progremes_sync_runs to authenticated;

insert into public.permessi(codice, descrizione, modulo)
values ('integrations.sync.progremes_modules', 'Sincronizza il catalogo moduli ProgreMES', 'integrazioni')
on conflict (codice) do update set descrizione=excluded.descrizione, modulo=excluded.modulo;

commit;
