-- Fase 1C.0: OCT inbound, RdP, mirror OP e inbox eventi MES.
-- Tutte le automazioni restano disabilitate a livello applicativo per default.

alter table if exists public.ordini_testate
  add column if not exists origine text not null default 'workspace',
  add column if not exists mexal_sigla text,
  add column if not exists mexal_cod_modulo text,
  add column if not exists mexal_serie integer,
  add column if not exists mexal_numero integer,
  add column if not exists mexal_anno integer,
  add column if not exists mexal_chiave text,
  add column if not exists mexal_cod_conto text,
  add column if not exists mexal_sincronizzato_il timestamptz,
  add column if not exists cliente_mexal_risolto boolean not null default true,
  add column if not exists data_consegna date;

create unique index if not exists ordini_testate_mexal_oct_uniq
  on public.ordini_testate (mexal_sigla, mexal_serie, mexal_numero);

alter table if exists public.ordini_righe
  add column if not exists mexal_posizione integer,
  add column if not exists mexal_tipo_riga text,
  add column if not exists data_consegna date,
  add column if not exists riga_descrittiva boolean not null default false;

create unique index if not exists ordini_righe_oct_posizione_uniq
  on public.ordini_righe (ordine_id, mexal_posizione);

create table if not exists public.workspace_production_requests (
  id uuid primary key default gen_random_uuid(),
  external_id uuid not null unique default gen_random_uuid(),
  ordine_id uuid not null references public.ordini_testate(id) on delete cascade,
  ordine_riga_id uuid not null unique references public.ordini_righe(id) on delete cascade,
  payload_hash text,
  stato text not null default 'NON_INVIATA',
  workspace_status text not null default 'NON_INVIATA',
  attempt_count integer not null default 0,
  last_error_code text,
  last_event_sequence bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_production_proposals (
  id bigint generated by default as identity primary key,
  production_request_id uuid not null references public.workspace_production_requests(id) on delete cascade,
  mes_proposal_id integer not null unique,
  production_index integer not null,
  quantita numeric(18,3) not null,
  stato text not null,
  material_status text not null,
  expected_material_availability date,
  mes_production_order_id integer,
  mes_production_order_number text,
  confirmation_external_id uuid unique,
  confirmation_payload_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (production_request_id, production_index)
);

create table if not exists public.workspace_production_event_inbox (
  event_id uuid primary key,
  external_id uuid not null,
  sequence bigint not null,
  event_type text not null,
  payload_hash text not null,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (external_id, sequence)
);


alter table public.workspace_production_requests enable row level security;
alter table public.workspace_production_proposals enable row level security;
alter table public.workspace_production_event_inbox enable row level security;
revoke all on public.workspace_production_requests from anon, authenticated;
revoke all on public.workspace_production_proposals from anon, authenticated;
revoke all on public.workspace_production_event_inbox from anon, authenticated;
