-- Sprint 3 - invio ordini a Mexal, tracciamento OCM/OCX e retry.

alter table if exists public.ordini_testate
  add column if not exists stato_sincronizzazione text not null default 'non_inviato',
  add column if not exists errore_sincronizzazione text,
  add column if not exists ultimo_tentativo_sync timestamptz,
  add column if not exists sincronizzato_mexal_il timestamptz,
  add column if not exists numero_ocm text,
  add column if not exists numero_ocx text;

create table if not exists public.ordini_sync_mexal_log (
  id bigint generated by default as identity primary key,
  ordine_id uuid not null references public.ordini_testate(id) on delete cascade,
  tipo_documento text not null check (tipo_documento in ('OCM','OCX')),
  stato text not null check (stato in ('successo','errore')),
  payload jsonb not null default '{}'::jsonb,
  risposta jsonb not null default '{}'::jsonb,
  errore text,
  iniziato_il timestamptz not null default now(),
  completato_il timestamptz
);

create index if not exists idx_ordini_sync_mexal_log_ordine
  on public.ordini_sync_mexal_log(ordine_id, iniziato_il desc);

create index if not exists idx_ordini_testate_sync_status
  on public.ordini_testate(stato_sincronizzazione, data_ordine desc);

alter table public.ordini_sync_mexal_log enable row level security;

drop policy if exists "ordini_sync_mexal_log_select_authenticated" on public.ordini_sync_mexal_log;
create policy "ordini_sync_mexal_log_select_authenticated"
on public.ordini_sync_mexal_log
for select to authenticated
using (true);

-- La scrittura dei log avviene esclusivamente dalla API Vercel con service_role.

comment on column public.ordini_testate.stato_sincronizzazione is
  'non_inviato, in_corso, completato oppure errore';
