-- Vercel Hobby esegue un solo cron giornaliero: gli orari legacy non determinano l'avvio.
create table if not exists public.mexal_sync_schedules (
  id bigint generated by default as identity primary key,
  sync_type text not null unique check (sync_type in ('clients','products','commercial_conditions','document_series','stocks','orders')),
  enabled boolean not null default true,
  schedule_mode text not null default 'daily_vercel_hobby',
  batch_size integer,
  execution_order integer not null,
  hour integer, minute integer, frequency_minutes integer, days_of_week text[], next_run_at timestamptz,
  last_run_at timestamptz, last_status text, last_error text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

insert into public.mexal_sync_schedules (sync_type, enabled, schedule_mode, batch_size, execution_order)
values
  ('clients', true, 'daily_vercel_hobby', 100, 1),
  ('products', true, 'daily_vercel_hobby', 12, 2),
  ('commercial_conditions', true, 'daily_vercel_hobby', 100, 3),
  ('document_series', true, 'daily_vercel_hobby', 100, 4),
  ('stocks', true, 'daily_vercel_hobby', 12, 5),
  ('orders', true, 'daily_vercel_hobby', 100, 6)
on conflict (sync_type) do update set execution_order = excluded.execution_order, schedule_mode = excluded.schedule_mode, updated_at = now();
