begin;

create table if not exists public.workspace_builder_layouts (
  target_type text not null check (target_type in ('screen','module','menu')),
  target_code text not null,
  layout jsonb not null default '{"version":1,"blocks":[]}'::jsonb,
  current_version integer not null default 1,
  updated_by uuid references public.utenti(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (target_type,target_code)
);

create table if not exists public.workspace_builder_versions (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('screen','module','menu')),
  target_code text not null,
  version integer not null,
  layout jsonb not null,
  target_name text,
  target_description text,
  created_by uuid references public.utenti(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (target_type,target_code,version)
);

create table if not exists public.workspace_builder_audit_log (
  id bigint generated by default as identity primary key,
  target_type text not null,
  target_code text not null,
  action text not null,
  actor_id uuid references public.utenti(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists workspace_builder_versions_target_idx
  on public.workspace_builder_versions(target_type,target_code,version desc);
create index if not exists workspace_builder_audit_target_idx
  on public.workspace_builder_audit_log(target_type,target_code,created_at desc);

alter table public.workspace_builder_layouts enable row level security;
alter table public.workspace_builder_versions enable row level security;
alter table public.workspace_builder_audit_log enable row level security;

drop policy if exists "authenticated read published workspace layouts" on public.workspace_builder_layouts;
create policy "authenticated read published workspace layouts" on public.workspace_builder_layouts
for select to authenticated using (true);
drop policy if exists "admins manage workspace layouts" on public.workspace_builder_layouts;
create policy "admins manage workspace layouts" on public.workspace_builder_layouts
for all to authenticated using (public.workspace_user_is_admin()) with check (public.workspace_user_is_admin());

drop policy if exists "admins read workspace layout versions" on public.workspace_builder_versions;
create policy "admins read workspace layout versions" on public.workspace_builder_versions
for select to authenticated using (public.workspace_user_is_admin());
drop policy if exists "admins read workspace builder audit" on public.workspace_builder_audit_log;
create policy "admins read workspace builder audit" on public.workspace_builder_audit_log
for select to authenticated using (public.workspace_user_is_admin());

grant select on public.workspace_builder_layouts to authenticated;
grant select on public.workspace_builder_versions, public.workspace_builder_audit_log to authenticated;

create or replace function public.workspace_validate_builder_layout(target_layout jsonb)
returns void language plpgsql immutable set search_path=public as $$
declare target_blocks jsonb;
begin
  if jsonb_typeof(target_layout) <> 'object' then raise exception 'Layout non valido.'; end if;
  target_blocks := target_layout->'blocks';
  if jsonb_typeof(target_blocks) <> 'array' then raise exception 'Il layout deve contenere un elenco di blocchi.'; end if;
  if jsonb_array_length(target_blocks) > 40 then raise exception 'Il layout non può contenere più di 40 blocchi.'; end if;
  if exists (
    select 1 from jsonb_array_elements(target_blocks) block
    where coalesce(block->>'type','') not in ('system-content','text','panel','button','links','divider')
  ) then raise exception 'Il layout contiene un tipo di blocco non consentito.'; end if;
  if exists (
    select block->>'id' from jsonb_array_elements(target_blocks) block
    group by block->>'id' having block->>'id' is null or count(*) > 1
  ) then raise exception 'Ogni blocco deve avere un identificatore univoco.'; end if;
  if exists (
    select 1 from jsonb_array_elements(target_blocks) block
    where block->>'type'='button' and coalesce(block->>'href','') !~ '^(\/|https:\/\/)'
  ) then raise exception 'Destinazione pulsante non consentita.'; end if;
  if exists (
    select 1 from jsonb_array_elements(target_blocks) block
    cross join lateral jsonb_array_elements(coalesce(block->'items','[]'::jsonb)) item
    where block->>'type'='links' and coalesce(item->>'href','') !~ '^(\/|https:\/\/)'
  ) then raise exception 'Destinazione collegamento non consentita.'; end if;
end $$;

create or replace function public.admin_save_workspace_builder_layout(
  p_target_type text,
  p_target_code text,
  p_target_name text,
  p_target_description text,
  p_target_layout jsonb
)
returns integer language plpgsql security definer set search_path=public as $$
declare actor uuid := public.workspace_current_profile_id(); next_version integer;
begin
  if not public.workspace_user_is_admin() then raise exception 'Operazione riservata all''amministratore Workspace.'; end if;
  if p_target_type not in ('screen','module','menu') or btrim(coalesce(p_target_code,''))='' or btrim(coalesce(p_target_name,''))='' then raise exception 'Destinazione non valida.'; end if;
  perform public.workspace_validate_builder_layout(p_target_layout);
  if p_target_type <> 'screen' and not exists (
    select 1 from jsonb_array_elements(p_target_layout->'blocks') block where block->>'type'='system-content'
  ) then raise exception 'Il contenuto applicativo del modulo o menu è obbligatorio.'; end if;

  if p_target_type='screen' then
    if not exists (select 1 from public.workspace_schermate where codice=p_target_code) then raise exception 'Schermata non trovata.'; end if;
    if exists (select 1 from public.workspace_schermate where codice=p_target_code and coalesce(chiave_componente,'')<>'screen-builder')
       and not exists (select 1 from jsonb_array_elements(p_target_layout->'blocks') block where block->>'type'='system-content')
    then raise exception 'Il contenuto applicativo della schermata è obbligatorio.'; end if;
    update public.workspace_schermate set nome=btrim(p_target_name), descrizione=nullif(btrim(p_target_description),''), ultima_sincronizzazione=now() where codice=p_target_code;
  elsif p_target_type='module' then
    if not exists (select 1 from public.workspace_moduli where codice=p_target_code) then raise exception 'Modulo non trovato.'; end if;
    update public.workspace_moduli set nome=btrim(p_target_name), descrizione=nullif(btrim(p_target_description),''), aggiornato_il=now() where codice=p_target_code;
  else
    if not exists (select 1 from public.workspace_menu_voci where codice=p_target_code) then raise exception 'Voce menu non trovata.'; end if;
    update public.workspace_menu_voci set nome=btrim(p_target_name), descrizione=nullif(btrim(p_target_description),''), aggiornata_il=now() where codice=p_target_code;
  end if;

  select coalesce(max(version),0)+1 into next_version from public.workspace_builder_versions where target_type=p_target_type and target_code=p_target_code;
  insert into public.workspace_builder_versions(target_type,target_code,version,layout,target_name,target_description,created_by)
  values(p_target_type,p_target_code,next_version,p_target_layout,btrim(p_target_name),nullif(btrim(p_target_description),''),actor);
  insert into public.workspace_builder_layouts(target_type,target_code,layout,current_version,updated_by,updated_at)
  values(p_target_type,p_target_code,p_target_layout,next_version,actor,now())
  on conflict (target_type,target_code) do update set layout=excluded.layout,current_version=excluded.current_version,updated_by=excluded.updated_by,updated_at=now();
  insert into public.workspace_builder_audit_log(target_type,target_code,action,actor_id,details)
  values(p_target_type,p_target_code,'layout_saved',actor,jsonb_build_object('version',next_version,'blocks',jsonb_array_length(p_target_layout->'blocks')));
  return next_version;
end $$;

create or replace function public.admin_clone_workspace_builder_screen(
  p_source_code text,
  p_new_code text,
  p_new_name text,
  p_new_description text,
  p_target_layout jsonb
)
returns text language plpgsql security definer set search_path=public as $$
declare actor uuid := public.workspace_current_profile_id(); normalized_code text := lower(btrim(p_new_code)); source_screen public.workspace_schermate%rowtype;
begin
  if not public.workspace_user_is_admin() then raise exception 'Operazione riservata all''amministratore Workspace.'; end if;
  if normalized_code !~ '^[a-z0-9_]+$' or btrim(coalesce(p_new_name,''))='' then raise exception 'Codice o nome non valido.'; end if;
  if exists (select 1 from public.workspace_schermate where codice=normalized_code) then raise exception 'Esiste già una schermata con questo codice.'; end if;
  perform public.workspace_validate_builder_layout(p_target_layout);
  select * into source_screen from public.workspace_schermate where codice=p_source_code;
  if not found then raise exception 'Schermata sorgente non trovata.'; end if;
  insert into public.workspace_schermate(codice,nome,descrizione,provider,percorso,chiave_componente,protetta,attiva,ordine,metadati)
  values(normalized_code,btrim(p_new_name),nullif(btrim(p_new_description),''),'workspace','/workspace/schermate/'||normalized_code,'screen-builder',false,true,source_screen.ordine+1,jsonb_build_object('kind','screen-builder','cloned_from',p_source_code));
  insert into public.workspace_moduli_schermate(modulo_codice,schermata_codice,ordine,predefinita,visibile_menu)
  select modulo_codice,normalized_code,ordine+1,false,visibile_menu from public.workspace_moduli_schermate where schermata_codice=p_source_code on conflict do nothing;
  perform public.admin_save_workspace_builder_layout('screen',normalized_code,p_new_name,p_new_description,p_target_layout);
  insert into public.workspace_builder_audit_log(target_type,target_code,action,actor_id,details)
  values('screen',normalized_code,'screen_cloned',actor,jsonb_build_object('source_code',p_source_code));
  return normalized_code;
end $$;

revoke all on function public.workspace_validate_builder_layout(jsonb), public.admin_save_workspace_builder_layout(text,text,text,text,jsonb), public.admin_clone_workspace_builder_screen(text,text,text,text,jsonb) from public, anon;
grant execute on function public.admin_save_workspace_builder_layout(text,text,text,text,jsonb), public.admin_clone_workspace_builder_screen(text,text,text,text,jsonb) to authenticated;

commit;
