create table if not exists public.ordini_serie_documenti (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  sigla_documento text,
  serie text not null,
  descrizione text,
  attiva boolean not null default true,
  dati_mexal jsonb not null default '{}'::jsonb,
  sincronizzata_il timestamptz not null default now()
);

create index if not exists ordini_serie_documenti_sigla_serie_idx
  on public.ordini_serie_documenti(sigla_documento, serie);

create table if not exists public.ordini_configurazione_documenti (
  id integer primary key default 1 check (id = 1),
  serie_ocm text,
  serie_ocx text,
  aggiornato_il timestamptz not null default now()
);

insert into public.ordini_configurazione_documenti(id)
values (1)
on conflict (id) do nothing;

alter table public.ordini_serie_documenti enable row level security;
alter table public.ordini_configurazione_documenti enable row level security;

drop policy if exists "authenticated read order series" on public.ordini_serie_documenti;
create policy "authenticated read order series" on public.ordini_serie_documenti
for select to authenticated using (true);

drop policy if exists "authenticated read order document config" on public.ordini_configurazione_documenti;
create policy "authenticated read order document config" on public.ordini_configurazione_documenti
for select to authenticated using (true);

drop policy if exists "admins manage order document config" on public.ordini_configurazione_documenti;
create policy "admins manage order document config" on public.ordini_configurazione_documenti
for all to authenticated
using (
  exists (
    select 1 from public.utenti u
    left join public.ruoli r on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (coalesce(r.livello,0) >= 80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))
  )
)
with check (
  exists (
    select 1 from public.utenti u
    left join public.ruoli r on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (coalesce(r.livello,0) >= 80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))
  )
);
