begin;

alter table public.crm_external_connections
  add column if not exists provider_code text,
  add column if not exists category text,
  add column if not exists auth_type text,
  add column if not exists sync_attivo boolean not null default false,
  add column if not exists sync_frequency text not null default 'manual',
  add column if not exists is_default boolean not null default false,
  add column if not exists ultimo_test_il timestamptz,
  add column if not exists ultimo_test_stato text,
  add column if not exists ultimo_test_messaggio text,
  add column if not exists errori_consecutivi integer not null default 0 check(errori_consecutivi >= 0),
  add column if not exists oauth_scade_il timestamptz,
  add column if not exists webhook_path text,
  add column if not exists webhook_stato text not null default 'non_configurato',
  add column if not exists ultimo_webhook_il timestamptz,
  add column if not exists disabilitata_il timestamptz,
  add column if not exists aggiornata_da uuid references public.utenti(id) on delete set null;

alter table public.crm_external_connections drop constraint if exists crm_external_connections_stato_check;
alter table public.crm_external_connections add constraint crm_external_connections_stato_check
  check(stato in (
    'non_configurato','configurazione_parziale','pronto','configurato',
    'da_verificare','connesso','errore','disabilitato','oauth_scaduto',
    'sincronizzazione_in_corso'
  ));
alter table public.crm_external_connections drop constraint if exists crm_external_connections_sync_frequency_check;
alter table public.crm_external_connections add constraint crm_external_connections_sync_frequency_check
  check(sync_frequency in ('manual','daily'));
alter table public.crm_external_connections drop constraint if exists crm_external_connections_last_test_check;
alter table public.crm_external_connections add constraint crm_external_connections_last_test_check
  check(ultimo_test_stato is null or ultimo_test_stato in ('success','failed','insufficient_scope','expired','unreachable'));
alter table public.crm_external_connections drop constraint if exists crm_external_connections_webhook_status_check;
alter table public.crm_external_connections add constraint crm_external_connections_webhook_status_check
  check(webhook_stato in ('non_configurato','configurato','attivo','errore','disabilitato'));

create unique index if not exists crm_external_connections_default_category_idx
  on public.crm_external_connections(category) where is_default and abilitata;
create index if not exists crm_external_connections_schedule_idx
  on public.crm_external_connections(sync_attivo,prossima_run_il) where abilitata;

create table if not exists public.crm_connection_secrets (
  connection_id uuid not null references public.crm_external_connections(id) on delete cascade,
  secret_name text not null,
  ciphertext text not null,
  iv text not null,
  auth_tag text not null,
  key_version integer not null default 1,
  fingerprint text not null,
  aggiornata_da uuid references public.utenti(id) on delete set null,
  creata_il timestamptz not null default now(),
  aggiornata_il timestamptz not null default now(),
  primary key(connection_id,secret_name),
  check(secret_name ~ '^[a-z][a-z0-9_]{1,63}$')
);
comment on table public.crm_connection_secrets is
  'Segreti cifrati AES-256-GCM. Nessun grant frontend; accesso esclusivo service_role.';

create table if not exists public.crm_connection_oauth_states (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null references public.crm_external_connections(id) on delete cascade,
  provider_code text not null,
  state_hash text not null unique,
  verifier_ciphertext text,
  verifier_iv text,
  verifier_auth_tag text,
  redirect_path text not null default '/settings/crm-digital',
  created_by uuid references public.utenti(id) on delete set null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists crm_connection_oauth_states_expiry_idx
  on public.crm_connection_oauth_states(expires_at) where consumed_at is null;

create table if not exists public.crm_connection_audit (
  id bigint generated by default as identity primary key,
  connection_id uuid references public.crm_external_connections(id) on delete set null,
  provider_code text,
  operation text not null,
  actor_id uuid references public.utenti(id) on delete set null,
  outcome text not null default 'success' check(outcome in ('success','failed')),
  details jsonb not null default '{}',
  created_at timestamptz not null default now(),
  check(details::text !~* '(access[_-]?token|refresh[_-]?token|api[_-]?key|client[_-]?secret|password|authorization|webhook[_-]?secret)')
);
create index if not exists crm_connection_audit_connection_idx
  on public.crm_connection_audit(connection_id,created_at desc);

alter table public.crm_connection_secrets enable row level security;
alter table public.crm_connection_oauth_states enable row level security;
alter table public.crm_connection_audit enable row level security;

revoke all on public.crm_connection_secrets from public,anon,authenticated;
revoke all on public.crm_connection_oauth_states from public,anon,authenticated;
revoke all on public.crm_connection_audit from public,anon,authenticated;
grant select on public.crm_connection_audit to authenticated;
grant usage,select on sequence public.crm_connection_audit_id_seq to service_role;
grant select,insert,update,delete on public.crm_connection_secrets,public.crm_connection_oauth_states to service_role;
grant select,insert,update,delete on public.crm_connection_audit to service_role;

create or replace function public.crm_can_view_connection_manager()
returns boolean language sql stable security definer set search_path=public as $$
  with me as (
    select u.id,coalesce(r.amministratore_workspace,false) admin,
      coalesce(r.livello_accesso,'lettura') role_level
    from public.utenti u left join public.ruoli r on r.id=u.ruolo_id
    where u.auth_user_id=auth.uid() and u.attivo is not false limit 1
  )
  select coalesce((select admin or role_level='amministrazione' or exists(
    select 1 from public.permessi_utente pu
    join public.permessi p on p.id=pu.permesso_id
    where pu.utente_id=me.id and p.codice='integrations.configure'
  ) from me),false)
$$;
revoke all on function public.crm_can_view_connection_manager() from public,anon;
grant execute on function public.crm_can_view_connection_manager() to authenticated,service_role;

drop policy if exists "digital connection admin read" on public.crm_external_connections;
drop policy if exists "digital connection manager read" on public.crm_external_connections;
create policy "digital connection manager read" on public.crm_external_connections
  for select to authenticated using(
    public.crm_can_view_connection_manager()
    or public.crm_has_module_level(public.crm_digital_module_for_connection(tipo),'lettura')
  );

drop policy if exists "digital connection audit read" on public.crm_connection_audit;
create policy "digital connection audit read" on public.crm_connection_audit
  for select to authenticated using(public.crm_can_view_connection_manager());

create or replace function public.crm_claim_sync_run_service(
  target_connection_id uuid,
  target_sync_type text,
  target_mode text,
  target_idempotency_key text,
  target_triggered_by uuid default null
) returns uuid language plpgsql security definer set search_path=public as $$
declare run_id uuid; connection_enabled boolean;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Operazione riservata al servizio Digital.' using errcode='42501';
  end if;
  select abilitata into connection_enabled
  from public.crm_external_connections where id=target_connection_id for update;
  if connection_enabled is null then raise exception 'Connessione non trovata.'; end if;
  if not connection_enabled then raise exception 'Connessione o sincronizzazione disattivata.'; end if;
  insert into public.crm_sync_runs(
    connection_id,sync_type,mode,status,idempotency_key,started_at,heartbeat_at,triggered_by
  ) values(
    target_connection_id,target_sync_type,coalesce(target_mode,'incremental'),
    'running',target_idempotency_key,now(),now(),target_triggered_by
  ) returning id into run_id;
  update public.crm_external_connections
    set stato='sincronizzazione_in_corso',aggiornata_il=now()
    where id=target_connection_id;
  return run_id;
exception when unique_violation then
  raise exception 'Sincronizzazione dello stesso tipo gia in corso.' using errcode='55P03';
end $$;
revoke all on function public.crm_claim_sync_run_service(uuid,text,text,text,uuid) from public,anon,authenticated;
grant execute on function public.crm_claim_sync_run_service(uuid,text,text,text,uuid) to service_role;

create or replace function public.crm_complete_sync_run_service(
  target_run_id uuid,
  target_status text,
  target_counts jsonb default '{}',
  target_error_code text default null,
  target_error_message text default null,
  target_details jsonb default '{}'
) returns void language plpgsql security definer set search_path=public as $$
declare target_connection uuid;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Operazione riservata al servizio Digital.' using errcode='42501';
  end if;
  if target_status not in ('completed','partial','failed','cancelled') then
    raise exception 'Stato finale non valido.';
  end if;
  update public.crm_sync_runs set
    status=target_status,
    completed_at=now(),
    heartbeat_at=now(),
    duration_ms=greatest(0,extract(epoch from (now()-started_at))*1000)::bigint,
    records_read=coalesce((target_counts->>'read')::integer,records_read),
    records_inserted=coalesce((target_counts->>'inserted')::integer,records_inserted),
    records_updated=coalesce((target_counts->>'updated')::integer,records_updated),
    records_failed=coalesce((target_counts->>'failed')::integer,records_failed),
    error_code=target_error_code,
    error_message=left(target_error_message,500),
    details=coalesce(target_details,'{}')
  where id=target_run_id returning connection_id into target_connection;
  update public.crm_external_connections set
    stato=case when target_status='failed' then 'errore' else 'connesso' end,
    ultimo_sync_il=case when target_status in ('completed','partial') then now() else ultimo_sync_il end,
    ultimo_errore=case when target_status='failed' then left(target_error_message,500) else null end,
    prossima_run_il=case when sync_attivo and sync_frequency='daily' then now()+interval '1 day' else null end,
    aggiornata_il=now()
  where id=target_connection;
end $$;
revoke all on function public.crm_complete_sync_run_service(uuid,text,jsonb,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.crm_complete_sync_run_service(uuid,text,jsonb,text,text,jsonb) to service_role;

-- Le due schermate esistono gia nella fondazione Digital: riallineamento idempotente.
update public.workspace_schermate set attiva=true,percorso='/settings/crm-digital',
  metadati=metadati||'{"admin_only":true}'::jsonb,ultima_sincronizzazione=now()
where codice='impostazioni.crm_digital';
update public.workspace_schermate set attiva=true,percorso='/integrations/crm-digital',
  metadati=metadati||'{"required_permissions":["integrations.configure"]}'::jsonb,ultima_sincronizzazione=now()
where codice='integrazioni.crm_digital';

commit;
