-- WorkspaceMES V3. Schema additivo, disabilitato per default e senza backfill storico.
-- V1/V2 restano invariati; tutte le mutazioni V3 passano da RPC service-role fail-closed.

create table if not exists public.workspace_finished_bom_revisions (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  finished_article_code text not null,
  revision integer not null check (revision > 0),
  source text not null default 'MEXAL',
  source_hash text not null,
  base_quantity numeric(18,6) not null default 1 check (base_quantity > 0),
  unit_of_measure text not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  is_current boolean not null default true,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (finished_article_code, revision),
  check (effective_to is null or effective_to >= effective_from)
);

create unique index if not exists workspace_finished_bom_current_uniq
  on public.workspace_finished_bom_revisions (finished_article_code) where is_current;

create table if not exists public.workspace_finished_bom_lines (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  revision_id bigint not null references public.workspace_finished_bom_revisions(id) on delete restrict,
  line_number integer not null check (line_number > 0),
  source_line_key text not null,
  article_code text not null,
  description text,
  quantity numeric(18,6) not null check (quantity > 0),
  unit_of_measure text not null,
  component_kind text not null check (component_kind in ('DIRECT_COMPONENT','FORMULA_COMPONENT')),
  classification_source text not null,
  formula_external_ref text,
  source_unit_type text,
  is_removed boolean not null default false,
  removed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  unique (revision_id, line_number),
  unique (revision_id, source_line_key)
);

create table if not exists public.workspace_supplier_order_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_hash text not null unique,
  source_endpoint text not null default 'documenti/ordini-fornitori',
  captured_at timestamptz not null default now(),
  orders_count integer not null default 0,
  lines_count integer not null default 0,
  source_payload jsonb not null default '{}'::jsonb
);

create table if not exists public.workspace_supplier_order_snapshot_lines (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.workspace_supplier_order_snapshots(id) on delete restrict,
  order_external_key text not null,
  line_external_key text not null,
  supplier_code text not null,
  supplier_name text,
  article_code text not null,
  description text,
  unit_of_measure text not null,
  ordered_quantity numeric(18,6) not null check (ordered_quantity > 0),
  received_quantity numeric(18,6) not null default 0 check (received_quantity >= 0),
  remaining_quantity numeric(18,6) not null check (remaining_quantity >= 0),
  expected_at timestamptz,
  order_date date,
  order_status text not null default 'OPEN',
  active boolean not null default true,
  receipt_semantics text not null default 'NOT_EXPOSED_BY_MEXAL_ENDPOINT',
  source_payload jsonb not null default '{}'::jsonb,
  unique(snapshot_id,line_external_key)
);

create index if not exists workspace_supplier_snapshot_captured_idx
  on public.workspace_supplier_order_snapshots(captured_at desc);
create index if not exists workspace_supplier_lines_netting_idx
  on public.workspace_supplier_order_snapshot_lines(snapshot_id,article_code,active,expected_at);

create table if not exists public.workspace_v3_previews (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  production_request_id uuid references public.workspace_production_requests(id) on delete restrict,
  contract_version integer not null default 3 check (contract_version = 3),
  preview_hash text not null unique,
  idempotency_key text not null unique,
  payload_hash text not null,
  status text not null check (status in ('BUILDING','READY','BLOCKED','STALE','CONFIRMING','CONFIRMED','RECOVERY_REQUIRED','CANCELLED')),
  oct_revision integer not null check (oct_revision > 0),
  oct_hash text not null,
  bom_revision_id bigint references public.workspace_finished_bom_revisions(id) on delete restrict,
  bom_hash text not null,
  availability_version text not null,
  snapshot jsonb not null,
  correlation_id uuid not null,
  causation_id uuid,
  requested_by uuid,
  row_version bigint not null default 1,
  captured_at timestamptz not null default now(),
  invalidated_at timestamptz,
  confirmed_at timestamptz
);

create table if not exists public.workspace_v3_preview_sources (
  id bigint generated by default as identity primary key,
  preview_id bigint not null references public.workspace_v3_previews(id) on delete restrict,
  order_id uuid not null references public.ordini_testate(id) on delete restrict,
  order_line_id uuid not null references public.ordini_righe(id) on delete restrict,
  bom_revision_id bigint not null references public.workspace_finished_bom_revisions(id) on delete restrict,
  finished_article_code text not null,
  finished_quantity numeric(18,6) not null check(finished_quantity>0),
  unit_of_measure text not null,
  oct_revision integer not null,
  oct_hash text not null,
  bom_hash text not null,
  unique(preview_id,order_line_id)
);

create table if not exists public.workspace_v3_preview_components (
  id bigint generated by default as identity primary key,
  preview_id bigint not null references public.workspace_v3_previews(id) on delete restrict,
  bom_line_id bigint not null references public.workspace_finished_bom_lines(id) on delete restrict,
  component_kind text not null check (component_kind in ('DIRECT_COMPONENT','FORMULA_COMPONENT','FORMULA_MATERIAL')),
  parent_component_id bigint references public.workspace_v3_preview_components(id) on delete restrict,
  article_code text not null,
  unit_of_measure text not null,
  required_quantity numeric(18,6) not null check (required_quantity >= 0),
  on_hand_quantity numeric(18,6) not null default 0,
  committed_quantity numeric(18,6) not null default 0,
  incoming_quantity numeric(18,6) not null default 0,
  uncovered_quantity numeric(18,6) not null default 0,
  required_at timestamptz,
  expected_available_at timestamptz,
  calculation_owner text not null check (calculation_owner in ('WORKSPACE','PROGREMES')),
  formula_code text,
  formula_revision integer,
  formula_snapshot_hash text,
  batch text,
  station text,
  filling text,
  blocker_code text,
  certified_payload jsonb not null default '{}'::jsonb,
  unique (preview_id, component_kind, article_code, bom_line_id, parent_component_id)
);

create table if not exists public.workspace_v3_confirmation_sagas (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique,
  preview_id bigint not null references public.workspace_v3_previews(id) on delete restrict,
  idempotency_key text not null unique,
  payload_hash text not null,
  status text not null check (status in ('PENDING_MES','MES_CONFIRMED','MATERIALIZING_WORKSPACE','COMPLETED','RECOVERY_REQUIRED','COMPENSATION_REQUIRED','CANCELLED')),
  mes_confirmation_id uuid,
  mes_production_order_id integer,
  mes_production_order_number text,
  last_error_code text,
  correlation_id uuid not null,
  causation_id uuid,
  row_version bigint not null default 1,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.workspace_v3_material_commitments (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  saga_id bigint not null references public.workspace_v3_confirmation_sagas(id) on delete restrict,
  preview_component_id bigint not null references public.workspace_v3_preview_components(id) on delete restrict,
  owner text not null check (owner in ('WORKSPACE_DIRECT','PROGREMES_MP_CERTIFIED')),
  article_code text not null,
  unit_of_measure text not null,
  quantity numeric(18,6) not null check (quantity > 0),
  source_commitment_id text,
  status text not null check (status in ('ACTIVE','RELEASED','COMPENSATION_REQUIRED')),
  committed_at timestamptz not null default now(),
  released_at timestamptz,
  unique (saga_id, preview_component_id, owner)
);

create table if not exists public.workspace_v3_purchase_requirements (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  saga_id bigint not null references public.workspace_v3_confirmation_sagas(id) on delete restrict,
  commitment_id bigint not null references public.workspace_v3_material_commitments(id) on delete restrict,
  article_code text not null,
  unit_of_measure text not null,
  required_quantity numeric(18,6) not null check (required_quantity > 0),
  required_at timestamptz,
  status text not null check (status in ('OPEN','IN_PROPOSAL','IN_RFQ','QUOTED','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
  lineage jsonb not null,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (saga_id, commitment_id)
);

create table if not exists public.workspace_v3_purchase_documents (
  id bigint generated by default as identity primary key,
  external_id uuid not null unique default gen_random_uuid(),
  document_type text not null check (document_type in ('PROPOSAL','RFQ','QUOTE','SUPPLIER_ORDER')),
  parent_document_id bigint references public.workspace_v3_purchase_documents(id) on delete restrict,
  supplier_external_ref text,
  status text not null,
  document_number text,
  currency text,
  valid_until date,
  mexal_external_ref text,
  payload_hash text not null,
  idempotency_key text not null unique,
  correlation_id uuid not null,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_v3_purchase_document_lines (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.workspace_v3_purchase_documents(id) on delete restrict,
  requirement_id bigint not null references public.workspace_v3_purchase_requirements(id) on delete restrict,
  quantity numeric(18,6) not null check (quantity > 0),
  unit_price numeric(18,6),
  expected_at timestamptz,
  received_quantity numeric(18,6) not null default 0 check (received_quantity >= 0),
  unique (document_id, requirement_id)
);

create table if not exists public.workspace_v3_outbox (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique default gen_random_uuid(),
  aggregate_type text not null,
  aggregate_id text not null,
  destination text not null check (destination in ('PROGREMES','MEXAL','WORKSPACE')),
  event_type text not null,
  sequence bigint not null,
  payload jsonb not null,
  payload_hash text not null,
  correlation_id uuid not null,
  causation_id uuid,
  attempt_count integer not null default 0,
  next_attempt_at timestamptz,
  lease_token uuid,
  lease_expires_at timestamptz,
  delivered_at timestamptz,
  dead_lettered_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  unique (aggregate_type, aggregate_id, destination, sequence)
);

create table if not exists public.workspace_v3_audit (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique default gen_random_uuid(),
  aggregate_type text not null,
  aggregate_id text not null,
  action text not null,
  actor_id text not null,
  before_hash text,
  after_hash text,
  payload jsonb not null default '{}'::jsonb,
  correlation_id uuid not null,
  causation_id uuid,
  occurred_at timestamptz not null default now()
);

create table if not exists public.workspace_v3_feature_flags (
  key text primary key,
  enabled boolean not null default false,
  description text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

insert into public.workspace_v3_feature_flags(key, enabled, description) values
  ('workspacemes.v3.preview', false, 'Abilita preview V3 senza effetti produttivi.'),
  ('workspacemes.v3.confirm', false, 'Abilita saga di conferma V3 e materializzazione impegni/fabbisogni.'),
  ('workspacemes.v3.purchasing', false, 'Abilita il workflow acquisti V3 fino alla preparazione ordine fornitore, senza invio Mexal.'),
  ('legacy.sync.oct', true, 'Sincronizzazione legacy OCT Mexal verso MES.'),
  ('legacy.sync.articles', true, 'Sincronizzazione legacy articoli Mexal verso MES.'),
  ('legacy.sync.customers', true, 'Sincronizzazione legacy clienti Mexal verso MES.'),
  ('legacy.sync.suppliers', true, 'Sincronizzazione legacy fornitori Mexal verso MES.'),
  ('legacy.sync.stocks', true, 'Sincronizzazione legacy giacenze Mexal verso MES.'),
  ('legacy.sync.supplier_orders', true, 'Sincronizzazione legacy ordini fornitori Mexal verso MES.'),
  ('legacy.sync.finished_bom', true, 'Sincronizzazione legacy distinta prodotto finito Mexal verso MES.'),
  ('legacy.sync.fp_formulas', true, 'Sincronizzazione legacy formule FP Mexal verso MES.')
on conflict (key) do nothing;

insert into public.permessi(codice,descrizione,modulo)
values ('purchases.manage','Gestisce proposta, RdO, preventivo e ordine fornitore WorkspaceMES V3','progremes')
on conflict (codice) do update set descrizione=excluded.descrizione,modulo=excluded.modulo;

create index if not exists workspace_v3_outbox_pending_idx on public.workspace_v3_outbox(next_attempt_at, id)
  where delivered_at is null and dead_lettered_at is null;
create index if not exists workspace_v3_requirements_status_idx on public.workspace_v3_purchase_requirements(status, required_at);
create index if not exists workspace_v3_components_article_idx on public.workspace_v3_preview_components(article_code, component_kind);

alter table public.workspace_finished_bom_revisions enable row level security;
alter table public.workspace_finished_bom_lines enable row level security;
alter table public.workspace_supplier_order_snapshots enable row level security;
alter table public.workspace_supplier_order_snapshot_lines enable row level security;
alter table public.workspace_v3_previews enable row level security;
alter table public.workspace_v3_preview_sources enable row level security;
alter table public.workspace_v3_preview_components enable row level security;
alter table public.workspace_v3_confirmation_sagas enable row level security;
alter table public.workspace_v3_material_commitments enable row level security;
alter table public.workspace_v3_purchase_requirements enable row level security;
alter table public.workspace_v3_purchase_documents enable row level security;
alter table public.workspace_v3_purchase_document_lines enable row level security;
alter table public.workspace_v3_outbox enable row level security;
alter table public.workspace_v3_audit enable row level security;
alter table public.workspace_v3_feature_flags enable row level security;

revoke all on public.workspace_finished_bom_revisions, public.workspace_finished_bom_lines,
  public.workspace_supplier_order_snapshots, public.workspace_supplier_order_snapshot_lines,
  public.workspace_v3_previews, public.workspace_v3_preview_sources, public.workspace_v3_preview_components,
  public.workspace_v3_confirmation_sagas, public.workspace_v3_material_commitments,
  public.workspace_v3_purchase_requirements, public.workspace_v3_purchase_documents,
  public.workspace_v3_purchase_document_lines, public.workspace_v3_outbox,
  public.workspace_v3_audit, public.workspace_v3_feature_flags from anon, authenticated;
grant select, insert, update on public.workspace_finished_bom_revisions, public.workspace_finished_bom_lines,
  public.workspace_supplier_order_snapshots, public.workspace_supplier_order_snapshot_lines,
  public.workspace_v3_previews, public.workspace_v3_preview_sources, public.workspace_v3_preview_components,
  public.workspace_v3_confirmation_sagas, public.workspace_v3_material_commitments,
  public.workspace_v3_purchase_requirements, public.workspace_v3_purchase_documents,
  public.workspace_v3_purchase_document_lines, public.workspace_v3_outbox,
  public.workspace_v3_audit, public.workspace_v3_feature_flags to service_role;

create or replace function public.apply_workspace_finished_bom_snapshot(
  p_finished_article_code text,
  p_source_hash text,
  p_unit_of_measure text,
  p_base_quantity numeric,
  p_source_payload jsonb,
  p_lines jsonb,
  p_captured_at timestamptz
) returns table(revision_id bigint, revision integer, changed boolean)
language plpgsql security definer set search_path=public as $$
declare
  v_previous public.workspace_finished_bom_revisions%rowtype;
  v_revision public.workspace_finished_bom_revisions%rowtype;
  v_line jsonb;
  v_number integer := 0;
begin
  if nullif(trim(p_finished_article_code),'') is null or nullif(trim(p_source_hash),'') is null or
     nullif(trim(p_unit_of_measure),'') is null or p_base_quantity <= 0 or jsonb_typeof(p_lines) <> 'array'
  then raise exception 'INVALID_FINISHED_BOM_SNAPSHOT'; end if;

  perform pg_advisory_xact_lock(hashtextextended(upper(trim(p_finished_article_code)),0));
  select * into v_previous from public.workspace_finished_bom_revisions
   where finished_article_code=upper(trim(p_finished_article_code)) and is_current for update;
  if found and v_previous.source_hash=p_source_hash then
    return query select v_previous.id,v_previous.revision,false;
    return;
  end if;

  if found then
    update public.workspace_finished_bom_revisions
       set is_current=false,effective_to=p_captured_at
     where id=v_previous.id;
  end if;

  insert into public.workspace_finished_bom_revisions(
    finished_article_code,revision,source,source_hash,base_quantity,unit_of_measure,
    effective_from,is_current,source_payload)
  values(upper(trim(p_finished_article_code)),coalesce(v_previous.revision,0)+1,'MEXAL',p_source_hash,
    p_base_quantity,upper(trim(p_unit_of_measure)),p_captured_at,true,coalesce(p_source_payload,'{}'::jsonb))
  returning * into v_revision;

  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_number := v_number+1;
    insert into public.workspace_finished_bom_lines(
      revision_id,line_number,source_line_key,article_code,description,quantity,unit_of_measure,
      component_kind,classification_source,formula_external_ref,source_unit_type,is_removed,metadata)
    values(v_revision.id,v_number,v_line->>'sourceLineKey',upper(v_line->>'articleCode'),v_line->>'description',
      (v_line->>'quantity')::numeric,upper(v_line->>'unitOfMeasure'),v_line->>'componentKind',
      v_line->>'classificationSource',nullif(v_line->>'formulaExternalRef',''),nullif(v_line->>'sourceUnitType',''),
      false,coalesce(v_line->'metadata','{}'::jsonb));
  end loop;

  if v_previous.id is not null then
    insert into public.workspace_finished_bom_lines(
      revision_id,line_number,source_line_key,article_code,description,quantity,unit_of_measure,
      component_kind,classification_source,formula_external_ref,source_unit_type,is_removed,removed_at,metadata)
    select v_revision.id,v_number+row_number() over(order by old_line.line_number),old_line.source_line_key,
      old_line.article_code,old_line.description,old_line.quantity,old_line.unit_of_measure,old_line.component_kind,
      old_line.classification_source,old_line.formula_external_ref,old_line.source_unit_type,true,p_captured_at,
      old_line.metadata||jsonb_build_object('removedFromRevision',v_previous.revision)
    from public.workspace_finished_bom_lines old_line
    where old_line.revision_id=v_previous.id and not old_line.is_removed
      and not exists(select 1 from jsonb_array_elements(p_lines) fresh where fresh->>'sourceLineKey'=old_line.source_line_key);
  end if;

  return query select v_revision.id,v_revision.revision,true;
end $$;

create or replace function public.apply_workspace_supplier_order_snapshot(
  p_snapshot_hash text,
  p_source_payload jsonb,
  p_lines jsonb,
  p_captured_at timestamptz
) returns table(snapshot_id bigint, changed boolean)
language plpgsql security definer set search_path=public as $$
declare v_snapshot_id bigint;
begin
  if nullif(trim(p_snapshot_hash),'') is null or jsonb_typeof(p_lines)<>'array'
  then raise exception 'INVALID_SUPPLIER_ORDER_SNAPSHOT'; end if;
  select id into v_snapshot_id from public.workspace_supplier_order_snapshots where snapshot_hash=p_snapshot_hash;
  if found then return query select v_snapshot_id,false; return; end if;

  insert into public.workspace_supplier_order_snapshots(snapshot_hash,captured_at,orders_count,lines_count,source_payload)
  values(p_snapshot_hash,p_captured_at,(select count(distinct value->>'orderExternalKey') from jsonb_array_elements(p_lines)),
    jsonb_array_length(p_lines),coalesce(p_source_payload,'{}'::jsonb)) returning id into v_snapshot_id;

  insert into public.workspace_supplier_order_snapshot_lines(
    snapshot_id,order_external_key,line_external_key,supplier_code,supplier_name,article_code,description,
    unit_of_measure,ordered_quantity,received_quantity,remaining_quantity,expected_at,order_date,
    order_status,active,receipt_semantics,source_payload)
  select v_snapshot_id,x.order_external_key,x.line_external_key,x.supplier_code,x.supplier_name,x.article_code,
    x.description,x.unit_of_measure,x.ordered_quantity,0,x.ordered_quantity,x.expected_at,x.order_date,
    'OPEN',true,'NOT_EXPOSED_BY_MEXAL_ENDPOINT',x.source_payload
  from jsonb_to_recordset(p_lines) as x(order_external_key text,line_external_key text,supplier_code text,
    supplier_name text,article_code text,description text,unit_of_measure text,ordered_quantity numeric,
    expected_at timestamptz,order_date date,source_payload jsonb);
  return query select v_snapshot_id,true;
end $$;

create or replace function public.persist_workspace_v3_preview(
  p_external_id uuid,
  p_production_request_id uuid,
  p_preview_hash text,
  p_idempotency_key text,
  p_payload_hash text,
  p_status text,
  p_oct_revision integer,
  p_oct_hash text,
  p_bom_hash text,
  p_availability_version text,
  p_snapshot jsonb,
  p_correlation_id uuid,
  p_causation_id uuid,
  p_requested_by uuid,
  p_sources jsonb,
  p_components jsonb
) returns table(preview_id bigint,status text,row_version bigint,created boolean)
language plpgsql security definer set search_path=public as $$
declare
  v_preview public.workspace_v3_previews%rowtype;
  v_item jsonb;
  v_parent_id bigint;
begin
  select * into v_preview from public.workspace_v3_previews where idempotency_key=p_idempotency_key;
  if found then
    if v_preview.payload_hash<>p_payload_hash then raise exception 'V3_PREVIEW_IDEMPOTENCY_CONFLICT'; end if;
    return query select v_preview.id,v_preview.status,v_preview.row_version,false;
    return;
  end if;
  if p_status not in ('READY','BLOCKED') or jsonb_typeof(p_sources)<>'array' or jsonb_typeof(p_components)<>'array'
  then raise exception 'INVALID_V3_PREVIEW'; end if;

  insert into public.workspace_v3_previews(external_id,production_request_id,preview_hash,idempotency_key,payload_hash,
    status,oct_revision,oct_hash,bom_hash,availability_version,snapshot,correlation_id,causation_id,requested_by)
  values(p_external_id,p_production_request_id,p_preview_hash,p_idempotency_key,p_payload_hash,p_status,p_oct_revision,
    p_oct_hash,p_bom_hash,p_availability_version,p_snapshot,p_correlation_id,p_causation_id,p_requested_by)
  returning * into v_preview;

  insert into public.workspace_v3_preview_sources(preview_id,order_id,order_line_id,bom_revision_id,
    finished_article_code,finished_quantity,unit_of_measure,oct_revision,oct_hash,bom_hash)
  select v_preview.id,x.order_id,x.order_line_id,x.bom_revision_id,x.finished_article_code,x.finished_quantity,
    x.unit_of_measure,x.oct_revision,x.oct_hash,x.bom_hash
  from jsonb_to_recordset(p_sources) as x(order_id uuid,order_line_id uuid,bom_revision_id bigint,
    finished_article_code text,finished_quantity numeric,unit_of_measure text,oct_revision integer,oct_hash text,bom_hash text);

  for v_item in select value from jsonb_array_elements(p_components)
    where value->>'componentKind'<>'FORMULA_MATERIAL'
  loop
    insert into public.workspace_v3_preview_components(preview_id,bom_line_id,component_kind,article_code,
      unit_of_measure,required_quantity,on_hand_quantity,committed_quantity,incoming_quantity,uncovered_quantity,
      required_at,expected_available_at,calculation_owner,formula_code,formula_revision,formula_snapshot_hash,batch,station,
      filling,blocker_code,certified_payload)
    values(v_preview.id,(v_item->>'bomLineId')::bigint,v_item->>'componentKind',upper(v_item->>'articleCode'),
      upper(v_item->>'unitOfMeasure'),(v_item->>'requiredQuantity')::numeric,coalesce((v_item->>'onHandQuantity')::numeric,0),
      coalesce((v_item->>'committedQuantity')::numeric,0),coalesce((v_item->>'incomingQuantity')::numeric,0),
      coalesce((v_item->>'uncoveredQuantity')::numeric,0),(v_item->>'requiredAt')::timestamptz,(v_item->>'expectedAvailableAt')::timestamptz,
      v_item->>'calculationOwner',nullif(v_item->>'formulaCode',''),nullif((v_item->>'formulaRevision')::integer,0),
      nullif(v_item->>'formulaSnapshotHash',''),nullif(v_item->>'batch',''),nullif(v_item->>'station',''),
      nullif(v_item->>'filling',''),nullif(v_item->>'blockerCode',''),coalesce(v_item->'certifiedPayload','{}'::jsonb));
  end loop;

  for v_item in select value from jsonb_array_elements(p_components)
    where value->>'componentKind'='FORMULA_MATERIAL'
  loop
    select id into v_parent_id from public.workspace_v3_preview_components
      where preview_id=v_preview.id and component_kind='FORMULA_COMPONENT'
        and bom_line_id=(v_item->>'bomLineId')::bigint and article_code=upper(v_item->>'parentArticleCode');
    if v_parent_id is null then raise exception 'V3_FORMULA_PARENT_NOT_FOUND'; end if;
    insert into public.workspace_v3_preview_components(preview_id,bom_line_id,component_kind,parent_component_id,
      article_code,unit_of_measure,required_quantity,on_hand_quantity,committed_quantity,incoming_quantity,
      uncovered_quantity,required_at,expected_available_at,calculation_owner,formula_code,formula_revision,
      formula_snapshot_hash,batch,station,filling,blocker_code,certified_payload)
    values(v_preview.id,(v_item->>'bomLineId')::bigint,'FORMULA_MATERIAL',v_parent_id,upper(v_item->>'articleCode'),
      upper(v_item->>'unitOfMeasure'),(v_item->>'requiredQuantity')::numeric,coalesce((v_item->>'onHandQuantity')::numeric,0),
      coalesce((v_item->>'committedQuantity')::numeric,0),coalesce((v_item->>'incomingQuantity')::numeric,0),
      coalesce((v_item->>'uncoveredQuantity')::numeric,0),(v_item->>'requiredAt')::timestamptz,(v_item->>'expectedAvailableAt')::timestamptz,'PROGREMES',
      nullif(v_item->>'formulaCode',''),nullif((v_item->>'formulaRevision')::integer,0),
      nullif(v_item->>'formulaSnapshotHash',''),nullif(v_item->>'batch',''),nullif(v_item->>'station',''),
      nullif(v_item->>'filling',''),nullif(v_item->>'blockerCode',''),coalesce(v_item->'certifiedPayload','{}'::jsonb));
  end loop;

  insert into public.workspace_v3_audit(aggregate_type,aggregate_id,action,actor_id,after_hash,payload,correlation_id,causation_id)
  values('V3_PREVIEW',v_preview.id::text,'PREVIEW_CAPTURED',coalesce(p_requested_by::text,'system'),p_preview_hash,p_snapshot,p_correlation_id,p_causation_id);
  return query select v_preview.id,v_preview.status,v_preview.row_version,true;
end $$;

revoke all on function public.apply_workspace_finished_bom_snapshot(text,text,text,numeric,jsonb,jsonb,timestamptz) from public,anon,authenticated;
grant execute on function public.apply_workspace_finished_bom_snapshot(text,text,text,numeric,jsonb,jsonb,timestamptz) to service_role;
revoke all on function public.apply_workspace_supplier_order_snapshot(text,jsonb,jsonb,timestamptz) from public,anon,authenticated;
grant execute on function public.apply_workspace_supplier_order_snapshot(text,jsonb,jsonb,timestamptz) to service_role;
revoke all on function public.persist_workspace_v3_preview(uuid,uuid,text,text,text,text,integer,text,text,text,jsonb,uuid,uuid,uuid,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.persist_workspace_v3_preview(uuid,uuid,text,text,text,text,integer,text,text,text,jsonb,uuid,uuid,uuid,jsonb,jsonb) to service_role;

create or replace function public.confirm_workspace_v3_after_mes(
  p_preview_id bigint,
  p_external_id uuid,
  p_idempotency_key text,
  p_payload_hash text,
  p_expected_row_version bigint,
  p_mes_confirmation_id uuid,
  p_mes_production_order_id integer,
  p_mes_production_order_number text,
  p_actor text,
  p_correlation_id uuid,
  p_causation_id uuid default null
) returns table(saga_id bigint, status text, requirements_created integer)
language plpgsql security definer set search_path = public as $$
declare
  v_preview public.workspace_v3_previews%rowtype;
  v_saga public.workspace_v3_confirmation_sagas%rowtype;
  v_component public.workspace_v3_preview_components%rowtype;
  v_commitment_id bigint;
  v_requirements integer := 0;
begin
  if not coalesce((select enabled from public.workspace_v3_feature_flags where key='workspacemes.v3.confirm'), false) then
    raise exception 'WORKSPACEMES_V3_CONFIRM_DISABLED';
  end if;
  select * into v_preview from public.workspace_v3_previews where id=p_preview_id for update;
  if not found then raise exception 'V3_PREVIEW_NOT_FOUND'; end if;
  if v_preview.row_version <> p_expected_row_version then raise exception 'V3_CONCURRENT_MODIFICATION'; end if;
  if v_preview.status <> 'READY' then raise exception 'V3_PREVIEW_NOT_READY'; end if;
  select * into v_saga from public.workspace_v3_confirmation_sagas where idempotency_key=p_idempotency_key for update;
  if found then
    if v_saga.payload_hash <> p_payload_hash then raise exception 'V3_IDEMPOTENCY_CONFLICT'; end if;
    return query select v_saga.id, v_saga.status, 0;
    return;
  end if;
  insert into public.workspace_v3_confirmation_sagas(external_id,preview_id,idempotency_key,payload_hash,status,
    mes_confirmation_id,mes_production_order_id,mes_production_order_number,correlation_id,causation_id)
  values(p_external_id,p_preview_id,p_idempotency_key,p_payload_hash,'MATERIALIZING_WORKSPACE',
    p_mes_confirmation_id,p_mes_production_order_id,p_mes_production_order_number,p_correlation_id,p_causation_id)
  returning * into v_saga;
  for v_component in select * from public.workspace_v3_preview_components where preview_id=p_preview_id loop
    if v_component.required_quantity <= 0 then continue; end if;
    if v_component.component_kind='FORMULA_COMPONENT' then continue; end if;
    insert into public.workspace_v3_material_commitments(saga_id,preview_component_id,owner,article_code,unit_of_measure,quantity,source_commitment_id,status)
    values(v_saga.id,v_component.id,case when v_component.component_kind='DIRECT_COMPONENT' then 'WORKSPACE_DIRECT' else 'PROGREMES_MP_CERTIFIED' end,
      v_component.article_code,v_component.unit_of_measure,v_component.required_quantity,
      case when v_component.component_kind='FORMULA_MATERIAL' then p_mes_confirmation_id::text else null end,'ACTIVE')
    returning id into v_commitment_id;
    if v_component.uncovered_quantity > 0 then
      insert into public.workspace_v3_purchase_requirements(saga_id,commitment_id,article_code,unit_of_measure,required_quantity,expected_at,status,lineage)
      values(v_saga.id,v_commitment_id,v_component.article_code,v_component.unit_of_measure,v_component.uncovered_quantity,
        v_component.required_at,'OPEN',jsonb_build_object('previewId',p_preview_id,'componentId',v_component.id,
        'productionOrderId',p_mes_production_order_id,'productionOrderNumber',p_mes_production_order_number));
      v_requirements := v_requirements + 1;
    end if;
  end loop;
  update public.workspace_v3_confirmation_sagas set status='COMPLETED',completed_at=now(),updated_at=now(),row_version=row_version+1 where id=v_saga.id;
  update public.workspace_v3_previews set status='CONFIRMED',confirmed_at=now(),row_version=row_version+1 where id=p_preview_id;
  insert into public.workspace_v3_outbox(aggregate_type,aggregate_id,destination,event_type,sequence,payload,payload_hash,correlation_id,causation_id)
  values('V3_CONFIRMATION_SAGA',v_saga.id::text,'WORKSPACE','WorkspaceV3Confirmed',1,
    jsonb_build_object('sagaId',v_saga.id,'previewId',p_preview_id,'productionOrderId',p_mes_production_order_id,'requirementsCreated',v_requirements),
    p_payload_hash,p_correlation_id,p_causation_id);
  insert into public.workspace_v3_audit(aggregate_type,aggregate_id,action,actor_id,after_hash,payload,correlation_id,causation_id)
  values('V3_CONFIRMATION_SAGA',v_saga.id::text,'CONFIRMED',p_actor,p_payload_hash,
    jsonb_build_object('previewId',p_preview_id,'requirementsCreated',v_requirements),p_correlation_id,p_causation_id);
  return query select v_saga.id, 'COMPLETED'::text, v_requirements;
end $$;

revoke all on function public.confirm_workspace_v3_after_mes(bigint,uuid,text,text,bigint,uuid,integer,text,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.confirm_workspace_v3_after_mes(bigint,uuid,text,text,bigint,uuid,integer,text,text,uuid,uuid) to service_role;

create or replace function public.create_workspace_v3_purchase_document(
  p_external_id uuid,
  p_document_type text,
  p_parent_document_id bigint,
  p_supplier_external_ref text,
  p_document_number text,
  p_currency text,
  p_valid_until date,
  p_payload_hash text,
  p_idempotency_key text,
  p_correlation_id uuid,
  p_actor text,
  p_lines jsonb
) returns table(document_id bigint,document_type text,status text,created boolean)
language plpgsql security definer set search_path=public as $$
declare
  v_document public.workspace_v3_purchase_documents%rowtype;
  v_parent public.workspace_v3_purchase_documents%rowtype;
  v_line jsonb;
  v_requirement public.workspace_v3_purchase_requirements%rowtype;
  v_expected_parent text;
  v_requirement_status text;
begin
  if not coalesce((select enabled from public.workspace_v3_feature_flags where key='workspacemes.v3.purchasing'),false)
  then raise exception 'WORKSPACEMES_V3_PURCHASING_DISABLED'; end if;
  if p_document_type not in ('PROPOSAL','RFQ','QUOTE','SUPPLIER_ORDER') or jsonb_typeof(p_lines)<>'array' or jsonb_array_length(p_lines)=0
  then raise exception 'INVALID_V3_PURCHASE_DOCUMENT'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key,0));
  select * into v_document from public.workspace_v3_purchase_documents where idempotency_key=p_idempotency_key;
  if found then
    if v_document.payload_hash<>p_payload_hash then raise exception 'V3_PURCHASE_IDEMPOTENCY_CONFLICT'; end if;
    return query select v_document.id,v_document.document_type,v_document.status,false; return;
  end if;

  v_expected_parent := case p_document_type when 'RFQ' then 'PROPOSAL' when 'QUOTE' then 'RFQ' when 'SUPPLIER_ORDER' then 'QUOTE' else null end;
  if v_expected_parent is null and p_parent_document_id is not null then raise exception 'V3_PURCHASE_PARENT_NOT_ALLOWED'; end if;
  if v_expected_parent is not null then
    select * into v_parent from public.workspace_v3_purchase_documents where id=p_parent_document_id for update;
    if not found or v_parent.document_type<>v_expected_parent then raise exception 'V3_PURCHASE_PARENT_INVALID'; end if;
  end if;
  if p_document_type in ('QUOTE','SUPPLIER_ORDER') and nullif(trim(p_supplier_external_ref),'') is null
  then raise exception 'V3_PURCHASE_SUPPLIER_REQUIRED'; end if;

  insert into public.workspace_v3_purchase_documents(external_id,document_type,parent_document_id,supplier_external_ref,
    status,document_number,currency,valid_until,payload_hash,idempotency_key,correlation_id)
  values(p_external_id,p_document_type,p_parent_document_id,nullif(trim(p_supplier_external_ref),''),'PREPARED',
    nullif(trim(p_document_number),''),nullif(trim(p_currency),''),p_valid_until,p_payload_hash,p_idempotency_key,p_correlation_id)
  returning * into v_document;

  v_requirement_status := case p_document_type when 'PROPOSAL' then 'IN_PROPOSAL' when 'RFQ' then 'IN_RFQ'
    when 'QUOTE' then 'QUOTED' when 'SUPPLIER_ORDER' then 'ORDERED' end;
  for v_line in select value from jsonb_array_elements(p_lines) loop
    select * into v_requirement from public.workspace_v3_purchase_requirements
      where id=(v_line->>'requirementId')::bigint for update;
    if not found or v_requirement.status='CANCELLED' or (v_line->>'quantity')::numeric<=0 or
       (v_line->>'quantity')::numeric>v_requirement.required_quantity
    then raise exception 'V3_PURCHASE_REQUIREMENT_INVALID'; end if;
    if v_parent.id is not null and not exists(select 1 from public.workspace_v3_purchase_document_lines
      where document_id=v_parent.id and requirement_id=v_requirement.id)
    then raise exception 'V3_PURCHASE_LINEAGE_INVALID'; end if;
    insert into public.workspace_v3_purchase_document_lines(document_id,requirement_id,quantity,unit_price,expected_at)
    values(v_document.id,v_requirement.id,(v_line->>'quantity')::numeric,(v_line->>'unitPrice')::numeric,
      (v_line->>'expectedAt')::timestamptz);
    update public.workspace_v3_purchase_requirements set status=v_requirement_status,row_version=row_version+1,updated_at=now()
      where id=v_requirement.id;
  end loop;
  insert into public.workspace_v3_outbox(aggregate_type,aggregate_id,destination,event_type,sequence,payload,payload_hash,correlation_id)
  values('V3_PURCHASE_DOCUMENT',v_document.id::text,'WORKSPACE',
    case when p_document_type='SUPPLIER_ORDER' then 'SupplierOrderPreparedNotSent' else 'PurchaseDocumentPrepared' end,
    1,jsonb_build_object('documentId',v_document.id,'documentType',p_document_type,'sendToMexal',false),p_payload_hash,p_correlation_id);
  insert into public.workspace_v3_audit(aggregate_type,aggregate_id,action,actor_id,after_hash,payload,correlation_id)
  values('V3_PURCHASE_DOCUMENT',v_document.id::text,p_document_type||'_PREPARED',p_actor,p_payload_hash,
    jsonb_build_object('parentDocumentId',p_parent_document_id,'sendToMexal',false),p_correlation_id);
  return query select v_document.id,v_document.document_type,v_document.status,true;
end $$;

revoke all on function public.create_workspace_v3_purchase_document(uuid,text,bigint,text,text,text,date,text,text,uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.create_workspace_v3_purchase_document(uuid,text,bigint,text,text,text,date,text,text,uuid,text,jsonb) to service_role;

comment on table public.workspace_v3_previews is 'Snapshot V3 append-only: preview senza impegni, fabbisogni o prenotazioni.';
comment on table public.workspace_v3_purchase_requirements is 'Fabbisogno acquisti Workspace aggregato da DIRECT e copia certificata MP MES.';
comment on table public.workspace_supplier_order_snapshots is 'Fotografia append-only ordini fornitore Mexal. La WebAPI usata in produzione non espone il ricevuto: non viene inferito.';
comment on table public.workspace_v3_feature_flags is 'Gate V3 e sincronizzazioni legacy separabili; V3 resta fail-closed fino al collaudo.';
