begin;

-- ============================================================
-- ORDER MODULES CONFIGURATION
-- ============================================================

create table if not exists public.ordini_moduli_configurazione (
  id bigint generated by default as identity primary key,

  modulo text not null,
  mese integer,
  anno integer,

  attivo boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ordini_moduli_configurazione_mese_check
    check (
      mese is null
      or (mese >= 1 and mese <= 12)
    ),

  constraint ordini_moduli_configurazione_anno_check
    check (
      anno is null
      or anno >= 2000
    )
);


-- ============================================================
-- INDICI
-- ============================================================

create index if not exists ordini_testate_modulo_mese_idx
on public.ordini_moduli_configurazione (
  modulo,
  anno,
  mese
);


-- ============================================================
-- UPDATED AT
-- ============================================================

create or replace function public.set_ordini_moduli_configurazione_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists ordini_moduli_configurazione_updated_at
on public.ordini_moduli_configurazione;


create trigger ordini_moduli_configurazione_updated_at
before update on public.ordini_moduli_configurazione
for each row
execute function public.set_ordini_moduli_configurazione_updated_at();


-- ============================================================
-- RLS
-- ============================================================

alter table public.ordini_moduli_configurazione enable row level security;


-- ============================================================
-- LETTURA UTENTI AUTENTICATI
-- ============================================================

drop policy if exists "authenticated read order module config"
on public.ordini_moduli_configurazione;


create policy "authenticated read order module config"
on public.ordini_moduli_configurazione
for select
to authenticated
using (true);


-- ============================================================
-- GESTIONE ADMIN
-- ============================================================

drop policy if exists "admins manage order module config"
on public.ordini_moduli_configurazione;


create policy "admins manage order module config"
on public.ordini_moduli_configurazione
for all
to authenticated
using (
  exists (
    select 1
    from public.utenti u
    left join public.ruoli r
      on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (
        coalesce(r.livello,0) >= 80
        or lower(coalesce(r.nome,'')) in (
          'admin',
          'administrator',
          'amministratore',
          'super admin',
          'direzione'
        )
      )
  )
)
with check (
  exists (
    select 1
    from public.utenti u
    left join public.ruoli r
      on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (
        coalesce(r.livello,0) >= 80
        or lower(coalesce(r.nome,'')) in (
          'admin',
          'administrator',
          'amministratore',
          'super admin',
          'direzione'
        )
      )
  )
);


commit;