begin;

create table if not exists public.ordini_email_invio (
  id bigint generated by default as identity primary key,
  ordine_id uuid not null
    references public.ordini_testate(id)
    on delete cascade,
  evento text not null,
  tipo_destinatario text not null,
  destinatario text not null,
  stato text not null default 'queued',
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  available_at timestamptz not null default now(),
  worker_id text,
  lock_token uuid,
  lease_expires_at timestamptz,
  oggetto text not null,
  allegati jsonb not null default '[]'::jsonb,
  config_snapshot jsonb not null default '{}'::jsonb,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz,
  constraint ordini_email_invio_idempotency_key
    unique (ordine_id, evento, destinatario),
  constraint ordini_email_invio_evento_not_blank
    check (btrim(evento) <> ''),
  constraint ordini_email_invio_tipo_destinatario_not_blank
    check (btrim(tipo_destinatario) <> ''),
  constraint ordini_email_invio_destinatario_not_blank
    check (btrim(destinatario) <> ''),
  constraint ordini_email_invio_stato_check
    check (stato in ('queued', 'leased', 'sending', 'retry', 'sent', 'failed', 'cancelled')),
  constraint ordini_email_invio_attempts_check
    check (attempts >= 0 and max_attempts > 0 and attempts <= max_attempts),
  constraint ordini_email_invio_allegati_array_check
    check (jsonb_typeof(allegati) = 'array'),
  constraint ordini_email_invio_config_snapshot_object_check
    check (jsonb_typeof(config_snapshot) = 'object')
);

create index if not exists ordini_email_invio_available_idx
  on public.ordini_email_invio (available_at, id)
  where stato in ('queued', 'retry');

create index if not exists ordini_email_invio_expired_lease_idx
  on public.ordini_email_invio (lease_expires_at, id)
  where stato in ('leased', 'sending');

create index if not exists ordini_email_invio_ordine_idx
  on public.ordini_email_invio (ordine_id, created_at desc);

create or replace function public.set_ordini_email_invio_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ordini_email_invio_updated_at
on public.ordini_email_invio;

create trigger ordini_email_invio_updated_at
before update on public.ordini_email_invio
for each row
execute function public.set_ordini_email_invio_updated_at();

alter table public.ordini_email_invio enable row level security;

drop policy if exists "admins read order email queue"
on public.ordini_email_invio;

create policy "admins read order email queue"
on public.ordini_email_invio
for select
to authenticated
using (
  exists (
    select 1
    from public.utenti u
    left join public.ruoli r
      on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (
        coalesce(r.livello, 0) >= 80
        or lower(coalesce(r.nome, '')) in (
          'admin',
          'administrator',
          'amministratore',
          'super admin',
          'direzione'
        )
      )
  )
);

revoke all on table public.ordini_email_invio from public, anon, authenticated;
grant select on table public.ordini_email_invio to authenticated;
grant all on table public.ordini_email_invio to service_role;
grant usage, select on sequence public.ordini_email_invio_id_seq to service_role;

commit;
