-- Stores the response of explicitly idempotent manual Mexal start requests.
-- A separate ledger is needed because sync_all can create more than one sync run.
create table if not exists public.mexal_sync_idempotency (
  id bigint generated by default as identity primary key,
  idempotency_key text not null check (char_length(idempotency_key) between 1 and 255),
  sync_type text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  sync_run_id bigint references public.mexal_sync_runs(id) on delete set null,
  response jsonb,
  created_at timestamptz not null default now(),
  unique (idempotency_key, sync_type, user_id)
);

create index if not exists mexal_sync_idempotency_run_idx
  on public.mexal_sync_idempotency (sync_run_id);

alter table public.mexal_sync_idempotency enable row level security;
