create table if not exists public.documenti_sync_config (
  id smallint primary key default 1 check (id=1),
  automatica_attiva boolean not null default false,
  ora smallint not null default 23 check (ora between 0 and 23),
  minuto smallint not null default 0 check (minuto between 0 and 59),
  ultima_esecuzione_il timestamptz,
  prossima_esecuzione_il timestamptz,
  ultimo_stato text,
  ultimo_errore text,
  aggiornato_il timestamptz not null default now()
);
insert into public.documenti_sync_config(id, prossima_esecuzione_il)
values (1, (((now() at time zone 'Europe/Rome')::date + case when (now() at time zone 'Europe/Rome')::time < time '23:00' then 0 else 1 end)::timestamp + time '23:00') at time zone 'Europe/Rome')
on conflict(id) do nothing;

create table if not exists public.documenti_sync_runs (
  id bigint generated by default as identity primary key,
  origine text not null default 'manuale' check (origine in ('manuale','automatica')),
  stato text not null default 'in_coda' check (stato in ('in_coda','in_esecuzione','completata','completata_con_errori','arrestata','errore')),
  arresto_richiesto boolean not null default false,
  iniziata_il timestamptz not null default now(),
  completata_il timestamptz,
  file_totali integer not null default 0,
  file_elaborati integer not null default 0,
  file_rimossi integer not null default 0,
  errore text,
  dettagli jsonb not null default '{}'::jsonb,
  aggiornata_il timestamptz not null default now()
);
create index if not exists documenti_sync_runs_started_idx on public.documenti_sync_runs(iniziata_il desc);

alter table public.documenti_sync_config enable row level security;
alter table public.documenti_sync_runs enable row level security;
drop policy if exists "admins manage document sync config" on public.documenti_sync_config;
create policy "admins manage document sync config" on public.documenti_sync_config for all to authenticated using (exists(select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione')))) with check (exists(select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))));
drop policy if exists "admins read document sync runs" on public.documenti_sync_runs;
create policy "admins read document sync runs" on public.documenti_sync_runs for select to authenticated using (exists(select 1 from public.utenti u left join public.ruoli r on r.id=u.ruolo_id where u.auth_user_id=auth.uid() and u.attivo is not false and (coalesce(r.livello,0)>=80 or lower(coalesce(r.nome,'')) in ('admin','administrator','amministratore','super admin','direzione'))));
grant select,insert,update,delete on public.documenti_sync_config to authenticated;
grant select on public.documenti_sync_runs to authenticated;
