-- Fase 1: nettificazione prodotto finito, UDM e snapshot auditabile.
-- Questa migration prepara soltanto il repository: non abilita alcun flusso mutante.

alter table if exists public.ordini_righe
  add column if not exists unita_misura_oct text,
  add column if not exists tipo_unita_misura_mexal text;

alter table if exists public.workspace_production_requests
  add column if not exists availability_snapshot_id bigint,
  add column if not exists quantita_richiesta_oct numeric(18,6),
  add column if not exists quantita_richiesta_prodotto numeric(18,6),
  add column if not exists quantita_disponibile_pf numeric(18,6),
  add column if not exists quantita_coperta_scorta numeric(18,6),
  add column if not exists quantita_da_produrre numeric(18,6),
  add column if not exists unita_misura_oct text,
  add column if not exists unita_misura_prodotto text,
  add column if not exists unita_misura_effettiva text,
  add column if not exists sent_availability_snapshot_id bigint,
  add column if not exists sent_quantita_da_produrre numeric(18,6),
  add column if not exists sent_unita_misura text,
  add column if not exists availability_validated_at timestamptz;

alter table public.workspace_production_requests
  add constraint workspace_production_requests_requested_oct_nonnegative
    check (quantita_richiesta_oct is null or quantita_richiesta_oct >= 0),
  add constraint workspace_production_requests_requested_product_nonnegative
    check (quantita_richiesta_prodotto is null or quantita_richiesta_prodotto >= 0),
  add constraint workspace_production_requests_available_pf_nonnegative
    check (quantita_disponibile_pf is null or quantita_disponibile_pf >= 0),
  add constraint workspace_production_requests_covered_stock_nonnegative
    check (quantita_coperta_scorta is null or quantita_coperta_scorta >= 0),
  add constraint workspace_production_requests_to_produce_nonnegative
    check (quantita_da_produrre is null or quantita_da_produrre >= 0);

create table if not exists public.workspace_production_availability_snapshots (
  id bigint generated by default as identity primary key,
  production_request_id uuid not null references public.workspace_production_requests(id) on delete cascade,
  ordine_id uuid not null references public.ordini_testate(id) on delete cascade,
  ordine_riga_id uuid not null references public.ordini_righe(id) on delete cascade,
  codice_articolo text not null,
  quantita_richiesta_oct numeric(18,6) not null check (quantita_richiesta_oct >= 0),
  quantita_richiesta_prodotto numeric(18,6) not null check (quantita_richiesta_prodotto >= 0),
  quantita_disponibile_pf numeric(18,6) not null check (quantita_disponibile_pf >= 0),
  quantita_coperta_scorta numeric(18,6) not null check (quantita_coperta_scorta >= 0),
  quantita_da_produrre numeric(18,6) not null check (quantita_da_produrre >= 0),
  unita_misura_oct text,
  unita_misura_prodotto text not null,
  unita_misura_effettiva text not null,
  conversione jsonb,
  regola_magazzini jsonb not null,
  product_updated_at timestamptz not null,
  product_last_sync_at timestamptz,
  snapshot_hash text not null,
  snapshot jsonb not null,
  captured_at timestamptz not null default now(),
  last_validated_at timestamptz not null default now(),
  unique (production_request_id, snapshot_hash)
);

alter table public.workspace_production_requests
  add constraint workspace_production_requests_availability_snapshot_fk
  foreign key (availability_snapshot_id) references public.workspace_production_availability_snapshots(id);

alter table public.workspace_production_requests
  add constraint workspace_production_requests_sent_availability_snapshot_fk
  foreign key (sent_availability_snapshot_id) references public.workspace_production_availability_snapshots(id);

alter table public.workspace_production_availability_snapshots enable row level security;
revoke all on public.workspace_production_availability_snapshots from anon, authenticated;

create index if not exists workspace_production_availability_snapshots_line_idx
  on public.workspace_production_availability_snapshots (ordine_riga_id, captured_at desc);

create or replace function public.record_workspace_production_netting(
  p_ordine_id uuid,
  p_ordine_riga_id uuid,
  p_codice_articolo text,
  p_quantita_richiesta_oct numeric,
  p_quantita_richiesta_prodotto numeric,
  p_quantita_disponibile numeric,
  p_quantita_coperta numeric,
  p_quantita_da_produrre numeric,
  p_udm_oct text,
  p_udm_prodotto text,
  p_udm_effettiva text,
  p_conversione jsonb,
  p_regola_magazzini jsonb,
  p_product_updated_at timestamptz,
  p_product_last_sync_at timestamptz,
  p_snapshot_hash text,
  p_snapshot jsonb
) returns table(request_id uuid, external_id uuid, snapshot_id bigint, snapshot_captured_at timestamptz, reused boolean, attempt_count integer)
language plpgsql security definer set search_path = public as $$
declare
  v_request public.workspace_production_requests%rowtype;
  v_snapshot public.workspace_production_availability_snapshots%rowtype;
  v_product record;
  v_reused boolean := false;
begin
  if p_quantita_richiesta_oct < 0 or p_quantita_richiesta_prodotto < 0 or
     p_quantita_disponibile < 0 or p_quantita_coperta < 0 or p_quantita_da_produrre < 0 then
    raise exception 'NEGATIVE_QUANTITY';
  end if;
  if p_quantita_coperta > p_quantita_richiesta_prodotto or
     p_quantita_da_produrre <> greatest(0, p_quantita_richiesta_prodotto - p_quantita_coperta) then
    raise exception 'INVALID_NETTING_TOTALS';
  end if;

  select p.disponibilita, p.updated_at, p.ultimo_sync_mexal
    into strict v_product
    from public.prodotti p
    where upper(btrim(p.codice_mexal)) = upper(btrim(p_codice_articolo))
      and p.sincronizzato_mexal = true and p.attivo_mexal = true
    for update;
  if coalesce(v_product.disponibilita, 0)::numeric <> p_quantita_disponibile or
     v_product.updated_at is distinct from p_product_updated_at or
     v_product.ultimo_sync_mexal is distinct from p_product_last_sync_at then
    raise exception 'AVAILABILITY_CHANGED';
  end if;

  insert into public.workspace_production_requests (ordine_id, ordine_riga_id)
    values (p_ordine_id, p_ordine_riga_id)
    on conflict (ordine_riga_id) do update set updated_at = public.workspace_production_requests.updated_at
    returning * into v_request;

  insert into public.workspace_production_availability_snapshots (
    production_request_id, ordine_id, ordine_riga_id, codice_articolo,
    quantita_richiesta_oct, quantita_richiesta_prodotto, quantita_disponibile_pf,
    quantita_coperta_scorta, quantita_da_produrre, unita_misura_oct,
    unita_misura_prodotto, unita_misura_effettiva, conversione, regola_magazzini,
    product_updated_at, product_last_sync_at, snapshot_hash, snapshot
  ) values (
    v_request.id, p_ordine_id, p_ordine_riga_id, upper(btrim(p_codice_articolo)),
    p_quantita_richiesta_oct, p_quantita_richiesta_prodotto, p_quantita_disponibile,
    p_quantita_coperta, p_quantita_da_produrre, nullif(upper(btrim(p_udm_oct)), ''),
    upper(btrim(p_udm_prodotto)), upper(btrim(p_udm_effettiva)), p_conversione,
    p_regola_magazzini, p_product_updated_at, p_product_last_sync_at,
    p_snapshot_hash, p_snapshot
  ) on conflict (production_request_id, snapshot_hash) do nothing
  returning * into v_snapshot;
  if not found then
    v_reused := true;
    update public.workspace_production_availability_snapshots
      set last_validated_at = now()
      where production_request_id = v_request.id and snapshot_hash = p_snapshot_hash
      returning * into strict v_snapshot;
  end if;

  update public.workspace_production_requests set
    availability_snapshot_id = v_snapshot.id,
    quantita_richiesta_oct = p_quantita_richiesta_oct,
    quantita_richiesta_prodotto = p_quantita_richiesta_prodotto,
    quantita_disponibile_pf = p_quantita_disponibile,
    quantita_coperta_scorta = p_quantita_coperta,
    quantita_da_produrre = p_quantita_da_produrre,
    unita_misura_oct = nullif(upper(btrim(p_udm_oct)), ''),
    unita_misura_prodotto = upper(btrim(p_udm_prodotto)),
    unita_misura_effettiva = upper(btrim(p_udm_effettiva)),
    availability_validated_at = now(),
    -- Una preview/rivalidazione successiva non deve arretrare uno stato già ricevuto dal MES.
    stato = case when v_request.sent_availability_snapshot_id is not null then stato
      when p_quantita_da_produrre = 0 then 'COPERTA_DA_SCORTA' else 'PRONTA' end,
    workspace_status = case when v_request.sent_availability_snapshot_id is not null then workspace_status
      when p_quantita_da_produrre = 0 then 'COPERTA_DA_SCORTA' else 'PRONTA' end,
    updated_at = now()
  where id = v_request.id
  returning * into v_request;

  return query select v_request.id, v_request.external_id, v_snapshot.id, v_snapshot.captured_at, v_reused, v_request.attempt_count;
end $$;

revoke all on function public.record_workspace_production_netting(
  uuid,uuid,text,numeric,numeric,numeric,numeric,numeric,text,text,text,jsonb,jsonb,timestamptz,timestamptz,text,jsonb
) from public, anon, authenticated;
grant execute on function public.record_workspace_production_netting(
  uuid,uuid,text,numeric,numeric,numeric,numeric,numeric,text,text,text,jsonb,jsonb,timestamptz,timestamptz,text,jsonb
) to service_role;

comment on table public.workspace_production_availability_snapshots is
  'Snapshot append-only della nettificazione PF Workspace. Non costituisce prenotazione di magazzino Mexal.';
comment on column public.workspace_production_requests.sent_quantita_da_produrre is
  'Quantità effettivamente inviata a ProgreMES; usata per bloccare conferme dopo variazioni di disponibilità o UDM.';
