-- Registro append-only delle esecuzioni Mexal. Non modifica né elimina cataloghi esistenti.
create table if not exists public.mexal_sync_runs (
  id bigint generated by default as identity primary key,
  sync_type text not null check (sync_type in ('products', 'clients')),
  status text not null check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  processed integer not null default 0 check (processed >= 0),
  inserted integer not null default 0 check (inserted >= 0),
  updated integer not null default 0 check (updated >= 0),
  skipped integer not null default 0 check (skipped >= 0),
  failed integer not null default 0 check (failed >= 0),
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists mexal_sync_runs_type_started_idx
  on public.mexal_sync_runs (sync_type, started_at desc);

alter table public.mexal_sync_runs enable row level security;

drop policy if exists "admins read mexal sync runs" on public.mexal_sync_runs;
create policy "admins read mexal sync runs" on public.mexal_sync_runs
for select to authenticated
using (
  exists (
    select 1 from public.utenti u
    left join public.ruoli r on r.id = u.ruolo_id
    where u.auth_user_id = auth.uid()
      and u.attivo is not false
      and (coalesce(r.livello, 0) >= 80 or lower(coalesce(r.nome, '')) in ('admin', 'administrator', 'amministratore', 'super admin', 'direzione'))
  )
);
