// `mese_ordine` is generated by PostgreSQL from `data_ordine`: it must never
// be included in a write to ordini_testate. Keep this list intentionally
// narrow so a form state or a record returned by Supabase cannot leak read-only
// columns into an insert, upsert, or update.
const WRITABLE_ORDER_FIELDS = [
  "data_ordine",
  "stato",
  "codice_cliente",
  "ragione_sociale_cliente",
  "codice_agente_mexal",
  "codice_pagamento",
  "descrizione_pagamento",
  "codice_listino",
  "indirizzo_spedizione",
  "commenti",
  "totale",
  "note_mexal",
];

/**
 * Produces the only payload shape accepted by the New Order write flow.
 *
 * This is deliberately an allow-list rather than a destructuring/rest or
 * spread operation: records read from Supabase may contain generated columns
 * such as `mese_ordine`, identity columns, and other read-only fields.
 */
export function buildWritableOrderPayload(order) {
  return WRITABLE_ORDER_FIELDS.reduce((payload, field) => {
    if (Object.hasOwn(order, field)) payload[field] = order[field];
    return payload;
  }, {});
}

export function buildNewOrderInsertPayload({
  dataOrdine,
  customer,
  agentCode,
  payment,
  paymentDescription,
  comments,
  total,
}) {
  return buildWritableOrderPayload({
    data_ordine: dataOrdine,
    stato: "bozza",
    codice_cliente: customer.codice_cliente,
    ragione_sociale_cliente: customer.ragione_sociale,
    codice_agente_mexal: customer.codice_agente_mexal || agentCode || null,
    codice_pagamento: payment?.codice || customer.codice_pagamento || null,
    descrizione_pagamento: payment?.descrizione || paymentDescription(customer),
    codice_listino: customer.codice_listino || null,
    indirizzo_spedizione: [
      customer.indirizzo,
      customer.cap,
      customer.localita,
      customer.provincia,
    ].filter(Boolean).join(" "),
    commenti: comments.trim() || null,
    totale: total,
  });
}
