import { useState } from "react";
import { GitCompareArrows } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function MexalSettings({ settings, onChange, disabled }) {
  const navigate = useNavigate();
  const [advanced, setAdvanced] = useState(false);
  const update = (field, value) => onChange({ ...settings, [field]: value });

  return <section className="mexal-settings-panel"><div className="mexal-section-heading"><div><h3>Parametri sincronizzazione</h3><p>Connessione Mexal attiva. Le sincronizzazioni manuali sono disponibili nelle card.</p></div></div><div className="mexal-settings-grid"><div><strong>Automazione</strong><small>Un solo cron giornaliero Vercel Hobby avvia tutte le sincronizzazioni abilitate in sequenza.</small></div><div><strong>Ordine</strong><small>Clienti, prodotti, condizioni commerciali, serie documenti, giacenze e monitoraggio ordini.</small></div></div><button className="orders-secondary" type="button" onClick={() => navigate("/integrations/mexal/diagnostica")}><GitCompareArrows size={18} /> Apri diagnostica Mexal</button><button type="button" onClick={() => setAdvanced(!advanced)}>{advanced ? "Nascondi opzioni avanzate" : "Opzioni avanzate"}</button>{advanced && <div className="mexal-settings-grid"><label className="mexal-toggle-row"><input type="checkbox" checked={settings.dryRun} onChange={(e) => update("dryRun", e.target.checked)} disabled={disabled}/><span><strong>Dry Run</strong><small>Solo diagnostica: non scrive nel database.</small></span></label><label className="mexal-toggle-row"><input type="checkbox" checked={settings.syncPayments} onChange={(e) => update("syncPayments", e.target.checked)} disabled={disabled}/><span><strong>Regole pagamento</strong><small>Mantiene disponibili le condizioni per il motore ordini.</small></span></label><label className="mexal-select-row"><span><strong>Modalità</strong><small>Completa può disattivare regole non più presenti.</small></span><select value={settings.mode} onChange={(e) => update("mode", e.target.value)} disabled={disabled}><option value="full">Completa</option><option value="incremental">Incrementale</option></select></label></div>}</section>;
}
