import { useState } from "react";
const labels = { clients: "Clienti", products: "Prodotti", commercial_conditions: "Condizioni commerciali", document_series: "Serie documenti", stocks: "Giacenze", orders: "Ordini", agents: "Agenti", payments: "Pagamenti" };
export default function MexalSettings({ schedules = [], onSave, onRunNow, disabled }) {
  const [drafts, setDrafts] = useState({}); const [saving, setSaving] = useState(null);
  const value = (item) => drafts[item.sync_type] || item;
  const update = (item, field, next) => setDrafts((old) => ({ ...old, [item.sync_type]: { ...value(item), [field]: next } }));
  const save = async (item) => { setSaving(item.sync_type); try { await onSave(value(item)); setDrafts((old) => { const copy = { ...old }; delete copy[item.sync_type]; return copy; }); } finally { setSaving(null); } };
  return <section className="mexal-settings-panel"><div className="mexal-section-heading"><div><h3>Parametri sincronizzazione</h3><p>Le automazioni sono salvate nel database e interpretate in fuso Europe/Rome.</p></div></div><div className="mexal-schedules">{schedules.map((item) => { const current = value(item); return <article className="mexal-schedule" key={item.id || item.sync_type}><strong>{labels[item.sync_type] || item.sync_type}</strong><label><input type="checkbox" checked={current.enabled} onChange={(e) => update(item, "enabled", e.target.checked)} disabled={disabled}/> Abilitata</label><select value={current.schedule_mode} onChange={(e) => update(item, "schedule_mode", e.target.value)} disabled={disabled}><option value="manual">Manuale</option><option value="interval">Intervallo</option><option value="daily">Giornaliera</option><option value="weekly">Settimanale</option></select>{current.schedule_mode === "interval" ? <input aria-label="Frequenza minuti" type="number" min="1" value={current.frequency_minutes || 60} onChange={(e) => update(item, "frequency_minutes", Number(e.target.value))}/> : <><input aria-label="Ora" type="number" min="0" max="23" value={current.hour ?? 0} onChange={(e) => update(item, "hour", Number(e.target.value))}/><input aria-label="Minuti" type="number" min="0" max="59" value={current.minute ?? 0} onChange={(e) => update(item, "minute", Number(e.target.value))}/></>}<input aria-label="Dimensione lotto" type="number" min="1" value={current.batch_size || 12} onChange={(e) => update(item, "batch_size", Number(e.target.value))}/><small>Ultima: {item.last_run_at ? new Date(item.last_run_at).toLocaleString("it-IT") : "—"} · Prossima: {item.next_run_at ? new Date(item.next_run_at).toLocaleString("it-IT") : "al prossimo orario"} {item.last_error ? `· Errore: ${item.last_error}` : ""}</small><button type="button" onClick={() => save(item)} disabled={disabled || saving === item.sync_type}>{saving === item.sync_type ? "Salvo…" : "Salva"}</button><button type="button" onClick={() => onRunNow(item.sync_type)} disabled={disabled}>Esegui ora</button></article>; })}</div></section>;
}
