import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { supabase } from "../../../lib/supabaseClient";
import { customerOrderSeriesOptions } from "../../../components/documentSeriesOptions";
const defaults = { invia_automaticamente_mexal: false, serie_documento: "", invia_email_agente: false, invia_email_cliente: false, invia_email_responsabile: false, backoffice_1_email: "", backoffice_2_email: "" };
function Panel({ code, title, series }) {
  const [config, setConfig] = useState(defaults); const [message, setMessage] = useState("");
  useEffect(() => { supabase.from("ordini_moduli_configurazione").select("*").eq("modulo_ordini", code).maybeSingle().then(({ data, error }) => { if (error) setMessage(error.message); else setConfig({ ...defaults, ...data }); }); }, [code]);
  const set = (key, value) => setConfig((current) => ({ ...current, [key]: value }));
  async function save() { const { error } = await supabase.from("ordini_moduli_configurazione").upsert({ ...config, modulo_ordini: code, aggiornato_il: new Date().toISOString() }); setMessage(error ? error.message : "Configurazione salvata."); }
  return <section style={{ padding: 22, border: "1px solid #dbe3ec", borderRadius: 16, background: "#fff" }}><h3 style={{ marginTop: 0 }}>{title}</h3><p style={{ color: "#64748b" }}>Configurazione indipendente del modulo {title}.</p><label style={{ display: "flex", gap: 8, alignItems: "center", margin: "16px 0" }}><input type="checkbox" checked={config.invia_automaticamente_mexal} onChange={(e) => set("invia_automaticamente_mexal", e.target.checked)} /> Invia automaticamente gli ordini a Mexal</label>{config.invia_automaticamente_mexal && <label><strong>Serie documento</strong><select value={config.serie_documento} onChange={(e) => set("serie_documento", e.target.value)} style={{ width: "100%", minHeight: 40, marginTop: 6 }}><option value="">Seleziona serie...</option>{series.map((item) => <option key={item.source_key} value={item.serie}>{item.sigla_documento || item.tipo_documento} · Serie {item.serie} · {item.descrizione}</option>)}</select></label>}<fieldset style={{ border: 0, padding: 0, margin: "20px 0", display: "grid", gap: 10 }}><legend><strong>Configurazione Email</strong></legend>{[["invia_email_agente", "Invia email agente"], ["invia_email_cliente", "Invia email cliente"], ["invia_email_responsabile", "Invia email responsabile collegato"]].map(([key, label]) => <label key={key} style={{ display: "flex", gap: 8 }}><input type="checkbox" checked={config[key]} onChange={(e) => set(key, e.target.checked)} /> {label}: <strong>{config[key] ? "SI" : "NO"}</strong></label>)}</fieldset><div style={{ display: "grid", gap: 12 }}><label>Backoffice 1<input type="email" value={config.backoffice_1_email} onChange={(e) => set("backoffice_1_email", e.target.value)} style={{ display: "block", width: "100%", minHeight: 40, marginTop: 5 }} /></label><label>Backoffice 2<input type="email" value={config.backoffice_2_email} onChange={(e) => set("backoffice_2_email", e.target.value)} style={{ display: "block", width: "100%", minHeight: 40, marginTop: 5 }} /></label></div><button type="button" className="orders-primary" onClick={save} style={{ marginTop: 18 }}><Save size={16} /> Salva configurazione</button>{message && <p role="status">{message}</p>}</section>;
}
export default function OrderModuleSettings() { const [series, setSeries] = useState([]); useEffect(() => { supabase.from("ordini_serie_documenti").select("*").eq("attiva", true).order("sigla_documento").order("serie").then(({ data }) => setSeries(customerOrderSeriesOptions(data || []))); }, []); return <div><h2>Moduli Ordini</h2><p>Le impostazioni Mexal ed email sono separate per ciascuna area.</p><div className="mexal-two-columns"><Panel code="prof" title="ORDINI PROF" series={series} /><Panel code="ph" title="ORDINI PH" series={series} /></div></div>; }
